"use client";
import {useCallback,useEffect,useRef,useState,type FormEvent} from "react";
import dynamic from "next/dynamic";
import {adminOptionLabel,catalogDraftFormValues,catalogFields,type AdminField,type AdminRecord,type HumanChange} from "../../lib/admin-simple-catalog";
import {ADMIN_CATALOG_COPY,adminSaveLabel,adminSavedMessage,adminReferenceMessage} from "../../lib/admin-ui";
import {requestPrefill,type AdminRequestSeed} from "../../lib/admin-request-operations";
import {AdminCatalogFilters} from "./admin-catalog-filters";
import {AdminSheet} from "./admin-sheet";
import {AdminCourseGolfEditor} from "./admin-course-golf-editor";
import {AdminTournamentWizard} from "./admin-tournament-wizard";
import {AdminNumericValues,AdminHandedness} from "./admin-structured-values";
const CourseDetails=dynamic(()=>import("./admin-course-details").then(m=>m.AdminCourseDetails));
type Draft={id:string;entity_id:string;entity_type:string;status:string;payload:Record<string,unknown>};
type Lifecycle={references:number;canDelete:boolean;state:string;blocked?:boolean};
const ADVANCED=new Set(["latitude","longitude","sourceType","aliasesText","compressionSource","compressionSourceUrl"]);
export function VisualField({field,value,change}:{field:AdminField;value:unknown;change:(value:unknown)=>void}){
 if(field.type==="checkbox")return <label style={{display:"flex",alignItems:"center"}}><input style={{width:20}} type="checkbox" checked={value===true} onChange={e=>change(e.target.checked)}/>{field.label}</label>;
 return <label>{field.label}{field.type==="textarea"?<textarea required={field.required} maxLength={20000} value={String(value??"")} onChange={e=>change(e.target.value)}/>:field.options?<select required={field.required} value={String(value??"")} onChange={e=>change(e.target.value)}>{!field.required&&<option value="">Sin especificar</option>}{field.options.map(o=><option key={o} value={o}>{adminOptionLabel(o)}</option>)}</select>:<input required={field.required} type={field.type||"text"} inputMode={field.type==="number"?"decimal":undefined} min={field.min} max={field.max} step={field.type==="number"?"any":undefined} maxLength={500} value={String(value??"")} onChange={e=>change(e.target.value)} onInput={field.type==="date"||field.type==="datetime-local"?e=>change(e.currentTarget.value):undefined} onBlur={field.type==="date"||field.type==="datetime-local"?e=>change(e.currentTarget.value):undefined}/>}</label>;
}
const evidence:AdminField[]=[{key:"sourceName",label:"Fuente de la información",required:true},{key:"sourceUrl",label:"Enlace de referencia",type:"url"},{key:"verifiedAt",label:"Fecha de verificación",type:"date"}];
export function AdminVisualCatalog({token,module="courses",requestSeed,onRequestConsumed,onDetailChange}:{token:string;module?:string;requestSeed?:AdminRequestSeed|null;onRequestConsumed?:()=>void;onDetailChange?:(detail:boolean)=>void}){
 const [items,setItems]=useState<AdminRecord[]>([]),[drafts,setDrafts]=useState<Draft[]>([]);
 const [query,setQuery]=useState(""),[filter,setFilter]=useState("all"),[facets,setFacets]=useState<Record<string,string[]>>({}),[filters,setFilters]=useState<Record<string,string>>({});
 const [error,setError]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[editing,setEditing]=useState<AdminRecord|null>(null),[values,setValues]=useState<Record<string,unknown>>({});
 const [courses,setCourses]=useState<{id:string;title:string}[]>([]),[offset,setOffset]=useState(0),[nextOffset,setNextOffset]=useState<number|null>(null),[total,setTotal]=useState(0);
 const [preview,setPreview]=useState<{id:string;previewHash:string;changes:HumanChange[]}|null>(null),[reason,setReason]=useState(""),[confirmed,setConfirmed]=useState(false);
 const [section,setSection]=useState("info"),[advanced,setAdvanced]=useState(false),[lifecycle,setLifecycle]=useState<Lifecycle|null>(null);
 const copy=ADMIN_CATALOG_COPY[module]||ADMIN_CATALOG_COPY.equipment;
 useEffect(()=>{onDetailChange?.(!!editing);},[editing,onDetailChange]);
 const [loading,setLoading]=useState(true);
 const requestVersion=useRef(0);
 const [eligibility,setEligibility]=useState<Lifecycle|null>(null),[lifecycleOperation,setLifecycleOperation]=useState("archive-record");
 const [wizardStep,setWizardStep]=useState(0),[baseRevisionId,setBaseRevisionId]=useState<string|null>(null);
 const api=useCallback(async(body?:Record<string,unknown>,id?:string)=>{
  const params=new URLSearchParams({module,q:query,state:filter,offset:String(offset),...filters,...(id?{id}:{})});
  const r=await fetch(body?"/api/admin/simple":"/api/admin/simple?"+params,{method:body?"POST":"GET",headers:{authorization:"Bearer "+token,...(body?{"content-type":"application/json"}:{})},cache:"no-store",...(body?{body:JSON.stringify({...body,module})}:{})});
  const b=await r.json();if(!r.ok)throw new Error(b.error||"No pudimos completar la operación.");return b;
 },[token,module,query,filter,offset,filters]);
 const load=useCallback(async()=>{const version=++requestVersion.current;setLoading(true);let b;try{b=await api();}finally{if(version===requestVersion.current)setLoading(false);}if(version!==requestVersion.current)return;setItems(b.items||[]);setDrafts(b.drafts||[]);setCourses(b.courses||[]);setFacets(b.facets||{});setNextOffset(b.nextOffset??null);setTotal(b.total||0);setError("");},[api]);
 useEffect(()=>{const timer=setTimeout(()=>{void load().catch(e=>setError(e.message));},200);return()=>clearTimeout(timer);},[load]);
 function open(item:AdminRecord){setEditing(item);setValues({...item.values,verifiedAt:String(item.values.verifiedAt||"").slice(0,10),startsAt:String(item.values.startsAt||"").slice(0,16),endsAt:String(item.values.endsAt||"").slice(0,16)});setBaseRevisionId(null);setWizardStep(0);setPreview(null);setSection("info");setAdvanced(false);setLifecycle(null);setEligibility(null);setError("");setMessage("");}
 async function edit(item:AdminRecord){if(!item.id){open(item);return;}setBusy(true);try{const b=await api(undefined,item.id);if(!b.item)throw new Error("El registro ya no está disponible.");open(b.item);const inspected=await api({operation:"inspect",id:b.item.id,kind:b.item.kind});setEligibility(inspected.item);}catch(e){setError(e instanceof Error?e.message:"No pudimos abrir el registro.");}finally{setBusy(false);}}
 const patch=(key:string,value:unknown)=>setValues(v=>({...v,[key]:value}));
 async function action(body:Record<string,unknown>){if(busy)return;setBusy(true);setError("");try{const b=await api(body);if(body.operation==="preview"){setPreview({...b.preview,changes:b.changes});setConfirmed(false);setReason("");}else if(body.operation==="inspect"){setEligibility(b.item);setReason("");}else if(b.item?.blocked){setLifecycle(b.item);setError("Este registro tiene vínculos asociados. Puedes archivarlo para conservar su historia.");}else{setEditing(null);setPreview(null);setLifecycle(null);setMessage(adminSavedMessage(module,String(body.operation)));await load();}return b;}catch(e){setError(e instanceof Error?e.message:"No se guardaron los cambios.");}finally{setBusy(false);}}
 function save(e:FormEvent){e.preventDefault();void action({operation:"draft",id:editing?.id||undefined,copyFromId:values.copyFromId,baseRevisionId,requestId:values.requestId,kind:editing?.kind,values});}
 function create(){open({id:"",title:"Nuevo registro",subtitle:"",active:true,kind:module==="courses"?"COURSE":module==="balls"?"BALL":module==="competitions"?"COMPETITION":"CLUB_EQUIPMENT",values:module==="courses"?{name:"",clubName:"",holeCount:"18",active:true,tees:[],sourceName:"Verificación administrativa"}:{brand:"",model:"",active:true,bagEligible:true,fitEligible:false,sourceType:"ADMIN_RESEARCH",sourceName:"Verificación administrativa",category:"DRIVER",type:"TOURNAMENT",visibility:"PRIVATE",ruleBody:""}});}
 function createFromRequest(){create();setValues(current=>({...current,...requestPrefill(requestSeed!,module)}));onRequestConsumed?.();}
 const fields=editing?catalogFields(editing.kind):[];
 const family=(values.family||[]) as {id:string;title:string;active:boolean}[];
 const back=()=>{setEditing(null);setLifecycle(null);setPreview(null);};
 return <section className="adminV2Stack">
 {error&&<p role="alert" className="notice bad">{error}</p>}{message&&<p className="adminV2Feedback" role="status">{message}</p>}
 {requestSeed&&!editing&&<section className="notice"><h3>Crear desde solicitud</h3><p>{requestSeed.title}</p><p>{requestSeed.description}</p><button className="secondary" onClick={createFromRequest}>Revisar datos y completar registro</button></section>}
 {!editing&&<><div className="adminV2Actions"><button className="primary" disabled={busy} onClick={create}>+ {copy.add}</button></div><AdminCatalogFilters module={module} query={query} state={filter} facets={facets} filters={filters} onQuery={value=>{setQuery(value);setOffset(0);}} onApply={(state,next)=>{setFilter(state);setFilters(next);setOffset(0);}}/>
 {loading&&<div className="adminV2Loading" role="status" aria-label="Cargando registros"><div className="adminV2Skeleton"/><div className="adminV2Skeleton"/></div>}
 {!loading&&items.map(item=><article className="card adminV2ListItem" key={item.id}><div><h3>{item.title}</h3><p>{[...new Set(item.subtitle.split(" · "))].map(adminOptionLabel).join(" · ")} · {item.active?"Activo":"Archivado / histórico"}</p></div><button className="secondary" disabled={busy} aria-label={"Editar "+item.title} onClick={()=>void edit(item)}>Editar ›</button></article>)}
 {!items.length&&!error&&!loading&&<p className="adminV2Empty">{copy.empty}</p>}<div className="adminV2Pagination"><button className="secondary" disabled={!offset||loading} onClick={()=>setOffset(Math.max(0,offset-40))}>Anterior</button><p aria-live="polite">{total?(offset+1)+"–"+Math.min(offset+items.length,total)+" de "+total:"Sin resultados"}</p><button className="secondary" disabled={nextOffset===null||loading} onClick={()=>setOffset(nextOffset??offset)}>Siguiente</button></div></>}
 {editing&&<><button type="button" className="adminV2Back" onClick={back}>‹ {copy.title}</button>
 {family.length>1&&<label>Recorrido / tarjeta<select value={editing.id} onChange={e=>void edit({...editing,id:e.target.value})}>{family.map(child=><option key={child.id} value={child.id}>{child.title}</option>)}</select></label>}
 <form noValidate={module==="competitions"} className="card adminV2Editor adminV2Stack" onSubmit={save} onInvalid={()=>{setAdvanced(true);setSection("info");}}><h2>{editing.id?editing.title:copy.add}</h2>
 {(module==="equipment"||module==="balls"||module==="competitions")&&editing.id&&!baseRevisionId&&<button type="button" className="secondary" onClick={()=>open({...editing,id:"",title:"Duplicar registro",values:{...values,copyFromId:editing.id,model:String(values.model||"")+" · copia",name:String(values.name||"")+" · copia"}})}>Duplicar</button>}
 {module==="courses"&&<div className="adminV2Tabs">{[["info","Información"],["golf","Tees y tarjeta"],["versions","Versiones y reglas"]].map(([id,label])=><button type="button" className={section===id?"primary":"secondary"} key={id} onClick={()=>setSection(id)}>{label}</button>)}</div>}
 {(module!=="competitions"&&(module!=="courses"||section==="info"))&&<fieldset><legend>Básico</legend><div className="adminV2FormGrid">{fields.filter(f=>!ADVANCED.has(f.key)).map(f=>f.key==="handsText"?<AdminHandedness key={f.key} value={values[f.key]} change={v=>patch(f.key,v)}/>: ["loftsText","weightsText","torqueText"].includes(f.key)?<AdminNumericValues key={f.key} label={f.key==="loftsText"?"Lofts · grados":f.key==="weightsText"?"Pesos · gramos":"Torque"} value={values[f.key]} min={f.key==="weightsText"?1:0} max={f.key==="loftsText"?90:f.key==="weightsText"?300:30} change={v=>patch(f.key,v)}/>:<VisualField key={f.key} field={f} value={values[f.key]} change={v=>patch(f.key,v)}/>)}</div></fieldset>}
 {module==="equipment"&&!editing.id&&<label>Tipo<select value={editing.kind} onChange={e=>setEditing({...editing,kind:e.target.value as AdminRecord["kind"]})}><option value="CLUB_EQUIPMENT">Bastón</option><option value="SHAFT">Varilla</option></select></label>}
 {module==="courses"&&section==="golf"&&<AdminCourseGolfEditor values={values} patch={patch}/>}
 {module==="competitions"&&<AdminTournamentWizard step={wizardStep} setStep={setWizardStep} values={values} courses={courses} patch={patch} render={field=><VisualField key={field.key} field={field} value={values[field.key]} change={value=>patch(field.key,value)}/>}/>}
 {module==="competitions"&&editing.id&&values.competitionStatus==="PUBLISHED"&&<details><summary>Opciones del torneo</summary><label>Motivo<input value={reason} onChange={event=>setReason(event.target.value)}/></label><div className="adminV2Actions">{[["DRAFT","Despublicar"],["COMPLETED","Finalizar"]].map(([status,label])=><button type="button" key={status} className="secondary" disabled={busy||reason.trim().length<3} onClick={()=>{if(window.confirm(label+" este torneo. Su historia se conserva."))void action({operation:"competition-status",id:editing.id,expectedStatus:values.competitionStatus,status,reason,confirmed:true});}}>{label}</button>)}</div></details>}
 {section!=="versions"&&<details open={advanced} onToggle={e=>setAdvanced(e.currentTarget.open)}><summary>Avanzado · fuente y verificación</summary><div className="adminV2FormGrid">{[...fields.filter(f=>ADVANCED.has(f.key)),...evidence].map(f=><VisualField key={f.key} field={f} value={values[f.key]} change={v=>patch(f.key,v)}/>)}</div><p>Comprueba esta información antes de publicar.</p></details>}
 {section!=="versions"&&<div className="adminV2StickyActions"><button type="button" className="secondary" disabled={busy} onClick={back}>Cancelar</button><button className="primary" disabled={busy}>{busy?"Guardando…":adminSaveLabel(module,!!editing.id)}</button></div>}</form>
 {module==="courses"&&section==="versions"&&(editing.id?<CourseDetails token={token} courseId={editing.id}/>:<p className="notice">Guarda y publica el campo antes de agregar versiones o reglas.</p>)}
 {editing.id&&!baseRevisionId&&<section className="adminV2Stack"><div className="adminV2LifecycleActions"><button type="button" className="secondary" disabled={busy} onClick={()=>{setLifecycle(eligibility||{references:0,canDelete:false,state:"ACTIVE"});setLifecycleOperation(editing.active?"archive-record":"activate-record");setReason("");}}>{editing.active?"Archivar":"Activar"} {copy.singular}</button>{eligibility?.canDelete&&<button type="button" className="adminV2Danger" onClick={()=>{setLifecycle(eligibility);setLifecycleOperation("delete-record");setReason("");}}>Eliminar definitivamente</button>}</div>{eligibility&&!eligibility.canDelete&&<p className="adminV2Hint">{adminReferenceMessage(copy.singular,eligibility.references,false)}</p>}</section>}
 {lifecycle&&<AdminSheet title={(lifecycleOperation==="delete-record"?"Eliminar":lifecycleOperation==="activate-record"?"Activar":"Archivar")+" "+copy.singular} onClose={()=>setLifecycle(null)}><section className="adminV2Stack"><p>{lifecycleOperation==="delete-record"?"Esta acción no se puede deshacer. El registro no tiene históricos asociados.":lifecycleOperation==="activate-record"?"El registro volverá a estar disponible.":"El registro dejará de estar activo. Su historia se conserva."}</p><label>Motivo<input value={reason} maxLength={1000} onChange={e=>setReason(e.target.value)}/></label><div className="adminV2StickyActions"><button className="secondary" disabled={busy} onClick={()=>setLifecycle(null)}>Cancelar</button><button className={lifecycleOperation==="delete-record"?"adminV2Danger":"primary"} disabled={busy||reason.trim().length<3} onClick={()=>void action({operation:lifecycleOperation,id:editing.id,kind:editing.kind,reason,confirmed:true})}>{busy?"Guardando…":lifecycleOperation==="delete-record"?"Eliminar definitivamente":lifecycleOperation==="activate-record"?"Activar":"Archivar"}</button></div></section></AdminSheet>}
 </>}
 {!editing&&!!drafts.length&&<details><summary>Borradores guardados ({drafts.length})</summary><section className="adminV2Stack">{drafts.map(d=><article className="card adminV2ListItem" key={d.id}><div><h3>{String((d.payload.course as Record<string,unknown>)?.name||d.payload.name||d.payload.model||"Cambio guardado")}</h3><p>{d.status==="DRAFT"?"Borrador":"En revisión"}</p></div><div className="adminV2Actions">{["DRAFT","REVIEWED","VERIFIED"].includes(d.status)&&<button className="secondary" disabled={busy} onClick={()=>{open({id:d.entity_id,title:String((d.payload.course as Record<string,unknown>)?.name||d.payload.name||d.payload.model||"Borrador"),subtitle:"Borrador",active:true,kind:(d.entity_type||"COMPETITION") as AdminRecord["kind"],values:catalogDraftFormValues((d.entity_type||"COMPETITION") as AdminRecord["kind"],d.payload)});setBaseRevisionId(d.id);}}>Editar</button>}<button className="secondary" disabled={busy} onClick={()=>void action({operation:"preview",revisionId:d.id})}>Vista previa</button></div></article>)}</section></details>}
 {preview&&<section className="card adminV2Confirmation adminV2Stack"><h2>Revisa antes de publicar</h2><div className="adminV2Diff">{preview.changes.map((c,i)=><p key={i}><strong>{c.label}</strong><br/>{c.before} → {c.after}</p>)}</div><label>Motivo del cambio<input value={reason} maxLength={1000} onChange={e=>setReason(e.target.value)}/></label><label style={{display:"flex"}}><input style={{width:20}} type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>He revisado y verificado estos cambios</label><div className="adminV2StickyActions"><button className="secondary" disabled={busy} onClick={()=>setPreview(null)}>Cancelar</button><button className="primary" disabled={busy||!confirmed||reason.trim().length<3} onClick={()=>void action({operation:"publish",revisionId:preview.id,previewHash:preview.previewHash,reason,confirmed})}>Publicar</button></div></section>}
 </section>;
}
