"use client";
import { useCallback, useEffect, useState, type FormEvent } from "react";
import { COURSE_FIELDS, type AdminField, type AdminRecord, type HumanChange } from "../../lib/admin-simple-catalog";
import dynamic from "next/dynamic";
const CourseDetails=dynamic(()=>import("./admin-course-details").then(m=>m.AdminCourseDetails));
type Draft = {id:string;entity_id:string;entity_type:string;status:string;payload:Record<string,unknown>};
export function VisualField({ field, value, change }: {field:AdminField;value:unknown;change:(value:unknown)=>void}) {
  const attrs={required:field.required};
  if(field.type==="checkbox") return <label style={{display:"flex",alignItems:"center"}}><input style={{width:20}} type="checkbox" checked={value===true} onChange={e=>change(e.target.checked)} />{field.label}</label>;
  return <label>{field.label}{field.type==="textarea"?<textarea {...attrs} value={String(value??"")} maxLength={20000} onChange={e=>change(e.target.value)} />:field.options?<select {...attrs} value={String(value??"")} onChange={e=>change(e.target.value)}>{!field.required&&<option value="">Sin especificar</option>}{field.options.map(o=><option key={o} value={o}>{o}</option>)}</select>:<input {...attrs} type={field.type||"text"} min={field.min} max={field.max} step={field.type==="number"?"any":undefined} maxLength={500} value={String(value??"")} onChange={e=>change(e.target.value)} />}</label>;
}
const evidence:AdminField[]=[{key:"sourceName",label:"Fuente de la información",required:true},{key:"sourceUrl",label:"Enlace de referencia",type:"url"},{key:"verifiedAt",label:"Fecha en que verificaste la información",type:"date"}];
export function AdminVisualCatalog({token,module="courses"}:{token:string;module?:string}) {
  const [items,setItems]=useState<AdminRecord[]>([]),[drafts,setDrafts]=useState<Draft[]>([]),[query,setQuery]=useState(""),[filter,setFilter]=useState("all"),[error,setError]=useState(""),[busy,setBusy]=useState(false),[editing,setEditing]=useState<AdminRecord|null>(null),[values,setValues]=useState<Record<string,unknown>>({});
  const [preview,setPreview]=useState<{id:string;previewHash:string;changes:HumanChange[]}|null>(null),[reason,setReason]=useState(""),[confirmed,setConfirmed]=useState(false);
  const api=useCallback(async (body?:Record<string,unknown>)=>{
    const response=await fetch(body?"/api/admin/simple":`/api/admin/simple?module=${module}&q=${encodeURIComponent(query)}`,{method:body?"POST":"GET",headers:{authorization:`Bearer ${token}`,...(body?{"content-type":"application/json"}:{})},cache:"no-store",...(body?{body:JSON.stringify({...body,module})}:{})}); const result=await response.json();if(!response.ok)throw new Error(result.error||"No pudimos completar la operación.");return result;
  },[token,module,query]);
  const load=useCallback(async()=>{const data=await api();setItems(data.items||[]);setDrafts(data.drafts||[]);},[api]);
  useEffect(()=>{let current=true;const timer=setTimeout(()=>{void load().catch(e=>{if(current)setError(e.message);});},200);return()=>{current=false;clearTimeout(timer);};},[load]);
  function edit(item:AdminRecord){setEditing(item);setValues({...item.values,verifiedAt:String(item.values.verifiedAt||"").slice(0,10)});setPreview(null);setError("");}
  const patch=(key:string,value:unknown)=>setValues(current=>({...current,[key]:value}));
  async function action(body:Record<string,unknown>){setBusy(true);setError("");try{const result=await api(body);if(body.operation==="preview"){setPreview({...result.preview,changes:result.changes});setConfirmed(false);setReason("");}else{setEditing(null);setPreview(null);await load();}return result;}catch(e){setError(e instanceof Error?e.message:"No se guardaron los cambios.");}finally{setBusy(false);}}
  function save(event:FormEvent){event.preventDefault();void action({operation:"draft",id:editing?.id||undefined,values});}
  const tees=Array.isArray(values.tees)?values.tees as Record<string,unknown>[]:[];
  return <section className="adminV2Stack">{error&&<p role="alert" className="notice bad">{error}</p>}
    {!editing&&<><div className="adminV2Filter"><label>Buscar<input type="search" value={query} onChange={e=>setQuery(e.target.value)} /></label><label>Estado<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Todos</option><option value="active">Activos</option><option value="inactive">Inactivos / históricos</option></select></label></div><button className="primary" onClick={()=>edit({id:"",title:"Nuevo campo",subtitle:"",active:true,kind:"COURSE",values:{name:"",clubName:"",holeCount:"18",active:true,tees:[]}})}>+ Agregar campo</button>
    {items.filter(i=>filter==="all"||i.active===(filter==="active")).map(item=><article className="card adminV2ListItem" key={item.id}><div><h3>{item.title}</h3><p>{item.subtitle}</p><small>{item.active?"Activo":"Inactivo / histórico"}</small></div><button className="secondary" onClick={()=>edit(item)}>Editar →</button></article>)}{!items.length&&!error&&<p className="notice">No hay campos para esta búsqueda.</p>}</>}
    {editing&&<form className="card adminV2Editor adminV2Stack" onSubmit={save}><h2>{editing.id?"Editar campo":"Agregar campo"}</h2><fieldset><legend>Información</legend><div className="adminV2FormGrid">{COURSE_FIELDS.map(field=><VisualField key={field.key} field={field} value={values[field.key]} change={value=>patch(field.key,value)} />)}</div></fieldset>
    <fieldset><legend>Tees</legend>{tees.map((tee,index)=><section className="card adminV2Editor" key={String(tee.id||index)}><div className="adminV2FormGrid">{[{key:"name",label:"Nombre",required:true},{key:"color",label:"Color"},{key:"category",label:"Categoría"},{key:"rating",label:"Rating",type:"number",min:40,max:100},{key:"slope",label:"Slope",type:"number",min:55,max:155},{key:"par",label:"Par",type:"number"},{key:"totalYards",label:"Yardas",type:"number"},{key:"active",label:"Activo",type:"checkbox"}].map(field=><VisualField key={field.key} field={field as AdminField} value={tee[field.key]} change={value=>patch("tees",tees.map((t,i)=>i===index?{...t,[field.key]:value}:t))} />)}</div></section>)}<button className="secondary" type="button" onClick={()=>patch("tees",[...tees,{name:"",color:"",category:"",active:true}])}>+ Agregar tee</button><p>Desactiva los tees que ya no se usan. Sus históricos se conservan.</p></fieldset>
    <fieldset><legend>Fuente y verificación</legend><div className="adminV2FormGrid">{evidence.map(field=><VisualField key={field.key} field={field} value={values[field.key]} change={value=>patch(field.key,value)} />)}</div><p>La publicación de ratings requiere información verificada.</p></fieldset><div className="adminV2Actions"><button type="button" className="secondary" disabled={busy} onClick={()=>setEditing(null)}>Cancelar</button><button className="primary" disabled={busy}>{busy?"Guardando…":"Guardar borrador"}</button></div></form>}
    {editing?.id&&<CourseDetails token={token} courseId={editing.id}/>}
    {!!drafts.length&&<section className="adminV2Stack"><h2>Borradores guardados</h2>{drafts.map(draft=><article className="card adminV2ListItem" key={draft.id}><div><h3>{String((draft.payload.course as Record<string,unknown>)?.name||draft.payload.name||"Cambio guardado")}</h3><p>{draft.status==="DRAFT"?"Borrador":"En revisión"}</p></div><button className="secondary" disabled={busy} onClick={()=>void action({operation:"preview",revisionId:draft.id})}>Vista previa</button></article>)}</section>}
    {preview&&<section className="card adminV2Confirmation adminV2Stack"><h2>Revisa antes de publicar</h2><div className="adminV2Diff">{preview.changes.map((change,index)=><p key={index}><strong>{change.label}</strong><br/>{change.before} → {change.after}</p>)}</div><label>Motivo del cambio<input value={reason} maxLength={1000} onChange={e=>setReason(e.target.value)} /></label><label style={{display:"flex"}}><input style={{width:20}} type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)} />He revisado y verificado estos cambios</label><div className="adminV2Actions"><button className="secondary" disabled={busy} onClick={()=>setPreview(null)}>Cancelar</button><button className="primary" disabled={busy||!confirmed||reason.trim().length<3} onClick={()=>void action({operation:"publish",revisionId:preview.id,previewHash:preview.previewHash,reason,confirmed})}>Publicar</button></div></section>}
  </section>;
}
