"use client";
import {useEffect,useState} from "react";
import type {HumanChange} from "../../lib/admin-simple-catalog";
type Event={id:number;actor:string;role:string;action:string;entity:string;title:string;reason:string;date:string;changes:HumanChange[]};
const entities:Record<string,string>={COURSE:"Campos",CLUB_EQUIPMENT:"Equipment",BALL:"Bolas",SHAFT:"Varillas",COMPETITION:"Torneos",REQUEST:"Solicitudes",BET_PRESENTATION:"Apuestas",USER_ROLE:"Roles"};
export function AdminAudit({token}:{token:string}){
 const [items,setItems]=useState<Event[]>([]),[actors,setActors]=useState<{id:string;name:string}[]>([]),[error,setError]=useState(""),[offset,setOffset]=useState(0),[filters,setFilters]=useState<Record<string,string>>({});
 useEffect(()=>{const controller=new AbortController();const params=new URLSearchParams({offset:String(offset),...filters});void fetch("/api/admin/audit?"+params,{headers:{authorization:"Bearer "+token},cache:"no-store",signal:controller.signal}).then(async response=>{const body=await response.json();if(!response.ok)throw new Error(body.error);setItems(body.items);setActors(body.actors);setError("");}).catch(error=>{if(!controller.signal.aborted)setError(error.message);});return()=>controller.abort();},[token,offset,filters]);
 const change=(key:string,value:string)=>{setFilters(current=>({...current,[key]:value}));setOffset(0);};
 return <section className="adminV2Stack"><p>Los cambios se conservan. No se pueden borrar desde este panel.</p><details><summary>Filtrar auditoría</summary><div className="adminV2FormGrid"><label>Administrador<select value={filters.actor||""} onChange={event=>change("actor",event.target.value)}><option value="">Todos</option>{actors.map(actor=><option key={actor.id} value={actor.id}>{actor.name}</option>)}</select></label><label>Entidad<select value={filters.entity||""} onChange={event=>change("entity",event.target.value)}><option value="">Todas</option>{Object.entries(entities).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>Acción<select value={filters.action||""} onChange={event=>change("action",event.target.value)}><option value="">Todas</option>{[["PUBLISH","Publicar"],["ARCHIVE","Archivar"],["DELETE","Eliminar"],["ROLE","Permisos"],["REQUEST","Solicitudes"]].map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>Desde · UTC<input type="date" value={filters.from||""} onChange={event=>change("from",event.target.value)}/></label><label>Hasta · UTC<input type="date" value={filters.until||""} onChange={event=>change("until",event.target.value)}/></label></div></details>
 {error&&<p role="alert" className="notice bad">{error}</p>}{items.map(item=><details className="card adminV2AuditRow" key={item.id}><summary><strong>{item.title}</strong><span>{item.actor} · {item.role} · {new Date(item.date).toLocaleString("es-MX")}</span></summary><p>{item.reason||item.action.replaceAll("_"," ")}</p>{item.changes.map((change,index)=><p key={index}>{change.label}: {change.before} → {change.after}</p>)}</details>)}{!items.length&&!error&&<p className="notice">Sin cambios para estos filtros.</p>}<div className="adminV2Actions"><button className="secondary" disabled={!offset} onClick={()=>setOffset(Math.max(0,offset-40))}>Anterior</button><button className="secondary" disabled={items.length<40} onClick={()=>setOffset(offset+40)}>Siguiente</button></div></section>;
}