"use client";
import {useCallback,useEffect,useMemo,useState} from "react";
import {requestTargetModule,type AdminRequestSeed} from "../../lib/admin-request-operations";
import {AdminSheet} from "./admin-sheet";
type Request={id:string;title:string;description:string;contextual_category:string;request_status:string;created_at:string};
const statuses:Record<string,string>={NEW:"Nueva",IN_REVIEW:"En revisión",APPROVED:"Aprobada",REJECTED:"Rechazada",RESOLVED:"Resuelta"};
const feedback:Record<string,string>={IN_REVIEW:"Solicitud en revisión",APPROVED:"Solicitud aprobada",REJECTED:"Solicitud rechazada",RESOLVED:"Solicitud resuelta"};
export function AdminRequests({token,onCreate}:{token:string;onCreate:(module:"courses"|"equipment"|"balls",request:AdminRequestSeed)=>void}){
 const [isolatedQa,setIsolatedQa]=useState(false),[loading,setLoading]=useState(true),[query,setQuery]=useState("");
 const [items,setItems]=useState<Request[]>([]),[offset,setOffset]=useState(0),[selected,setSelected]=useState<Request|null>(null),[status,setStatus]=useState("IN_REVIEW"),[reason,setReason]=useState(""),[error,setError]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{setLoading(true);try{const r=await fetch(`/api/admin/requests?offset=${offset}`,{headers:{authorization:`Bearer ${token}`},cache:"no-store"});const b=await r.json();if(!r.ok)throw new Error(b.error||"No pudimos cargar las solicitudes.");setItems(b.items);setIsolatedQa(b.isolatedQa===true);setError("");}finally{setLoading(false);}},[token,offset]);
 useEffect(()=>{void load().catch(e=>setError(e.message));},[load]);
 const visible=useMemo(()=>{const needle=query.trim().toLocaleLowerCase("es-MX");return items.filter(item=>(item.title+" "+item.description).toLocaleLowerCase("es-MX").includes(needle));},[items,query]);
 function review(item:Request,next:string){setSelected(item);setStatus(next);setReason("");setError("");}
 async function save(){if(!selected||busy)return;setBusy(true);setError("");try{const r=await fetch("/api/admin/requests",{method:"POST",headers:{authorization:`Bearer ${token}`,"content-type":"application/json"},body:JSON.stringify({id:selected.id,expectedStatus:selected.request_status,status,reason})});const b=await r.json();if(!r.ok)throw new Error(b.error||"No se cambió la solicitud. Intenta nuevamente.");setSelected(null);setMessage(feedback[status]);await load();}catch(e){setError(e instanceof Error?e.message:"No se cambió la solicitud.");}finally{setBusy(false);}}
 return <section className="adminV2Stack">{isolatedQa&&<p className="adminV2Hint">Entorno de revisión QA</p>}<label>Buscar<input type="search" placeholder="Buscar solicitudes…" value={query} maxLength={160} onChange={event=>setQuery(event.target.value)}/></label>{offset>0&&<p className="adminV2Hint">La búsqueda filtra esta página de solicitudes.</p>}
 {message&&<p role="status" className="adminV2Feedback">{message}</p>}{error&&<p className="notice bad" role="alert">{error}</p>}
 {loading&&<div className="adminV2Loading" role="status" aria-label="Cargando solicitudes"><div className="adminV2Skeleton"/></div>}
 {!loading&&!visible.length&&!error&&<p className="adminV2Empty">{query?"No hay solicitudes que coincidan con tu búsqueda.":"No hay solicitudes en esta página."}</p>}
 {!loading&&visible.map(item=>{const target=requestTargetModule(item.contextual_category);return <article className="card adminV2ListItem adminV2RequestRow" key={item.id}><div><h3>{item.title||"Solicitud de la comunidad"}</h3><p className="adminV2Clamp">{item.description}</p><small>{statuses[item.request_status]||"En revisión"} · {new Date(item.created_at).toLocaleDateString("es-MX")}</small></div><div className="adminV2Actions">
 {["NEW","IN_REVIEW"].includes(item.request_status)&&<button className="primary" disabled={busy} onClick={()=>review(item,"APPROVED")}>Aprobar</button>}
 {!["RESOLVED","REJECTED"].includes(item.request_status)&&<button className="secondary" disabled={busy} onClick={()=>review(item,"REJECTED")}>Rechazar</button>}
 {item.request_status==="APPROVED"&&(target?<button className="primary" onClick={()=>onCreate(target,item)}>Crear {target==="courses"?"campo":target==="balls"?"bola":"equipo"}</button>:<details><summary>Crear registro</summary>{(["courses","equipment","balls"] as const).map(module=><button className="secondary" key={module} onClick={()=>onCreate(module,item)}>Crear {module==="courses"?"campo":module==="balls"?"bola":"equipo"}</button>)}</details>)}
 {item.request_status==="NEW"&&<button className="secondary" disabled={busy} onClick={()=>review(item,"IN_REVIEW")}>En revisión</button>}
 {item.request_status==="APPROVED"&&<button className="secondary" disabled={busy} onClick={()=>review(item,"RESOLVED")}>Resolver</button>}
 </div></article>;})}
 <div className="adminV2Pagination"><button className="secondary" disabled={!offset||loading} onClick={()=>{setOffset(o=>Math.max(0,o-40));setQuery("");}}>Anterior</button><button className="secondary" disabled={items.length<40||loading} onClick={()=>{setOffset(o=>o+40);setQuery("");}}>Siguiente</button></div>
 {selected&&<AdminSheet title={status==="APPROVED"?"Aprobar solicitud":status==="REJECTED"?"Rechazar solicitud":status==="RESOLVED"?"Resolver solicitud":"Revisar solicitud"} onClose={()=>{if(!busy)setSelected(null);}}><form className="adminV2Stack" onSubmit={event=>{event.preventDefault();void save();}}><h3>{selected.title}</h3><p>{selected.description}</p><label>Motivo<textarea required minLength={3} maxLength={1000} value={reason} onChange={event=>setReason(event.target.value)}/></label><p className="adminV2Hint">La decisión quedará registrada.</p>{error&&<p role="alert" className="notice bad">{error}</p>}<div className="adminV2StickyActions"><button type="button" className="secondary" disabled={busy} onClick={()=>setSelected(null)}>Cancelar</button><button className="primary" disabled={busy||reason.trim().length<3}>{busy?"Guardando…":status==="APPROVED"?"Aprobar":status==="REJECTED"?"Rechazar":"Guardar"}</button></div></form></AdminSheet>}
 </section>;
}
