"use client";
import { useCallback,useEffect,useState } from "react";
import { VisualField } from "./admin-visual-catalog";
import type { AdminField } from "../../lib/admin-simple-catalog";
type Entry={id:string;name?:string;status:string;payload?:{title?:string;sourceName?:string;sourceUrl?:string;verifiedAt?:string;rules?:{title:string;body:string;active:boolean}[]}};
export function AdminCourseDetails({token,courseId}:{token:string;courseId:string}){
  const [kind,setKind]=useState("profiles"),[items,setItems]=useState<Record<string,Entry[]>>({}),[values,setValues]=useState<Record<string,unknown>>({}),[error,setError]=useState(""),[busy,setBusy]=useState(false),[confirmation,setConfirmation]=useState<Entry|null>(null),[hash,setHash]=useState(""),[reason,setReason]=useState("");
  const api=useCallback(async(body?:Record<string,unknown>)=>{const response=await fetch(body?(kind==="rules"&&body.operation!=="draft"?"/api/admin/simple":"/api/admin/course-details"):`/api/admin/course-details?courseId=${encodeURIComponent(courseId)}`,{method:body?"POST":"GET",cache:"no-store",headers:{authorization:`Bearer ${token}`,...(body?{"content-type":"application/json"}:{})},...(body?{body:JSON.stringify({...body,kind,courseId,...(kind==="rules"&&body.operation!=="draft"?{module:"courses",revisionId:body.id}:{})})}:{})});const result=await response.json();if(!response.ok)throw new Error(result.error);return result;},[token,courseId,kind]);
  const load=useCallback(async()=>setItems(await api()),[api]);useEffect(()=>{void load().catch(e=>setError(e.message));},[load]);
  async function action(body:Record<string,unknown>){setBusy(true);setError("");try{const result=await api(body);if(body.operation==="preview")setHash(result.preview.previewHash);else{setConfirmation(null);setValues({});await load();}}catch(e){setError(e instanceof Error?e.message:"No se guardó el cambio.");}finally{setBusy(false);}}
  const fields:AdminField[]=[{key:"name",label:kind==="rules"?"Título de la regla":"Nombre",required:true},{key:"sourceName",label:"Fuente verificada",required:true},{key:"sourceUrl",label:"Referencia",type:"url"},{key:"verifiedAt",label:"Fecha de verificación",type:"date"},...(kind==="rules"?[{key:"body",label:"Regla local",type:"textarea" as const,required:true}]:kind==="configurations"?[{key:"description",label:"Descripción del cambio",type:"textarea" as const},{key:"effectiveFrom",label:"Inicio",type:"datetime-local" as const,required:true},{key:"effectiveUntil",label:"Fin",type:"datetime-local" as const},{key:"temporaryGreen",label:"Greens temporales",type:"checkbox" as const},{key:"temporaryTee",label:"Tees temporales",type:"checkbox" as const}]:[])];
  return <section className="card adminV2Editor adminV2Stack"><h2>Tarjetas y operación del campo</h2><div className="adminV2Actions">{[["profiles","Tarjetas"],["configurations","Configuraciones"],["rules","Reglas locales"]].map(([id,title])=><button className="secondary" key={id} aria-pressed={kind===id} onClick={()=>{setKind(id);setConfirmation(null);}}>{title}</button>)}</div>{error&&<p className="notice bad" role="alert">{error}</p>}
    {(items[kind]||[]).map(item=><article className="card adminV2ListItem" key={item.id}><div><h3>{item.name||item.payload?.title}</h3><p>{item.status}</p></div>{!["ARCHIVED","SUPERSEDED"].includes(item.status)&&<button className="secondary" disabled={busy} onClick={()=>{setConfirmation(item);setReason("");setHash("");}}>Revisar</button>}</article>)}
    <form className="adminV2Stack" onSubmit={e=>{e.preventDefault();void action({operation:"draft",values});}}><h3>Agregar nueva versión</h3>{kind==="rules"&&<><label>Regla<select value={values.ruleIndex===undefined?"new":String(values.ruleIndex)} onChange={e=>{const payload=items.rules?.find(r=>r.status==="PUBLISHED")?.payload;const index=Number(e.target.value);const rule=payload?.rules?.[index];setValues(e.target.value==="new"?{active:true}: {...payload,expectedRuleRevision:items.rules?.find(r=>r.status==="PUBLISHED")?.id,ruleIndex:index,name:rule?.title,body:rule?.body,active:rule?.active,verifiedAt:payload?.verifiedAt?.slice(0,10)});}}><option value="new">+ Agregar regla</option>{items.rules?.find(r=>r.status==="PUBLISHED")?.payload?.rules?.map((r,i)=><option key={i} value={i}>{r.title}</option>)}</select></label><VisualField field={{key:"active",label:"Regla activa",type:"checkbox"}} value={values.active!==false} change={value=>setValues(v=>({...v,active:value}))}/></>}<p>{kind==="profiles"?"Usa los tees y hoyos actuales del campo. Edita sus datos en Información / Tees antes de crear una tarjeta nueva.":"Los históricos y las rondas anteriores se conservan."}</p><div className="adminV2FormGrid">{fields.map(field=><VisualField key={field.key} field={field} value={values[field.key]} change={value=>setValues(v=>({...v,[field.key]:value}))}/>)}</div><button className="primary" disabled={busy}>Guardar borrador</button></form>
    {confirmation&&<section className="adminV2Confirmation adminV2Stack"><h3>{confirmation.name}</h3><p>Estado actual: {confirmation.status}. La nueva publicación se aplicará a futuras rondas.</p><label>Motivo<input value={reason} onChange={e=>setReason(e.target.value)}/></label>{(kind==="configurations"||kind==="rules")&&<button className="secondary" disabled={busy||reason.length<3} onClick={()=>void action({operation:"preview",id:confirmation.id,reason})}>Preparar vista previa</button>}<div className="adminV2Actions"><button className="secondary" onClick={()=>setConfirmation(null)}>Cancelar</button>{kind==="profiles"&&<button className="secondary" disabled={busy||reason.length<3} onClick={()=>void action({operation:"archive",id:confirmation.id,confirmed:true,reason})}>Archivar tarjeta</button>}<button className="primary" disabled={busy||reason.length<3||(kind==="configurations"||kind==="rules")&&!hash} onClick={()=>void action({operation:"publish",id:confirmation.id,previewHash:hash,confirmed:true,reason})}>Confirmar y publicar</button></div></section>}
  </section>;
}
