"use client";
import {useCallback,useEffect,useState} from "react";
import {BET_REGISTRY} from "../../lib/bets/registry";
import {betVariantCapability,type BetVariant} from "../../lib/admin-bet-variants";
import type {HumanChange} from "../../lib/admin-simple-catalog";
import {VisualField} from "./admin-visual-catalog";
type Row={id:string;variant_id:string;version:number;payload:Omit<BetVariant,"id"|"version">};
export function AdminBetVariants({token}:{token:string}) {
 const [items,setItems]=useState<Row[]>([]),[drafts,setDrafts]=useState<Row[]>([]),[offset,setOffset]=useState(0),[total,setTotal]=useState(0),[editing,setEditing]=useState<Row|null>(null),[copyFromId,setCopyFromId]=useState("");
 const [values,setValues]=useState<Record<string,unknown>>({}),[error,setError]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[preview,setPreview]=useState<{id:string;previewHash:string;changes:HumanChange[]}|null>(null),[reason,setReason]=useState("");
 const api=useCallback(async(body?:Record<string,unknown>)=>{const response=await fetch(body?"/api/admin/bet-variants":"/api/admin/bet-variants?offset="+offset,{method:body?"POST":"GET",cache:"no-store",headers:{authorization:"Bearer "+token,...(body?{"content-type":"application/json"}:{})},...(body?{body:JSON.stringify(body)}:{})});const result=await response.json();if(!response.ok)throw new Error(result.error);return result;},[token,offset]);
 const load=useCallback(async()=>{const result=await api();setItems(result.items);setDrafts(result.drafts);setTotal(result.total||0);},[api]);useEffect(()=>{void load().catch(error=>setError(error.message));},[load]);
 function chooseEngine(engine:string){const capability=betVariantCapability(engine);if(!capability)return;setValues(current=>({...current,engine,config:capability.defaults,minPlayers:capability.minimum,maxPlayers:capability.maximum}));}
 function create(){setEditing({id:"",variant_id:"",version:0,payload:{} as Row["payload"]});setCopyFromId("");setValues({engine:"",title:"",description:"",active:true,order:0});setError("");setPreview(null);}
 async function action(body:Record<string,unknown>){if(busy)return;setBusy(true);setError("");try{const result=await api(body);if(body.operation==="preview"){setPreview({...result.preview,changes:result.changes});setReason("");}else{setEditing(null);setPreview(null);setMessage(body.operation==="draft"?"Borrador guardado":"Cambios guardados");await load();}}catch(error){setError(error instanceof Error?error.message:"No se guardó la variante.");}finally{setBusy(false);}}
 const capability=betVariantCapability(String(values.engine||""));
 return <section className="adminV2Stack">{error&&<p role="alert" className="notice bad">{error}</p>}{message&&<p role="status" className="adminV2Feedback">{message}</p>}
 {!editing&&<><button className="primary" onClick={create}>+ Nueva apuesta</button>{items.map(item=><article className="card adminV2ListItem" key={item.id}><div><h3>{item.payload.title}</h3><p>{betVariantCapability(item.payload.engine)?.label} · {item.payload.active?"Visible":"Inactiva"} · {item.payload.minPlayers}–{item.payload.maxPlayers} jugadores</p></div><button className="secondary" onClick={()=>{setEditing(item);setValues(item.payload);setCopyFromId("");setPreview(null);}}>Editar</button></article>)}{!items.length&&<p>No hay variantes publicadas. Crea una desde un motor existente.</p>}<div className="adminV2Actions"><button className="secondary" disabled={!offset} onClick={()=>setOffset(Math.max(0,offset-40))}>Anterior</button><span>{total} variantes</span><button className="secondary" disabled={offset+40>=total} onClick={()=>setOffset(offset+40)}>Siguiente</button></div></>}
 {editing&&<form className="card adminV2Editor adminV2Stack" onSubmit={event=>{event.preventDefault();void action({operation:"draft",id:editing.variant_id||null,version:editing.variant_id?editing.version:0,values,copyFromId});}}><h2>{editing.variant_id?"Editar variante":"Nueva apuesta"}</h2><label>Motor base<select required disabled={!!editing.variant_id||!!copyFromId} value={String(values.engine||"")} onChange={event=>chooseEngine(event.target.value)}><option value="">Selecciona un motor</option>{BET_REGISTRY.filter(engine=>betVariantCapability(engine.id)).map(item=>item.id).map(engine=><option key={engine} value={engine}>{betVariantCapability(engine)?.label}</option>)}</select></label><VisualField field={{key:"title",label:"Nombre",required:true}} value={values.title} change={title=>setValues(current=>({...current,title}))}/><VisualField field={{key:"description",label:"Descripción",type:"textarea"}} value={values.description} change={description=>setValues(current=>({...current,description}))}/>
 {capability&&<fieldset><legend>Configuración soportada</legend><div className="adminV2FormGrid">{capability.fields.map(field=><VisualField key={field.key} field={field} value={(values.config as Record<string,unknown>)?.[field.key]} change={value=>setValues(current=>({...current,config:{...(current.config as Record<string,unknown>),[field.key]:value}}))}/>)}{[["minPlayers","Jugadores mínimo"],["maxPlayers","Jugadores máximo"]].map(([key,label])=><VisualField key={key} field={{key,label,type:"number",min:capability.minimum,max:capability.maximum,required:true}} value={values[key]} change={value=>setValues(current=>({...current,[key]:value}))}/>)}</div></fieldset>}
 <VisualField field={{key:"active",label:"Visible / activa",type:"checkbox"}} value={values.active} change={active=>setValues(current=>({...current,active}))}/><VisualField field={{key:"order",label:"Orden",type:"number",min:0,max:1000}} value={values.order} change={order=>setValues(current=>({...current,order}))}/><p>Un nuevo cálculo matemático requiere desarrollo. Aquí sólo cambias la configuración que admite el motor.</p>
 {editing.variant_id&&<details><summary>Archivar variante</summary><label>Motivo<input value={reason} maxLength={1000} onChange={event=>setReason(event.target.value)}/></label><button type="button" className="secondary" disabled={busy||reason.trim().length<3} onClick={()=>{if(window.confirm("¿Archivar esta variante? Las rondas existentes se conservan."))void action({operation:"archive",revisionId:editing.id,reason});}}>Confirmar archivo</button></details>}
 {editing.variant_id&&<button type="button" className="secondary" onClick={()=>{setCopyFromId(editing.variant_id);setEditing({...editing,id:"",variant_id:"",version:0});setValues(current=>({...current,title:String(current.title)+" · copia"}));}}>Duplicar</button>}
 <div className="adminV2StickyActions"><button type="button" className="secondary" onClick={()=>setEditing(null)}>Cancelar</button><button className="primary" disabled={busy||!capability}>Guardar borrador</button></div></form>}
 {!!drafts.length&&<details><summary>Borradores ({drafts.length})</summary>{drafts.map(draft=><article className="card adminV2ListItem" key={draft.id}><h3>{draft.payload.title}</h3><button className="secondary" disabled={busy} onClick={()=>void action({operation:"preview",revisionId:draft.id})}>Vista previa</button></article>)}</details>}
 {preview&&<section className="card adminV2Confirmation adminV2Stack"><h3>Revisa antes de publicar</h3>{preview.changes.map((change,index)=><p key={index}><strong>{change.label}</strong><br/>{change.before} → {change.after}</p>)}<label>Motivo<input value={reason} maxLength={1000} onChange={event=>setReason(event.target.value)}/></label><div className="adminV2StickyActions"><button className="secondary" onClick={()=>setPreview(null)}>Cancelar</button><button className="primary" disabled={busy||reason.trim().length<3} onClick={()=>void action({operation:"publish",revisionId:preview.id,previewHash:preview.previewHash,reason})}>Confirmar y publicar</button></div></section>}
 </section>;
}
