"use client";
import {useCallback,useEffect,useState} from "react";
import {requestTargetModule,type AdminRequestSeed} from "../../lib/admin-request-operations";
type Request={id:string;title:string;description:string;contextual_category:string;request_status:string;created_at:string};
const statuses:Record<string,string>={NEW:"Nueva",IN_REVIEW:"En revisión",APPROVED:"Aprobada",REJECTED:"Rechazada",RESOLVED:"Resuelta"};
export function AdminRequests({token,onCreate}:{token:string;onCreate:(module:"courses"|"equipment"|"balls",request:AdminRequestSeed)=>void}){
  const [isolatedQa,setIsolatedQa]=useState(false);
  const [items,setItems]=useState<Request[]>([]),[offset,setOffset]=useState(0),[selected,setSelected]=useState<Request|null>(null),[status,setStatus]=useState("IN_REVIEW"),[reason,setReason]=useState(""),[error,setError]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
  const load=useCallback(async()=>{const r=await fetch(`/api/admin/requests?offset=${offset}`,{headers:{authorization:`Bearer ${token}`},cache:"no-store"});const b=await r.json();if(!r.ok)throw new Error(b.error);setItems(b.items);setIsolatedQa(b.isolatedQa===true);setError("");},[token,offset]);useEffect(()=>{void load().catch(e=>setError(e.message));},[load]);
  async function save(){if(!selected)return;setBusy(true);setError("");try{const r=await fetch("/api/admin/requests",{method:"POST",headers:{authorization:`Bearer ${token}`,"content-type":"application/json"},body:JSON.stringify({id:selected.id,expectedStatus:selected.request_status,status,reason})});const b=await r.json();if(!r.ok)throw new Error(b.error);setSelected(null);setMessage("Solicitud actualizada");await load();}catch(e){setError(e instanceof Error?e.message:"No se cambió la solicitud.");}finally{setBusy(false);}}
  return <section className="adminV2Stack">{isolatedQa&&<p className="notice">QA aislado · Estas solicitudes sólo pertenecen a este entorno de revisión. Los datos sintéticos y de test permanecen excluidos.</p>}{message&&<p role="status" className="adminV2Feedback">{message}</p>}{error&&<p className="notice bad" role="alert">{error}</p>}{!items.length&&!error&&<p className="notice">No hay solicitudes en esta página.</p>}{items.map(item=><article className="card adminV2ListItem" key={item.id}><div><h3>{item.title||"Solicitud de la comunidad"}</h3><p className="adminV2Clamp">{item.description}</p><small>{statuses[item.request_status]} · {new Date(item.created_at).toLocaleDateString("es-MX")}</small></div><div className="adminV2Actions">{!["RESOLVED","REJECTED"].includes(item.request_status)&&<button className="secondary" onClick={()=>{setSelected(item);setStatus("IN_REVIEW");setReason("");}}>Revisar</button>}{item.request_status==="APPROVED"&&<details><summary>Crear registro</summary>{(requestTargetModule(item.contextual_category)?[requestTargetModule(item.contextual_category)!]:["courses","equipment","balls"] as const).map(module=><button className="secondary" key={module} onClick={()=>onCreate(module,item)}>Crear {module==="courses"?"campo":module==="balls"?"bola":"equipo"}</button>)}</details>}</div></article>)}<div className="adminV2Actions"><button className="secondary" disabled={!offset} onClick={()=>setOffset(o=>Math.max(0,o-40))}>Anterior</button><button className="secondary" disabled={items.length<40} onClick={()=>setOffset(o=>o+40)}>Siguiente</button></div>{selected&&<section className="card adminV2Confirmation adminV2Stack"><h3>{selected.title}</h3><p>{selected.description}</p><div className="adminV2Actions"><button className="secondary" onClick={()=>setStatus("APPROVED")}>Aprobar</button><button className="secondary" onClick={()=>setStatus("REJECTED")}>Rechazar</button></div><label>Nuevo estado<select value={status} onChange={e=>setStatus(e.target.value)}>{Object.entries(statuses).filter(([id])=>id!=="NEW").map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><label>Motivo<input maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)}/></label><div className="adminV2Actions"><button className="secondary" onClick={()=>setSelected(null)}>Cancelar</button><button className="primary" disabled={busy||reason.trim().length<3} onClick={()=>void save()}>Guardar revisión</button></div></section>}</section>;
}
