"use client";
import {useCallback,useEffect,useState} from "react";
import {VisualField} from "./admin-visual-catalog";
import type {AdminField,HumanChange} from "../../lib/admin-simple-catalog";
type Item={id:string;version:number;values:Record<string,unknown>};
export function AdminPresentationEditor({token,module}:{token:string;module:"bets"|"content"}){
  const [items,setItems]=useState<Item[]>([]),[drafts,setDrafts]=useState<{id:string;values:Record<string,unknown>}[]>([]),[editing,setEditing]=useState<Item|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false),[preview,setPreview]=useState<{id:string;previewHash:string;changes:HumanChange[]}|null>(null),[reason,setReason]=useState("");
  const api=useCallback(async(body?:Record<string,unknown>)=>{const r=await fetch(body?"/api/admin/presentation":`/api/admin/presentation?module=${module}`,{method:body?"POST":"GET",headers:{authorization:`Bearer ${token}`,...(body?{"content-type":"application/json"}:{})},cache:"no-store",...(body?{body:JSON.stringify({...body,module})}:{})});const result=await r.json();if(!r.ok)throw new Error(result.error);return result;},[token,module]);
  const load=useCallback(async()=>{const data=await api();setItems(data.items);setDrafts(data.drafts);},[api]);useEffect(()=>{void load().catch(e=>setError(e.message));},[load]);
  async function action(body:Record<string,unknown>){setBusy(true);setError("");try{const data=await api(body);if(body.operation==="preview"){setPreview({...data.preview,changes:data.changes});setReason("");}else{setEditing(null);setPreview(null);await load();}}catch(e){setError(e instanceof Error?e.message:"No se guardó el cambio.");}finally{setBusy(false);}}
  const fields:AdminField[]=[{key:"title",label:"Nombre mostrado",required:true},{key:"active",label:"Visible / activo",type:"checkbox"},...(module==="bets"?[{key:"description",label:"Descripción",type:"textarea" as const},{key:"instructions",label:"Instrucciones",type:"textarea" as const},{key:"icon",label:"Icono"},{key:"order",label:"Orden",type:"number" as const,min:0,max:1000}]:[{key:"body",label:"Texto",type:"textarea" as const}])];
  return <section className="adminV2Stack">{error&&<p className="notice bad" role="alert">{error}</p>}{module==="bets"&&<p className="notice">Agregar un nuevo tipo de apuesta requiere desarrollo. Aquí puedes editar presentación y disponibilidad de los motores existentes.</p>}
    {!editing&&items.map(item=><article className="card adminV2ListItem" key={item.id}><div><h3>{String(item.values.title)}</h3><p>{String(item.values.description||item.values.body||"")}</p><small>{item.values.active?"Activo":"Inactivo"}</small></div><button className="secondary" onClick={()=>setEditing(item)}>Editar →</button></article>)}
    {editing&&<form className="card adminV2Editor adminV2Stack" onSubmit={e=>{e.preventDefault();void action({operation:"draft",id:editing.id,version:editing.version,values:editing.values});}}><h2>Editar {String(editing.values.title)}</h2><div className="adminV2FormGrid">{fields.map(field=><VisualField key={field.key} field={field} value={editing.values[field.key]} change={value=>setEditing({...editing,values:{...editing.values,[field.key]:value}})}/>)}</div><div className="adminV2Actions"><button className="secondary" type="button" onClick={()=>setEditing(null)}>Cancelar</button><button className="primary" disabled={busy}>Guardar borrador</button></div></form>}
    {!!drafts.length&&<h2>Borradores guardados</h2>}{drafts.map(d=><article className="card adminV2ListItem" key={d.id}><h3>{String(d.values.title)}</h3><button className="secondary" disabled={busy} onClick={()=>void action({operation:"preview",id:d.id})}>Vista previa</button></article>)}
    {preview&&<section className="card adminV2Confirmation adminV2Stack"><h2>Revisa los cambios</h2>{preview.changes.map((c,i)=><p key={i}><strong>{c.label}</strong><br/>{c.before} → {c.after}</p>)}<label>Motivo<input value={reason} maxLength={1000} onChange={e=>setReason(e.target.value)}/></label><div className="adminV2Actions"><button className="secondary" onClick={()=>setPreview(null)}>Cancelar</button><button className="primary" disabled={busy||reason.length<3} onClick={()=>void action({operation:"publish",id:preview.id,previewHash:preview.previewHash,confirmed:true,reason})}>Confirmar y publicar</button></div></section>}
  </section>;
}
