"use client";
import {useState} from "react";
import {VisualField} from "./admin-visual-catalog";
import {AdminSheet} from "./admin-sheet";
import {scorecardYards,scorecardHolePatch,type HoleEditorValues} from "../../lib/admin-scorecard-ui";
import type {AdminField} from "../../lib/admin-simple-catalog";
export function AdminCourseGolfEditor({values,patch}:{values:Record<string,unknown>;patch:(key:string,value:unknown)=>void}){
 const [teeIndex,setTeeIndex]=useState<number|null>(null),[teeDraft,setTeeDraft]=useState<Record<string,unknown>>({});
 const [holeIndex,setHoleIndex]=useState<number|null>(null),[holeDraft,setHoleDraft]=useState<HoleEditorValues>({par:"",hcp:"",yards:[]});
 const tees=(Array.isArray(values.tees)?values.tees:[]) as Record<string,unknown>[],holes=(Array.isArray(values.holes)?values.holes:[]) as Record<string,unknown>[];
 const teeFields:AdminField[]=[{key:"name",label:"Nombre",required:true},{key:"color",label:"Color"},{key:"category",label:"Categoría"},{key:"rating",label:"Rating",type:"number",min:40,max:100},{key:"slope",label:"Slope",type:"number",min:55,max:155},{key:"par",label:"Par",type:"number",min:27,max:120},{key:"totalYards",label:"Yardas",type:"number",min:100,max:15000},{key:"active",label:"Activo",type:"checkbox"}];
 function editTee(index:number){setTeeIndex(index);setTeeDraft({... (tees[index]||{name:"",active:true})});}
 function editHole(index:number){setHoleIndex(index);setHoleDraft({par:String(holes[index].par??""),hcp:String(holes[index].strokeIndex??""),yards:tees.map((_,t)=>String(scorecardYards(values,t,index)))});}
 function updateYards(t:number,h:number,yards:string){const changes=(values.yardages||[]) as Record<string,unknown>[];patch("yardages",[...changes.filter(row=>row.teeIndex!==t||row.holeIndex!==h),{teeIndex:t,holeIndex:h,yards}]);}
 return <>
 <fieldset><legend>Tees</legend>{tees.map((tee,index)=><div className="adminV2TeeRow" key={String(tee.id||index)}><div><strong>{String(tee.name||"Tee nuevo")}</strong><br/><small>{String(tee.rating??"—")} / {String(tee.slope??"—")} · {tee.active===false?"Inactivo":"Activo"}</small></div><button type="button" className="secondary" aria-label={"Editar tee "+String(tee.name||index+1)} onClick={()=>editTee(index)}>Editar</button></div>)}<button type="button" className="secondary" onClick={()=>editTee(tees.length)}>+ Agregar tee</button></fieldset>
 <fieldset><legend>Tarjeta actual</legend>{!holes.length?<><p className="adminV2Hint">Completa la información verificada de cada hoyo.</p><button type="button" className="secondary" onClick={()=>patch("holes",Array.from({length:Number(values.holeCount)||18},(_,index)=>({holeNumber:index+1,par:"",strokeIndex:""})))}>Completar tarjeta</button></>:<>
 <div className="adminV2MobileOnly"><p className="adminV2Hint">Toca un hoyo para editar par, HCP y yardas.</p><div className="adminV2HoleList">{holes.map((hole,index)=><button type="button" className="adminV2HoleRow" key={String(hole.id||index)} onClick={()=>editHole(index)} aria-label={"Editar hoyo "+String(hole.holeNumber||index+1)}><strong>Hoyo {String(hole.holeNumber||index+1)}</strong><span>Par {String(hole.par||"—")} · HCP {String(hole.strokeIndex||"—")}</span><span aria-hidden="true">›</span></button>)}</div></div>
 <div className="adminV2Scorecard adminV2DesktopOnly" role="region" aria-label="Editar tarjeta por hoyo" tabIndex={0}><table><thead><tr><th scope="col">Hoyo</th><th scope="col">Par</th><th scope="col">HCP</th>{tees.map((tee,index)=><th scope="col" key={index}>{String(tee.name||"Tee nuevo")} · yd</th>)}</tr></thead><tbody>{holes.map((hole,index)=><tr key={String(hole.id||index)}><th scope="row">{String(hole.holeNumber||index+1)}</th>{["par","strokeIndex"].map(key=><td key={key}><input aria-label={`${key==="par"?"Par":"HCP"} hoyo ${index+1}`} type="number" inputMode="numeric" min={key==="par"?3:1} max={key==="par"?6:Number(values.holeCount)} value={String(hole[key]??"")} onChange={event=>patch("holes",holes.map((row,i)=>i===index?{...row,[key]:event.target.value}:row))}/></td>)}{tees.map((tee,t)=><td key={t}><input type="number" inputMode="numeric" min={1} max={1000} aria-label={`Yardas ${String(tee.name)} hoyo ${index+1}`} value={String(scorecardYards(values,t,index))} onChange={event=>updateYards(t,index,event.target.value)}/></td>)}</tr>)}</tbody></table></div></>}</fieldset>
 {teeIndex!==null&&<AdminSheet title={teeIndex===tees.length?"Agregar tee":"Editar tee"} onClose={()=>setTeeIndex(null)}><form className="adminV2Stack" onSubmit={event=>{event.preventDefault();patch("tees",teeIndex===tees.length?[...tees,teeDraft]:tees.map((tee,index)=>index===teeIndex?teeDraft:tee));setTeeIndex(null);}}><div className="adminV2FormGrid">{teeFields.map(field=><VisualField key={field.key} field={field} value={teeDraft[field.key]} change={value=>setTeeDraft(current=>({...current,[field.key]:value}))}/>)}</div><p className="adminV2Hint">Después, guarda los cambios del campo.</p><div className="adminV2StickyActions"><button className="secondary" type="button" onClick={()=>setTeeIndex(null)}>Cancelar</button><button className="primary">Guardar tee</button></div></form></AdminSheet>}
 {holeIndex!==null&&<AdminSheet title={"Hoyo "+String(holes[holeIndex]?.holeNumber||holeIndex+1)} onClose={()=>setHoleIndex(null)}><form className="adminV2Stack" onSubmit={event=>{event.preventDefault();const result=scorecardHolePatch(values,holeIndex,holeDraft);patch("holes",result.holes);patch("yardages",result.yardages);setHoleIndex(null);}}><div className="adminV2FormGrid"><label>Par<select required value={holeDraft.par} onChange={event=>setHoleDraft(current=>({...current,par:event.target.value}))}><option value="">Selecciona</option>{[3,4,5,6].map(par=><option key={par}>{par}</option>)}</select></label><label>HCP<input required type="number" inputMode="numeric" min={1} max={Number(values.holeCount)||18} value={holeDraft.hcp} onChange={event=>setHoleDraft(current=>({...current,hcp:event.target.value}))}/></label>{tees.map((tee,t)=><label key={String(tee.id||t)}>{String(tee.name||"Tee nuevo")} · yardas<input type="number" inputMode="numeric" min={1} max={1000} value={holeDraft.yards[t]||""} onChange={event=>setHoleDraft(current=>({...current,yards:current.yards.map((yards,i)=>i===t?event.target.value:yards)}))}/></label>)}</div><p className="adminV2Hint">Después, guarda los cambios del campo.</p><div className="adminV2StickyActions"><button type="button" className="secondary" onClick={()=>setHoleIndex(null)}>Cancelar</button><button className="primary">Guardar hoyo</button></div></form></AdminSheet>}
 </>;
}
