"use client";
import { useMemo,useState } from "react";
import { careerTournamentSummary,nextCareerTournament,type CareerTournament } from "../../lib/career-tournaments";
import { careerDate,careerNumber,scoreToPar } from "../../lib/career-statistics";
import type { CareerHubProps } from "./career-hub";
import { useCareerTournaments } from "./use-career-tournaments";
import { CareerPanel,CareerStatCard,CareerEmptyState,CareerCta,CareerSkeleton,CareerErrorState } from "./career-shared";
import { recordCareerEvent } from "../../features/analytics/career";
import { POLLA_LIVE_RELEASED } from "../../lib/feature-flags";
import styles from "./career-hub.module.css";
export const tournamentFormat=(format:CareerTournament["format"])=>`Stroke Play · ${format==="gross"?"bruto":format==="net"?"neto":"bruto y neto"}`;
export function TournamentHero({event,days,onOpen}:{event:CareerTournament;days:number;onOpen:(id:string)=>void}) {
  return <section className={styles.tournamentHero}><span className={styles.eyebrow}>PRÓXIMO TORNEO</span><h2>{event.name}</h2><p>{careerDate(event.date)} · {event.courseName}</p><p>{tournamentFormat(event.format)} · {event.holes} hoyos · Próximo</p><div className={styles.tournamentHeroFooter}><strong>{days===0?"Hoy":`${days} días`}</strong><button type="button" className={styles.goldButton} onClick={()=>onOpen(event.id)}>Ver detalles ›</button></div></section>;
}
export function TournamentRow({event:e,onOpen}:{event:CareerTournament;onOpen:(id:string)=>void}) {
  return <button type="button" className={styles.roundRow} onClick={()=>onOpen(e.id)} aria-label={`Ver torneo ${e.name}`}><span className={styles.rowMain}><strong>{e.name}</strong><small>{careerDate(e.date)} · {e.courseName}</small><small>{tournamentFormat(e.format)} · {e.status==="finished"?"Finalizado":e.status==="live"?"En juego":"Próximo"}</small></span><span className={styles.rowScore}><strong>{e.position===null?"—":`${e.position}º`}</strong><small>{e.gross===null?"Sin resultado":`${e.gross} golpes`}</small></span><span aria-hidden="true">›</span></button>;
}
export function TournamentRanking({ranking}:{ranking?:{position:number;players:number;points:number;change?:number}|null}) {
  return <CareerPanel title="Carrera en el ranking">{ranking?<div className={styles.metrics}><CareerStatCard label="Posición" value={`${ranking.position}º`} hint={`De ${ranking.players} jugadores`}/><CareerStatCard label="Puntos" value={careerNumber(ranking.points)}/>{ranking.change!==undefined&&<CareerStatCard label="Cambio de posición" value={ranking.change}/>}</div>:<p className={styles.caption}>La clasificación por temporada aparecerá cuando exista un sistema de puntos y ranking oficial en The Backyard.</p>}</CareerPanel>;
}
type ContentProps={events:CareerTournament[];loading:boolean;error:boolean;readPending?:boolean;authenticated:boolean;nextOffset:number|null;reload:()=>void;loadMore:()=>void;onExplore?:()=>void;today?:string;onOpened?:()=>void};
export function CareerTournamentsContent(props:ContentProps) {
  const [year,setYear]=useState("all"),[format,setFormat]=useState("all"),[course,setCourse]=useState("all"),[selected,setSelected]=useState<string|null>(null);
  const events=useMemo(()=>props.events.filter(e=>(year==="all"||e.date.startsWith(year))&&(format==="all"||e.format===format)&&(course==="all"||e.courseName===course)),[props.events,year,format,course]);
  const summary=useMemo(()=>careerTournamentSummary(events),[events]);
  const today=props.today??new Date().toLocaleDateString("sv-SE",{timeZone:"America/Mexico_City"}),next=nextCareerTournament(events,today),detail=events.find(e=>e.id===selected);
  const open=(id:string)=>{setSelected(id);props.onOpened?.();};
  if(props.loading&&!props.events.length)return <CareerSkeleton/>;
  if(props.readPending&&!props.events.length)return <CareerEmptyState title="Tu historia competitiva, en un solo lugar." description="La consulta de torneos aún no está habilitada. Tus resultados aparecerán cuando esté disponible." action="Reintentar" onAction={props.reload}/>;
  if(props.error&&!props.events.length)return <CareerErrorState onRetry={props.reload}/>;
  if(!props.authenticated)return <CareerEmptyState title="Todavía no tienes torneos registrados." description="Inicia sesión para consultar participaciones vinculadas a tu cuenta." action={props.onExplore?"Vive más torneos":undefined} onAction={props.onExplore}/>;
  return <>{props.error&&<CareerErrorState onRetry={props.reload}/>}<div className={styles.filters}><label>Temporada<select value={year} onChange={e=>{setYear(e.target.value);setSelected(null);}}><option value="all">Todas las temporadas</option>{[...new Set(props.events.map(e=>e.date.slice(0,4)))].sort().reverse().map(y=><option key={y} value={y}>{y}</option>)}</select></label><label>Modalidad<select value={format} onChange={e=>{setFormat(e.target.value);setSelected(null);}}><option value="all">Todas las modalidades</option><option value="gross">Stroke Play · bruto</option><option value="net">Stroke Play · neto</option><option value="both">Bruto y neto</option></select></label><label>Sede<select value={course} onChange={e=>{setCourse(e.target.value);setSelected(null);}}><option value="all">Todas las sedes</option>{[...new Set(props.events.map(e=>e.courseName))].sort().map(c=><option key={c} value={c}>{c}</option>)}</select></label></div>
    {!events.length&&!props.error&&<CareerEmptyState title="Todavía no tienes torneos registrados." description={props.authenticated?"Aquí aparecen competiciones con una participación vinculada a tu cuenta. Organizar un torneo no significa haberlo jugado.":"Inicia sesión para consultar participaciones vinculadas a tu cuenta."} action={props.onExplore?"Vive más torneos":undefined} onAction={props.onExplore}/>}
    <CareerPanel title="Resumen de torneos"><div className={styles.metrics}><CareerStatCard label="Torneos jugados" value={summary.played}/><CareerStatCard label="Podios" value={summary.ranked?summary.podiums:undefined}/><CareerStatCard label="Victorias" value={summary.ranked?summary.victories:undefined}/><CareerStatCard label="Mejor posición" value={summary.bestPosition?`${summary.bestPosition}º`:undefined}/>{summary.points!==undefined&&<CareerStatCard label="Puntos" value={summary.points}/>}</div><p className={styles.caption}>{props.events.length} participaciones cargadas{props.nextOffset!==null?" · carga más para ampliar el resumen":""}. Posiciones sólo con resultados completos; bruto si esa es la modalidad, neto en modalidades neto o ambos.</p></CareerPanel>
    {next&&<TournamentHero event={next.event} days={next.days} onOpen={open}/>}
    {detail&&<CareerPanel title={detail.name} action="Cerrar detalles" onAction={()=>setSelected(null)}><p className={styles.caption}>{careerDate(detail.date)} · {detail.courseName} · {detail.holes} hoyos</p><div className={styles.metrics}><CareerStatCard label="Score bruto" value={detail.gross}/><CareerStatCard label="Score neto" value={detail.net}/><CareerStatCard label="Resultado vs. par" value={scoreToPar(detail.relativeToPar??undefined)}/><CareerStatCard label="Posición" value={detail.position===null?undefined:`${detail.position}º`} hint={`${detail.players} participantes`}/></div><p className={styles.caption}>{detail.resultStatus==="final"?"Tarjeta completa en un torneo finalizado.":detail.resultStatus==="partial"?"Tarjeta en progreso. La posición final aún no está disponible.":"Participación vinculada; aún no hay resultados completos."}</p>{detail.publicLeaderboard&&POLLA_LIVE_RELEASED&&<a className={styles.goldButton} href={`/polla/${encodeURIComponent(detail.code)}`}>Ver tablero publicado ›</a>}</CareerPanel>}
    <CareerPanel title="Historial competitivo">{events.filter(e=>e.status!=="upcoming").map(e=><TournamentRow key={e.id} event={e} onOpen={open}/>)}{!events.some(e=>e.status!=="upcoming")&&<p className={styles.caption}>Tus resultados aparecerán conforme participes.</p>}{props.nextOffset!==null&&<button type="button" disabled={props.loading} className={styles.goldButton} onClick={props.loadMore}>{props.loading?"Cargando…":"Cargar más participaciones"}</button>}</CareerPanel>
    <TournamentRanking/>{events.length>0&&<CareerPanel title="Logros en torneos"><div className={styles.metrics}><CareerStatCard label="Victorias" value={summary.ranked?summary.victories:undefined}/><CareerStatCard label="Podios" value={summary.ranked?summary.podiums:undefined}/><CareerStatCard label="Top 10" value={summary.ranked?summary.top10:undefined}/><CareerStatCard label="Torneos jugados" value={summary.played}/></div></CareerPanel>}
    {props.onExplore&&<CareerCta title="Más torneos. Mejores historias." label="Vive más torneos" onAction={props.onExplore}/>}</>;
}
export function CareerTournaments(props:CareerHubProps) {
  const data=useCareerTournaments(props.userId,props.accessToken);
  return <CareerTournamentsContent {...data} onExplore={props.onExploreTournaments} onOpened={()=>recordCareerEvent("tournament_opened","tournaments",props.accessToken)}/>;
}
