"use client";
import { useMemo, useState } from "react";
import { deriveCareerRivalries, rivalryTotals, type CareerRivalry } from "../../lib/career-rivalries";
import { buildGolfInsights } from "../../lib/golf-insights";
import { careerDate, careerNumber, ownCareerHistory } from "../../lib/career-statistics";
import type { CareerHubProps } from "./career-hub";
import { CareerPanel, CareerEmptyState, CareerCta, CareerStatCard } from "./career-shared";
import { ProfileAvatarMedia } from "./profile-avatar-media";
import styles from "./career-hub.module.css";
export const streakLabel = (row: CareerRivalry) => `${row.currentStreak.count} ${row.currentStreak.result === "win" ? "victorias" : row.currentStreak.result === "loss" ? "derrotas" : "empates"}`;
export function RivalryRow({ rivalry:r, onOpen }: { rivalry:CareerRivalry;onOpen:(id:string)=>void }) {
  return <button type="button" className={styles.roundRow} onClick={()=>onOpen(r.playerB)} aria-label={`Ver rivalidad con ${r.name}`}><ProfileAvatarMedia fallback={r.name.slice(0,1)} className={styles.smallAvatar}/><span className={styles.rowMain}><strong>{r.name}</strong><small>{r.matchesPlayed} enfrentamientos · {r.wins}-{r.losses}-{r.ties} G-P-E</small></span><span className={styles.rowScore}><strong>{careerNumber(r.winRate)}%</strong><small>victorias</small></span><span aria-hidden="true">›</span></button>;
}
export function RivalryHero({ rivalry:r,displayName,avatarUrl,onOpen }: {rivalry:CareerRivalry;displayName:string;avatarUrl?:string|null;onOpen:(id:string)=>void}) {
  return <section className={styles.rivalryHero}><span className={styles.eyebrow}>RIVALIDAD DESTACADA</span><div className={styles.versus}><div><ProfileAvatarMedia value={avatarUrl} fallback={displayName.slice(0,1)} className={styles.avatar}/><h3>{displayName}</h3></div><b>VS</b><div><ProfileAvatarMedia fallback={r.name.slice(0,1)} className={styles.avatar}/><h3>{r.name}</h3></div></div><div className={styles.heroStats}><div><strong>{r.wins}-{r.losses}-{r.ties}</strong><small>G-P-E</small></div><div><strong>{r.matchesPlayed}</strong><small>Enfrentamientos</small></div><div><strong>{careerNumber(r.winRate)}%</strong><small>Victorias</small></div></div><p>Una gran rivalidad · {streakLabel(r)} en la racha actual.</p><small>Última partida: {careerDate(r.lastMatch)}</small><button type="button" className={styles.goldButton} onClick={()=>onOpen(r.playerB)}>Ver historial completo ›</button></section>;
}
export function CareerRivalries(props:CareerHubProps) {
  const [year,setYear]=useState("all"),[rival,setRival]=useState("all"),[holes,setHoles]=useState("all"),[selected,setSelected]=useState<string|null>(null);
  const eligible=useMemo(()=>props.rounds.filter(r=>(year==="all"||r.date.startsWith(year))&&(holes==="all"||r.roundHoles===Number(holes))),[props.rounds,year,holes]);
  const all=useMemo(()=>deriveCareerRivalries(eligible,props.userId),[eligible,props.userId]);
  const rows=useMemo(()=>all.filter(r=>rival==="all"||r.playerB===rival),[all,rival]);
  const total=useMemo(()=>rivalryTotals(rows),[rows]);
  const personal=useMemo(()=>buildGolfInsights(ownCareerHistory(eligible,props.userId)),[eligible,props.userId]);
  const detail=rows.find(r=>r.playerB===selected),featured=detail??rows[0];
  const open=(id:string)=>setSelected(id);
  const oldest=[...rows].sort((a,b)=>a.firstMatch.localeCompare(b.firstMatch))[0],best=[...rows].sort((a,b)=>b.bestWinStreak-a.bestWinStreak)[0];
  return <><div className={styles.filters}><label>Periodo<select value={year} onChange={e=>{setYear(e.target.value);setSelected(null);setRival("all");}}><option value="all">Todo el historial</option>{[...new Set(props.rounds.map(r=>r.date.slice(0,4)))].sort().reverse().map(y=><option key={y} value={y}>{y}</option>)}</select></label><label>Rival<select value={rival} onChange={e=>{setRival(e.target.value);setSelected(null);}}><option value="all">Todos los rivales</option>{all.map(r=><option key={r.playerB} value={r.playerB}>{r.name}</option>)}</select></label><label>Formato<select value={holes} onChange={e=>{setHoles(e.target.value);setSelected(null);setRival("all");}}><option value="all">Stroke Play · todos</option><option value="18">Stroke Play · 18 hoyos</option><option value="9">Stroke Play · 9 hoyos</option></select></label></div>
    <div className={styles.metrics}><CareerStatCard label="Enfrentamientos" value={total.matches}/><CareerStatCard label="Victorias" value={total.winRate===undefined?undefined:`${careerNumber(total.winRate)}%`} hint="Score bruto · empates incluidos"/>{personal.betBalance!==undefined&&<CareerStatCard label="Balance personal" value={personal.betBalance.toLocaleString("es-MX",{style:"currency",currency:"MXN",maximumFractionDigits:0})} hint="Tu resultado consolidado del periodo"/>}</div>
    <p className={styles.caption}>Resultados deportivos en score bruto, con tarjetas completas y mismo par. Invitados sin identidad estable se conservan por ronda. Los filtros de rival afectan al cara a cara; el balance corresponde al periodo completo.</p>
    {featured?<RivalryHero rivalry={featured} displayName={props.displayName} avatarUrl={props.avatarUrl} onOpen={open}/>:<CareerEmptyState title="Juega con amigos para empezar a construir tus rivalidades." action="Encuentra un rival" onAction={props.onFindRival}/>}
    {detail&&<CareerPanel title={`Historial cara a cara · ${detail.name}`} action="Cerrar historial" onAction={()=>setSelected(null)}>{detail.matches.map(m=><button key={m.roundId} type="button" className={styles.roundRow} onClick={()=>props.onOpenRound(m.roundId)}><span className={styles.rowMain}><strong>{m.courseName}</strong><small>{careerDate(m.date)} · {m.holes} hoyos · {m.result==="win"?"Victoria":m.result==="loss"?"Derrota":"Empate"}</small></span><span className={styles.rowScore}><strong>{m.ownScore} / {m.rivalScore}</strong><small>Score bruto</small></span><span aria-hidden="true">›</span></button>)}</CareerPanel>}
    {rows.length>0&&<><CareerPanel title="Top rivales"><p className={styles.caption}>Ordenados por más enfrentamientos.</p>{rows.slice(0,10).map(r=><RivalryRow key={r.playerB} rivalry={r} onOpen={open}/>)}</CareerPanel><CareerPanel title="Rachas actuales">{rows.slice(0,5).map(r=><button key={r.playerB} type="button" className={styles.roundRow} onClick={()=>open(r.playerB)}><span className={styles.rowMain}><strong>{r.name}</strong><small>{streakLabel(r)} · mejor racha: {r.bestWinStreak} victorias</small><small>{careerDate(r.lastMatch)}</small></span><span aria-hidden="true">›</span></button>)}</CareerPanel><CareerPanel title="Hitos de rivalidad"><div className={styles.milestoneRows}><p><span>Rival más frecuente</span><strong>{rows[0].name} · {rows[0].matchesPlayed} encuentros</strong></p><p><span>Mayor racha de victorias</span><strong>{best?.name} · {best?.bestWinStreak}</strong></p><p><span>Rivalidad más antigua</span><strong>{oldest?.name} · {oldest&&careerDate(oldest.firstMatch)}</strong></p></div></CareerPanel></>}
    <CareerCta title="El golf sabe mejor con rivales." label="Encuentra un rival" onAction={props.onFindRival}/></>;
}
