"use client";
import { useEffect, useMemo, useState } from "react";
import type { CareerHubProps } from "./career-hub";
import { backyardIndexTimeline, type CareerAttestSummary } from "../../lib/career-index-presentation";
import { careerDate,careerNumber } from "../../lib/career-statistics";
import { readCareerAttestSummary } from "../../lib/career-attest-client";
import { calculateBackyardIndex } from "../../lib/backyard-index";
import { CareerGhinScores } from "./career-ghin-scores";
import { ProfileAvatarMedia } from "./profile-avatar-media";
import styles from "./career-index-panel.module.css";
export type { CareerDetail as CareerIndexDetail } from "../../lib/career-navigation";
import type { CareerDetail as CareerIndexDetail } from "../../lib/career-navigation";
export function CareerIndexPanel({props,detail,onDetail}:{props:CareerHubProps;detail:CareerIndexDetail;onDetail:(view:CareerIndexDetail)=>void}) {
  const [attest,setAttest]=useState<CareerAttestSummary|null>(null),[error,setError]=useState(false),[retry,setRetry]=useState(0),[info,setInfo]=useState(false);
  useEffect(()=>{const controller=new AbortController();setAttest(null);setError(false);if(props.accessToken)void readCareerAttestSummary(props.accessToken,controller.signal).then(data=>{if(!controller.signal.aborted)setAttest(data);}).catch(()=>{if(!controller.signal.aborted)setError(true);});return()=>controller.abort();},[props.userId,props.accessToken,retry]);
  const timeline=useMemo(()=>props.index.source==="BACKYARD"?backyardIndexTimeline(props.history??props.rounds,props.userId):{points:[],low:null,average:null,high:null},[props.history,props.rounds,props.userId,props.index.source]);
  const internal=useMemo(()=>calculateBackyardIndex(props.history??props.rounds,props.userId),[props.history,props.rounds,props.userId]);
  const retained=props.index.source==="GHIN"&&internal.value!==null?<p>Backyard Index conservado: <b>{careerNumber(internal.value,1)}</b> · Calculado sólo con tus tarjetas Backyard elegibles.</p>:null;
  const label=props.index.source==="BACKYARD"?"Backyard Index":"Índice HCP",source=props.index.source==="BACKYARD"?"Índice local calculado":props.index.source==="GHIN"?"Fuente GHIN verificada":"Índice no disponible";
  const dots=<div className={styles.dots} aria-label={attest?`${attest.count} de 20 tarjetas atestadas`:"20 espacios para tus tarjetas"}>{Array.from({length:20},(_,i)=><i key={i} className={attest?.slots[i]?styles.valid:undefined}/>)}</div>;
  const summary=<section className={styles.attest}><div className={styles.attestTop}><button className={styles.attestLink} type="button" onClick={()=>onDetail("attest")}><span className={styles.shield} aria-hidden="true">✓</span><span><b>Atest de tarjetas Backyard <strong>{attest?`${attest.percent}%`:"—"}</strong></b><small>Tus últimas 20 tarjetas · {attest?attest.cards.length ? `${attest.count}/20 atestadas` : "Sin tarjetas Backyard elegibles · 0/20 atestadas":error?"No pudimos consultar el Atest Backyard":"Consultando tarjetas…"}</small></span></button><button type="button" aria-label="Información sobre Atest" aria-expanded={info} className={styles.info} onClick={()=>setInfo(v=>!v)}>i</button></div>{dots}<small>Cada tarjeta atestada suma 5%.</small>{info&&<p>El Atest de tarjetas refleja cuántas de tus últimas 20 tarjetas han sido confirmadas por compañeros. Cada tarjeta atestada suma 5%. No es una certificación oficial GHIN/WHS.</p>}{error&&<button type="button" onClick={()=>setRetry(v=>v+1)}>Reintentar</button>}</section>;
  const ghinCards=<CareerGhinScores control={props.ghin} userId={props.userId} expanded={detail==="attest"} onOpen={()=>onDetail("attest")} onReauthorize={props.onOpenProfile}/>;
  if(!detail)return <div className={styles.summary}><button type="button" className={styles.indexLink} onClick={()=>onDetail("index")}><span><small>{label}</small><strong>{careerNumber(props.index.value,1)}</strong><small>{source}</small></span><span aria-hidden="true">›</span></button>{retained}{summary}{ghinCards}</div>;
  const points=timeline.points,values=points.map(p=>p.value),min=Math.min(0,...values),max=Math.max(10,...values),width=300,height=140;
  const position=(value:number,i:number)=>`${20+(i/(Math.max(1,points.length-1)))*(width-40)},${height-20-(value-min)/(max-min)*(height-40)}`;
  return <section className={styles.detail} aria-label={detail==="index"?label:"Tus últimas 20 tarjetas"}><header><button type="button" onClick={()=>onDetail(null)} aria-label="Volver a Carrera">‹</button><h2>{detail==="index"?label:"Tus últimas 20 tarjetas"}</h2></header>
    {detail==="index"?<><div className={styles.player}><ProfileAvatarMedia className={styles.avatar} value={props.avatarUrl} fallback={props.displayName[0]||"G"}/><div><h3>{props.displayName}</h3>{props.city&&<p>{props.city}</p>}<small>{source}</small></div></div><section className={styles.indexHero}><h3>Índice actual</h3><strong className={styles.value}>{careerNumber(props.index.value,1)}</strong><p>{source}</p>{points.length>=2?<><svg className={styles.chart} viewBox={`0 0 ${width} ${height}`} role="img" aria-label={`Evolución del índice local: ${points.map(p=>`${p.date}: ${p.value}`).join(", ")}`}><path d={`M${points.map((p,i)=>position(p.value,i)).join(" L")}`} fill="none" stroke="#e9ca74" strokeWidth="2"/>{points.map((p,i)=><circle key={p.date} cx={position(p.value,i).split(",")[0]} cy={position(p.value,i).split(",")[1]} r="3" fill="#e9ca74"/>)}</svg><div className={styles.chartDates}><small>{careerDate(points[0].date)}</small><small>{careerDate(points.at(-1)!.date)}</small></div><p className={styles.explanation}>Evolución calculada con la evidencia guardada de cada tarjeta.</p><div className={styles.extremes}>{([["HCP más bajo",timeline.low],["Promedio histórico",timeline.average],["HCP más alto",timeline.high]] as const).map(([title,value])=><div key={title}><strong>{careerNumber(value,1)}</strong><small>{title}</small></div>)}</div></>:<p>Aún no tenemos suficiente historial para mostrar tu evolución.</p>}</section>{retained}{summary}</>:<><section className={styles.lastSummary}><button type="button" className={styles.indexLink} onClick={()=>onDetail("index")}><span><small>{label}</small><strong>{careerNumber(props.index.value,1)}</strong></span><span aria-hidden="true">›</span></button>{summary}</section><section className={styles.history}><h3>Historial reciente</h3>{attest?.cards.map((card,i)=><button type="button" className={styles.row} key={card.roundId} onClick={()=>props.onOpenRound(card.roundId)}><small>{i+1}</small><span><small>{careerDate(card.date)}</small><b>{card.courseName}</b></span><strong>{card.score}</strong><small className={card.attested?styles.attested:styles.pending}>{card.attested?"✓ Atestada":"◷ Pendiente"}</small></button>)}{attest&&!attest.cards.length&&<p>Tus tarjetas aparecerán conforme juegues. Los espacios vacíos siguen formando parte de las 20 tarjetas.</p>}{!attest&&!error&&<p role="status">Consultando tus tarjetas…</p>}{error&&<p role="status">Esta información no está disponible por el momento.</p>}</section></>}
    {ghinCards}
  </section>;
}
