"use client";
import { COACH_CAPABILITIES } from "../../lib/coach-capabilities";
import type { GolfInsights } from "../../lib/golf-insights";
import { BackyardIcon } from "./backyard-icon";
import styles from "./my-coach.module.css";
import {useVisualContent} from "./use-visual-content";
export function MyCoach({ insights, ready, onBallFit, onLaunchMonitor, onProgress, onEquipment, availableOnly = false }: { insights: GolfInsights; ready: boolean; onBallFit: () => void; onLaunchMonitor: () => void; onProgress: () => void; onEquipment: () => void; availableOnly?: boolean }) {
  const copy=useVisualContent();const ballCopy=copy.find(c=>c.target_key==="coach_ball_fit")?.values;const launchCopy=copy.find(c=>c.target_key==="coach_launch_monitor")?.values;
  return <section className={styles.screen} aria-label="My Coach">
    <section className={styles.hero}><h2>Tu coach personal</h2><p>Analiza. Aprende. Mejora.</p>{!availableOnly&&<div className={styles.swing}><h3>ANÁLISIS DE SWING</h3><p>Tu video, análisis y feedback en un solo lugar.</p><label className={styles.pending}>Próximamente<input type="file" accept="video/*" disabled={!COACH_CAPABILITIES.swingAnalysis} aria-label="Subir video para análisis de swing" /></label><small>Disponible cuando se active el análisis de video.</small></div>}</section>
    <button type="button" className={styles.launch} onClick={onLaunchMonitor} disabled={launchCopy?.active===false}><div><h2>{launchCopy?.title || "LAUNCH MONITOR"}</h2><p>{launchCopy?.body || "Captura y analiza tus mediciones."}</p></div><BackyardIcon name="arrow" /></button>
    <div className={styles.grid}><button type="button" className={styles.card} onClick={onBallFit} disabled={ballCopy?.active===false}><BackyardIcon name="ball" /><h3>{ballCopy?.title || "BALL FIT"}</h3><p>{ballCopy?.body || "Encuentra tu bola con tus datos y preferencias."}</p><span>Abrir fitting ›</span></button>{!availableOnly&&<><div className={styles.card} aria-disabled={!COACH_CAPABILITIES.drills}><BackyardIcon name="approach" /><h3>DRILLS</h3><p>Ejercicios para tu práctica.</p><small>Próximamente</small></div><div className={styles.card} aria-disabled={!COACH_CAPABILITIES.trainingRecommendations}><BackyardIcon name="mental" /><h3>RECOMENDACIONES IA</h3><p>Entrenamiento para tu siguiente paso.</p><small>Próximamente</small></div></>}<button type="button" className={styles.card} onClick={onEquipment}><BackyardIcon name="club" /><h3>MI BOLSA</h3><p>El mismo equipo que usas en tus rondas.</p><span>Abrir mi equipo ›</span></button></div>
    <section className={styles.progress}><div className={styles.progressTitle}><div><h2>MI PROGRESO</h2><p>Una mejor versión, hoy.</p></div><button type="button" onClick={onProgress}>Ver estadísticas ›</button></div>{ready && insights.scoredRounds ? <div className={styles.metrics}><div><b>{insights.last5Average?.toFixed(1) ?? "—"}</b><small>Promedio últimas 5 · {insights.scoreScopeHoles}H</small></div><div><b>{insights.last10Average?.toFixed(1) ?? "—"}</b><small>Promedio últimas 10 · {insights.scoreScopeHoles}H</small></div></div> : <p className={styles.empty}>{ready ? "Tus tendencias aparecerán con rondas guardadas y datos completos." : "Esperando confirmar tus estadísticas."}</p>}</section>
  </section>;
}
