"use client";
import { useMemo, useState } from "react";
import type { RoundSnapshot } from "../../lib/types";
import { buildFilteredGolfInsights, filterStatsRounds, type StatsWindow } from "../../features/stats/domain";
import { summarizeClubDistances } from "../../features/shots/domain";
import { historyGolfDetail, againstPar, recordedGolfAccuracy } from "../../lib/golf-scorecard-presentation";
import { golfCoachMetric, type GolfCoachContext } from "../../lib/golf-coach-context";
import { useGolfNavigation } from "./golf-object-navigation";
import { GolfDetailHeader, GolfEmptyState, golfDate } from "./golf-detail-ui";
import styles from "./golf-object.module.css";
export function PremiumGolfStatistics({rounds,onBack,onMore}:{rounds:RoundSnapshot[];onBack:()=>void;onMore:()=>void}) {
  const [view,setView]=useState("summary"),[period,setPeriod]=useState<StatsWindow>(20),[scope,setScope]=useState<9|18>(18),navigation=useGolfNavigation();
  const insights=useMemo(()=>buildFilteredGolfInsights(rounds,{window:period}),[rounds,period]);
  const selected=insights.scoreCohorts[scope] || insights.scoreCohorts[9] || insights.scoreCohorts[18], actualScope=selected?.holeCount || scope;
  const recent=selected?.recentRounds || [], putts=recent.filter(r=>r.putts!==null), averagePutts=putts.length?putts.reduce((n,r)=>n+r.putts!,0)/putts.length:null;
  const selectedRounds=useMemo(()=>filterStatsRounds(rounds,{window:period}),[rounds,period]);
  const recorded=useMemo(()=>recordedGolfAccuracy(selectedRounds,new Set(insights.recentRounds.map(r=>r.id))),[selectedRounds,insights]);
  const distances=useMemo(()=>summarizeClubDistances(selectedRounds.flatMap(r=>historyGolfDetail(r)?.shots||[])),[selectedRounds]);
  const fir=recorded.fairwayAttempts?Math.round(recorded.fairwaysHit/recorded.fairwayAttempts*100):null,gir=recorded.greenAttempts?Math.round(recorded.greensInRegulation/recorded.greenAttempts*100):null;
  function coach(category:GolfCoachContext["category"],metric:GolfCoachContext["metric"]) { navigation?.open({kind:"coach",id:"mine",context:{category,metric,period,...(metric==="putts"?{holes:actualScope}:{})}}); }
  return <section className={styles.screen}><GolfDetailHeader title="Mis estadísticas" onBack={onBack}/><nav className={styles.tabs} aria-label="Secciones de estadísticas">{[['summary','Resumen'],['shots','Tiros'],['approach','Approach'],['putting','Putting']].map(([id,label])=><button type="button" key={id} aria-pressed={view===id} onClick={()=>setView(id)}>{label}</button>)}</nav>
    <label className={styles.statsFilters}>Periodo<select value={period} onChange={event=>setPeriod(event.target.value==="ALL"||event.target.value==="SEASON"?event.target.value:Number(event.target.value) as 5|10|20)}>{[5,10,20].map(n=><option value={n} key={n}>Últimas {n} rondas</option>)}<option value="SEASON">Esta temporada</option><option value="ALL">Todo mi histórico</option></select></label>
    {!insights.scoredRounds?<GolfEmptyState title="Tu juego, en perspectiva" copy="Completa una ronda para comenzar a conocer tus tendencias."/>:<>
      {view==="summary"&&<>{insights.scoredRounds9>0&&insights.scoredRounds18>0&&<nav className={styles.tabs} aria-label="Longitud de ronda">{([9,18] as const).map(n=><button type="button" key={n} aria-pressed={actualScope===n} onClick={()=>setScope(n)}>{n} hoyos</button>)}</nav>}<div className={styles.statsHero}><span>Score promedio · {actualScope} hoyos</span><strong>{selected?.averageScore?.toFixed(1)??"—"}</strong><p>{selected?.rounds || 0} rondas comparables · Mejor score {selected?.bestScore ?? "—"}</p>{recent.length>0&&<div className={styles.statsBars} role="img" aria-label={`Scores recientes: ${recent.slice(0,10).reverse().map(r=>`${golfDate(r.date)}: ${r.gross}`).join(", ")}`}>{recent.slice(0,10).reverse().map(r=><span key={r.id} title={`${r.courseName}: ${r.gross}`} style={{height:`${r.gross/Math.max(...recent.slice(0,10).map(v=>v.gross))*100}%`}}/>)}</div>}</div><div className={styles.statsMetrics}><button type="button" disabled={fir===null} onClick={()=>coach("tee","fairways")}><small>Fairways</small><b>{fir===null?"—":`${fir}%`}</b><span>{recorded.fairwayAttempts} hoyos</span></button><button type="button" disabled={gir===null} onClick={()=>coach("approach","gir")}><small>GIR</small><b>{gir===null?"—":`${gir}%`}</b><span>{recorded.greenAttempts} hoyos</span></button><button type="button" disabled={averagePutts===null} onClick={()=>coach("putting","putts")}><small>Putts</small><b>{averagePutts?.toFixed(1)??"—"}</b><span>{putts.length} rondas · {actualScope} H</span></button></div><section className={styles.section}><h2>Rondas recientes</h2><ul className={styles.roundList}>{recent.slice(0,5).map(r=><li key={r.id}><button type="button" onClick={()=>navigation?.open({kind:"round",id:r.id,source:"history"})}><span><b>{r.courseName}</b><small>{golfDate(r.date)}</small></span><strong>{r.gross}<small>{againstPar(r.relativeToPar)}</small></strong></button></li>)}</ul></section></>}
      {view==="shots"&&(distances.length?<><h2>Distancias registradas</h2><ul className={styles.roundList}>{distances.map(d=><li key={d.clubLabel}><div className={styles.statsHero}><span>{d.clubLabel}</span><strong>{d.averageYards===null?"—":`${d.averageYards} yd`}</strong><p>{d.sampleCount} golpes medidos{d.averageYards===null?" · Aún faltan muestras para el promedio":""}</p></div></li>)}</ul></>:<GolfEmptyState title="Conoce tus distancias" copy="No hay suficientes golpes medidos en este periodo. Tus scores siguen disponibles en Resumen."/>)}
      {view==="approach"&&(gir!==null?<><div className={styles.statsHero}><span>Greens en regulación</span><strong>{gir}%</strong><p>{recorded.greensInRegulation} de {recorded.greenAttempts} hoyos capturados</p></div><button type="button" className={styles.primary} onClick={()=>coach("approach","gir")}>Trabajar approach en My Coach</button></>:<GolfEmptyState title="Tu approach, con datos" copy="Captura GIR en tus rondas para conocer esta parte de tu juego."/>)}
      {view==="putting"&&(averagePutts!==null?<><div className={styles.statsHero}><span>Putts por ronda · {actualScope} hoyos</span><strong>{averagePutts.toFixed(1)}</strong><p>{putts.length} tarjetas con captura completa</p></div><button type="button" className={styles.primary} onClick={()=>coach("putting","putts")}>Trabajar putting en My Coach</button></>:<GolfEmptyState title="Cada putt cuenta" copy="Captura los putts de todos los hoyos para ver un promedio comparable."/>)}
    </>}<button type="button" className={styles.textAction} onClick={onMore}>Explorar el análisis completo ›</button>
  </section>;
}
export function GolfCoachMetricContext({rounds,context,ready}:{rounds:RoundSnapshot[];context:GolfCoachContext;ready:boolean}) {
  const metric=ready?golfCoachMetric(rounds,context):null;
  return <section className={styles.coachContext} aria-label="Contexto de tus estadísticas"><small>DESDE MIS ESTADÍSTICAS</small><h2>{context.category==="putting"?"Putting":context.category==="approach"?"Approach":"Tee"}</h2><p>{metric?.value!==null&&metric?.value!==undefined?`${metric.value.toFixed(1)} ${metric.unit} · ${metric.sample} ${context.metric==="putts"?"rondas":"hoyos"}`:"Sin información suficiente en este periodo."}</p><p>{context.period==="ALL"?"Todo tu histórico":context.period==="SEASON"?"Esta temporada":`Últimas ${context.period} rondas`}. Conservamos esta métrica como contexto para tu práctica.</p></section>;
}
