"use client";
import {useCallback,useEffect,useRef,useState,type ReactNode} from 'react';
import type {SocialActivityCard,SocialActivityPage} from '../../lib/social-activity-contract';
import type {SocialPerson,ConnectionPage} from '../../lib/social-connections';
import {connectionState} from '../../lib/social-connections';
import {socialRequest,socialErrorMessage} from '../../lib/social-activity-client';
import {mergeSocialCards} from '../../lib/social-feed-presentation';
import {sharedPlayerRounds,sharedPlayerAchievements,sharedPlayerCourses} from '../../lib/social-player-presentation';
import {socialPlayerTabFromSearch,type SocialPlayerTab} from '../../lib/social-player-navigation';
import {CloudSocialActivity,socialScorecardDestination} from './cloud-social-activity';
import {ScorecardNavigationBoundary,type ScorecardDestination} from './scorecard-boundary';
import {ProfileAvatarMedia} from './profile-avatar-media';
import {BackyardIcon} from './backyard-icon';
import Image from 'next/image';
import styles from './social-player-profile.module.css';
type Person=SocialPerson&{club_name?:string|null};
type ProfileData={person:Person;friends:Person[];friendsComplete:boolean;connectionsScope:'OWN'|'VISIBLE'};
const EMPTY:ConnectionPage={people:[],requests:[],friends:[],blocked:[]};
function ProfileRelationship({viewerId,personId,accessToken}:{viewerId:string;personId:string;accessToken:string}) {
  const [graph,setGraph]=useState<ConnectionPage>(EMPTY),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[message,setMessage]=useState('');const lock=useRef(false),alive=useRef(true);
  useEffect(()=>{alive.current=true;const controller=new AbortController();void socialRequest<ConnectionPage>('/api/social/connections',accessToken,{signal:controller.signal}).then(g=>{if(!controller.signal.aborted)setGraph(g);}).catch(e=>{if(!controller.signal.aborted)setMessage(socialErrorMessage(e));}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>{alive.current=false;controller.abort();};},[accessToken]);
  async function action(body:Record<string,unknown>){if(lock.current)return;lock.current=true;setBusy(true);setMessage('');try{const next=await socialRequest<ConnectionPage>('/api/social/connections',accessToken,{method:'POST',body:{...body,operationId:crypto.randomUUID()}});if(alive.current)setGraph(next);}catch(e){if(alive.current)setMessage(socialErrorMessage(e));}finally{lock.current=false;if(alive.current)setBusy(false);}}
  const state=connectionState(graph,viewerId,personId),request=graph.requests.find(r=>r.state==='PENDING'&&(r.requester_id===personId||r.addressee_id===personId));
  return <div className={styles.relationship}>{loading?<span role="status">Consultando conexión…</span>:state==='NONE'?<button type="button" disabled={busy} onClick={()=>void action({action:'request',target:personId})}>Agregar amigo</button>:state==='INCOMING'&&request?<><button type="button" disabled={busy} onClick={()=>void action({action:'ACCEPTED',id:request.id})}>Aceptar solicitud</button><button type="button" disabled={busy} onClick={()=>void action({action:'REJECTED',id:request.id})}>Ignorar</button></>:<span>{state==='SELF'?'Mi perfil social':state==='FRIEND'?'✓ Amigos':state==='PENDING'?'Solicitud enviada':'Conexión no disponible'}</span>}{state==='PENDING'&&request&&<button type="button" disabled={busy} onClick={()=>void action({action:'CANCELLED',id:request.id})}>Cancelar solicitud</button>}{message&&<p role="status">{message}</p>}</div>;
}
export function SocialPlayerProfile({userId,viewerId,accessToken,onBack,onOpenPlayer,relationship,onOwnProfile}:{userId:string;viewerId:string;accessToken:string;onBack:()=>void;onOpenPlayer:(id:string)=>void;relationship?:ReactNode;onOwnProfile?:()=>void}) {
  const [profile,setProfile]=useState<ProfileData|null>(null),[cards,setCards]=useState<SocialActivityCard[]>([]),[tab,setTab]=useState<SocialPlayerTab>('activity'),[cursor,setCursor]=useState<string|null>(null),[message,setMessage]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[destination,setDestination]=useState<ScorecardDestination>();
  const live=useRef(true),lock=useRef(false),positions=useRef(new Map<SocialPlayerTab,number>());
  const path=`/api/social/activity?authorId=${encodeURIComponent(userId)}`;
  useEffect(()=>{live.current=true;const controller=new AbortController();const read=()=>setTab(socialPlayerTabFromSearch(location.search));read();window.addEventListener('popstate',read);
    void Promise.all([socialRequest<ProfileData>(`/api/social/profile/${encodeURIComponent(userId)}`,accessToken,{signal:controller.signal}),socialRequest<SocialActivityPage>(path,accessToken,{signal:controller.signal})]).then(([person,page])=>{if(!controller.signal.aborted){if(person.person.user_id!==userId||page.data.some(c=>c.author.userId!==userId))throw new Error('Identidad no disponible.');setProfile(person);setCards(mergeSocialCards([],page.data));setCursor(page.nextCursor);}}).catch(e=>{if(!controller.signal.aborted)setMessage(socialErrorMessage(e));}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});
    return()=>{live.current=false;controller.abort();window.removeEventListener('popstate',read);};
  },[userId,accessToken,path]);
  useEffect(()=>{
    const params=new URLSearchParams(location.search);
    if(socialPlayerTabFromSearch(location.search)==='activity')return;
    const id=params.get('card')?.match(/^social:([0-9a-f-]{36})$/i)?.[1];
    if(!id)return;
    const controller=new AbortController();
    void socialRequest<{data:SocialActivityCard}>(`/api/social/activity/${encodeURIComponent(id)}`,accessToken,{signal:controller.signal}).then(result=>{
      if(!controller.signal.aborted){if(result.data.id!==id||result.data.author.userId!==userId||!result.data.round)throw new Error('La tarjeta no está disponible.');setDestination(socialScorecardDestination(result.data));}
    }).catch(error=>{if(!controller.signal.aborted)setMessage(socialErrorMessage(error));});
    return()=>controller.abort();
  },[accessToken,userId]);
  async function more(){if(!cursor||lock.current)return;lock.current=true;setBusy(true);try{const page=await socialRequest<SocialActivityPage>(`${path}&cursor=${encodeURIComponent(cursor)}`,accessToken);if(page.data.some(c=>c.author.userId!==userId)||page.nextCursor===cursor)throw new Error('No se confirmó la actividad del jugador.');if(live.current){setCards(current=>mergeSocialCards(current,page.data));setCursor(page.nextCursor);}}catch(e){if(live.current)setMessage(socialErrorMessage(e));}finally{lock.current=false;if(live.current)setBusy(false);}}
  const openCard=useCallback(async(card:SocialActivityCard,open:(d?:ScorecardDestination)=>void)=>{if(lock.current)return;lock.current=true;setBusy(true);setMessage('');try{const r=await socialRequest<{data:SocialActivityCard}>(`/api/social/activity/${encodeURIComponent(card.id)}`,accessToken);if(r.data.id!==card.id||r.data.roundId!==card.roundId||r.data.author.userId!==userId)throw new Error('La tarjeta no está disponible.');if(live.current){const dest=socialScorecardDestination(r.data);setDestination(dest);open(dest);}}catch(e){if(live.current)setMessage(socialErrorMessage(e));}finally{lock.current=false;if(live.current)setBusy(false);}},[accessToken,userId]);
  function select(next:SocialPlayerTab){positions.current.set(tab,window.scrollY);setTab(next);const url=new URL(location.href);url.searchParams.set('playerTab',next);window.history.replaceState(window.history.state,'',url);window.scrollTo({top:positions.current.get(next)??0,behavior:'instant'});}
  const rounds=sharedPlayerRounds(cards,userId),achievements=sharedPlayerAchievements(cards,userId),courses=sharedPlayerCourses(cards,userId),equipment=cards.filter(c=>c.author.userId===userId&&c.equipment).sort((a,b)=>b.createdAt.localeCompare(a.createdAt))[0]?.equipment;
  const empty=(copy:string)=><div className={styles.empty}><BackyardIcon name="flag" size={28}/><p>{copy}</p></div>;
  return <ScorecardNavigationBoundary destination={destination} originLabel="perfil del jugador">{open=><section className={styles.profile} aria-label="Perfil social del jugador">
    <header className={styles.heading}><button type="button" aria-label="Volver desde perfil del jugador" onClick={onBack}>‹</button><b>Perfil del jugador</b>{userId===viewerId&&onOwnProfile&&<button type="button" onClick={onOwnProfile}>Mi perfil</button>}</header>
    {loading?<p role="status">Cargando perfil…</p>:profile?<><div className={styles.identity}><ProfileAvatarMedia className={styles.avatar} value={profile.person.avatar_url} fallback={profile.person.display_name[0]||'J'}/><div><h1>{profile.person.display_name}</h1><p>@{profile.person.username}</p>{profile.person.club_name&&<small>{profile.person.club_name}</small>}</div></div>{relationship??<ProfileRelationship viewerId={viewerId} personId={userId} accessToken={accessToken}/>}<nav className={styles.tabs} aria-label="Secciones del perfil">{([['activity','Actividad'],['rounds','Rondas'],['achievements','Logros'],['courses','Campos'],['equipment','Equipo'],['friends','Amigos']] as const).map(([key,label])=><button type="button" key={key} aria-pressed={tab===key} onClick={()=>select(key)}>{label}</button>)}</nav>
    <div hidden={tab!=='activity'}><CloudSocialActivity key={userId} viewerId={viewerId} accessToken={accessToken} authorId={userId} onOpenProfile={onOpenPlayer}/></div>
    {tab==='rounds'&&(rounds.length?<ul className={styles.rounds}>{rounds.map(c=><li key={c.id}><button type="button" disabled={busy} onClick={()=>void openCard(c,open)}><span><b>{c.round!.courseName}</b><small>{c.round!.date} · {c.round!.holesPlayed} hoyos{c.round!.teeName?` · ${c.round!.teeName}`:''}</small></span><span className={styles.score}><strong>{c.round!.ownerScore??'—'}</strong>{c.round!.toPar!==undefined&&<small>{c.round!.toPar>0?'+':''}{c.round!.toPar===0?'E':c.round!.toPar}</small>}</span><BackyardIcon name="chevron" size={14}/></button></li>)}</ul>:empty('No hay rondas compartidas disponibles para tu cuenta.'))}
    {tab==='achievements'&&(achievements.length?<ul className={styles.achievements}>{achievements.map(a=><li key={a.key}><BackyardIcon name="trophy" size={25}/><button type="button" disabled={busy} onClick={()=>void openCard(a.card,open)}><b>{a.label}</b><small>{a.card.round?.date} · Ver tarjeta ›</small></button></li>)}</ul>:empty('Este jugador todavía no ha compartido logros contigo.'))}
    {tab==='courses'&&(courses.length?<ul className={styles.rounds}>{courses.map(c=><li key={c.key}><div className={styles.course}><BackyardIcon name="flag" size={24}/><span><b>{c.name}</b><small>{c.rounds} rondas compartidas · {c.holes} hoyos</small></span>{c.best!==null&&<span className={styles.score}><small>Mejor</small><strong>{c.best}</strong></span>}</div></li>)}</ul>:empty('No hay campos compartidos disponibles.'))}
    {tab==='equipment'&&(equipment?.items.length?<ul className={styles.equipment}>{equipment.items.map(item=><li key={item.id}>{item.imageUrl?<Image src={item.imageUrl} alt={`${item.brand} ${item.model}`} width={52} height={52}/>:<BackyardIcon name="club" size={32}/>}<span><small>{item.category}</small><b>{item.brand} {item.model}</b></span></li>)}</ul>:empty('La bolsa no está compartida o todavía no tiene equipo visible.'))}
    {tab==='friends'&&<><p className={styles.caption}>{profile.connectionsScope==='OWN'?'Tus amigos':'Conexiones visibles para ti'}. Las listas privadas no se muestran.</p>{profile.friends.length?<ul className={styles.rounds}>{profile.friends.map(p=><li key={p.user_id}><button type="button" onClick={()=>onOpenPlayer(p.user_id)}><ProfileAvatarMedia className={styles.friendAvatar} value={p.avatar_url} fallback={p.display_name[0]||'J'}/><span><b>{p.display_name}</b><small>@{p.username}</small></span><BackyardIcon name="chevron" size={14}/></button></li>)}</ul>:empty('No hay conexiones visibles para tu cuenta.')}{!profile.friendsComplete&&<p className={styles.caption}>Se muestran las primeras 100 conexiones autorizadas.</p>}</>}
    {tab!=='activity'&&tab!=='friends'&&<p className={styles.caption}>Basado únicamente en actividad compartida{cursor?' · hay más actividad disponible':''}.</p>}{cursor&&tab!=='activity'&&tab!=='friends'&&<button type="button" className={styles.more} disabled={busy} onClick={()=>void more()}>{busy?'Cargando…':'Ver más actividad compartida'}</button>}
    </>:null}{message&&<p role="status" className={styles.notice}>{message}</p>}
  </section>}</ScorecardNavigationBoundary>;
}
