"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import type { SocialProfile } from "../../features/social/domain";
import { connectionState, type ConnectionPage, type SocialPerson } from "../../lib/social-connections";
import { socialRequest, socialErrorMessage } from "../../lib/social-activity-client";
import { ProfileAvatarMedia } from "./profile-avatar-media";
import { AnchoredSearch, AnchoredSearchOption } from "./anchored-search";
const EMPTY:ConnectionPage={people:[],requests:[],friends:[],blocked:[]};
export function SocialConnectionsPanel({ownerId,accessToken,targetId,onCloseTarget,onChanged}: {ownerId:string;accessToken?:string;directory?:SocialProfile[];targetId?:string|null;onCloseTarget?:()=>void;onChanged?:()=>void}) {
 const [data,setData]=useState<ConnectionPage>(EMPTY),[query,setQuery]=useState(""),[results,setResults]=useState<SocialPerson[]>([]),[selected,setSelected]=useState<SocialPerson|null>(null),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 const lock=useRef(false);
 const refresh=useCallback(async()=>{if(accessToken)setData(await socialRequest<ConnectionPage>("/api/social/connections",accessToken));},[accessToken]);
 useEffect(()=>{const controller=new AbortController(); if(accessToken) void socialRequest<ConnectionPage>("/api/social/connections",accessToken,{signal:controller.signal}).then(setData).catch(e=>{if(!controller.signal.aborted)setMessage(socialErrorMessage(e));});return()=>controller.abort();},[accessToken]);
 useEffect(()=>{const c=new AbortController(); if(targetId&&accessToken) void socialRequest<{person:SocialPerson}>(`/api/social/connections?target=${encodeURIComponent(targetId)}`,accessToken,{signal:c.signal}).then(r=>{setSelected(r.person);setMessage("");}).catch(e=>{if(!c.signal.aborted)setMessage(socialErrorMessage(e));});return()=>c.abort();},[targetId,accessToken]);
 useEffect(()=>{setResults([]);if(!accessToken||query.trim().length<2)return;const c=new AbortController();const timer=setTimeout(()=>{void socialRequest<{users:SocialPerson[]}>(`/api/groups/users?q=${encodeURIComponent(query.trim())}`,accessToken,{signal:c.signal}).then(r=>setResults(r.users)).catch(e=>{if(!c.signal.aborted)setMessage(socialErrorMessage(e));});},300);return()=>{clearTimeout(timer);c.abort();};},[accessToken,query]);
 async function action(body:Record<string,unknown>){if(!accessToken||lock.current)return;lock.current=true;setBusy(true);setMessage("");try{setData(await socialRequest<ConnectionPage>("/api/social/connections",accessToken,{method:"POST",body:{...body,operationId:crypto.randomUUID()}}));setMessage("Cambio guardado.");onChanged?.();}catch(e){setMessage(socialErrorMessage(e));}finally{lock.current=false;setBusy(false);}}
 const person=(id:string)=>data.people.find(p=>p.user_id===id);
 const label=(p:SocialPerson)=><><span className="socialProfileAvatar"><ProfileAvatarMedia value={p.avatar_url} fallback={p.display_name[0]||"J"}/></span><span><b>{p.display_name}</b><small>@{p.username}</small></span></>;
 if(!accessToken)return <section className="card"><h2>Amigos</h2><p>Inicia sesión para buscar y enviar solicitudes.</p></section>;
 return <section className="socialConnections"><section className="card"><h2>Agregar amigos</h2><AnchoredSearch label="Nombre, @usuario o correo exacto" value={query} onChange={setQuery} placeholder="Buscar usuarios Backyard" expanded={query.trim().length>=2&&results.length>0}>{results.map(p=><AnchoredSearchOption key={p.user_id} label={`Ver perfil de ${p.display_name}`} onSelect={()=>{setSelected(p);setQuery("");}}>{label(p)}</AnchoredSearchOption>)}</AnchoredSearch><p className="hint">Los correos no se muestran. La búsqueda respeta privacidad y bloqueos.</p></section>
 {selected&&<section className="card" aria-label="Perfil social"><button type="button" className="textButton" onClick={()=>{setSelected(null);onCloseTarget?.();}}>Cerrar perfil ×</button><div className="socialProfileResults">{label(selected)}</div>{(()=>{const state=connectionState(data,ownerId,selected.user_id);return state==="NONE"?<button type="button" className="primary" disabled={busy} onClick={()=>void action({action:"request",target:selected.user_id})}>Agregar amigo</button>:<p>{state==="SELF"?"Este es tu perfil.":state==="FRIEND"?"Amigos ✓":state==="INCOMING"?"Solicitud recibida · acéptala abajo.":state==="BLOCKED"?"Conexión bloqueada.":"Solicitud enviada"}</p>;})()}<p className="hint">Agregar a un grupo o ronda es una acción independiente. Ver un QR no acepta una amistad.</p></section>}
 {message&&<p className="notice" role="status">{message}</p>}
 <section className="card"><h2>Solicitudes</h2>{data.requests.filter(r=>r.state==="PENDING").map(r=>{const incoming=r.addressee_id===ownerId;const p=person(incoming?r.requester_id:r.addressee_id);return <div className="socialPendingList" key={r.id}><p>{p?`${p.display_name} · @${p.username}`:"Usuario no disponible"} · {incoming?"Recibida":"Enviada"}</p>{incoming?<><button type="button" className="primary" disabled={busy} onClick={()=>void action({action:"ACCEPTED",id:r.id})}>Aceptar</button><button type="button" className="secondary" disabled={busy} onClick={()=>void action({action:"REJECTED",id:r.id})}>Rechazar</button></>:<button type="button" disabled={busy} onClick={()=>void action({action:"CANCELLED",id:r.id})}>Cancelar solicitud</button>}</div>;})}{!data.requests.some(r=>r.state==="PENDING")&&<p>No hay solicitudes pendientes.</p>}</section>
 <section className="card"><h2>Amigos · {data.friends.length}</h2><ul className="socialProfileResults">{data.friends.map(id=>{const p=person(id);return p?<li key={id}>{label(p)}<button type="button" onClick={()=>setSelected(p)}>Ver perfil</button><button type="button" disabled={busy} onClick={()=>{if(confirm("¿Bloquear esta conexión? Se revocará la amistad y el acceso social entre ambos."))void action({action:"block",target:id});}}>Bloquear</button></li>:null;})}</ul>{!data.friends.length&&<p>Busca un compañero o escanea su QR para enviarle una solicitud.</p>}<button type="button" className="textButton" disabled={busy} onClick={()=>void refresh().catch(e=>setMessage(socialErrorMessage(e)))}>Actualizar</button></section></section>;
}
