import test from "node:test";
import assert from "node:assert/strict";
import { adminCatalogPage, buildCoursePayload, buildEquipmentPayload, buildCompetitionPayload, humanChanges, safeFields, latestPublishedVisualVersions, catalogFields, COURSE_FIELDS } from "../lib/admin-simple-catalog";
import { CLUB_CATEGORIES } from "../lib/golf-equipment";
import { coursePayloadIssues, equipmentPayloadIssues } from "../lib/admin-payload-validation";
const base={club:{id:"club-a",name:"Club",city:"Ciudad"},course:{id:"course-a",name:"Campo",holes:18,active:true},tees:[{id:"tee-a",name:"Azul",rating:72,slope:136,active:true}],holes:[],teeHoleYardages:[]};
const values={name:"Campo",clubName:"Club",holeCount:"18",active:true,tees:[{...base.tees[0],rating:72.1,slope:134}]};
test("course edits preserve IDs and existing scorecard references, rating/slope validate together",()=>{const payload=buildCoursePayload(base,values);assert.equal(payload.course.id,"course-a");assert.equal(payload.tees[0].id,"tee-a");assert.deepEqual(coursePayloadIssues(payload,"course-a"),[]);assert.ok(humanChanges(base,payload).some(c=>c.label.includes("Slope")&&c.before==="136"&&c.after==="134"));});
test("forged or removed historically referenced tees and invalid coordinates are rejected",()=>{assert.throws(()=>buildCoursePayload(base,{...values,tees:[]}),/Desactiva/);assert.throws(()=>buildCoursePayload(base,{...values,tees:[{...base.tees[0],id:"other-course-tee"}]}),/no pertenece/);assert.throws(()=>safeFields({...values,latitude:200},COURSE_FIELDS),/Latitud/);});
test("new record preview spells out actual fields instead of raw JSON",()=>{const changes=humanChanges({},base);assert.ok(changes.some(c=>c.label.includes("Rating")&&c.after==="72"));assert.ok(!changes.some(c=>c.label.endsWith("id")));});
test("equipment edits preserve existing IDs, historical variants and do not accept client engine fields",()=>{const base={id:"club-real",variants:[{loft:56,bounce:12,grind:"S"}]};const payload=buildEquipmentPayload(base,{id:"forged",brand:"Marca",model:"Modelo",category:"WEDGE",active:false,bagEligible:true,fitEligible:false,sourceType:"ADMIN_RESEARCH",sourceName:"Tarjeta oficial",year:"",handsText:"RH",loftsText:"56",engineContract:{fake:true}},"CLUB_EQUIPMENT");assert.equal(payload.id,"club-real");assert.deepEqual(payload.variants,base.variants);assert.ok(!("engineContract" in payload));assert.deepEqual(equipmentPayloadIssues(payload,"CLUB_EQUIPMENT","club-real"),[]);});
test("ball fitting visibility requires verified specifications and never adds algorithm parameters",()=>{const input={brand:"Marca",model:"Bola",active:true,bagEligible:true,fitEligible:false,sourceType:"ADMIN_RESEARCH",sourceName:"Fabricante",year:"",flight:"",driverSpin:"",ironSpin:"",shortGameSpin:"",feel:"",compression:"",algorithm:"arbitrary"};const payload=buildEquipmentPayload({id:"ball-real"},input,"BALL");assert.deepEqual(equipmentPayloadIssues(payload,"BALL","ball-real"),[]);assert.ok(!("algorithm" in payload));assert.ok(equipmentPayloadIssues({...payload,fitEligible:true},"BALL","ball-real").some(s=>s.includes("tres especificaciones")));});

test("nullable catalog fields remain editable without inventing specifications",()=>{
  const fields=catalogFields("BALL");
  const input={brand:"Marca",model:"Bola",active:true,bagEligible:true,fitEligible:false,sourceType:"ADMIN_RESEARCH",feel:null,construction:null};
  const result=safeFields(input,fields);assert.equal(result.feel,null);assert.equal(result.construction,null);
  assert.throws(()=>safeFields({...input,brand:null},fields),/Marca/);
  assert.throws(()=>safeFields({...input,feel:{}},fields),/Sensación/);
  for(const category of CLUB_CATEGORIES){const club=buildEquipmentPayload({id:"club"},{...input,category,handsText:"RH",loftsText:"",setMakeup:null},"CLUB_EQUIPMENT");assert.equal(club.category,category);assert.equal(club.setMakeup,null);}
});

test("published presentation selects the newest version regardless of ordering and ignores drafts",()=>{
  const rows=[{target_key:"skins",version:3,status:"PUBLISHED",title:"Actual"},{target_key:"skins",version:4,status:"DRAFT",title:"Pendiente"},{target_key:"skins",version:1,status:"PUBLISHED",title:"Anterior"}];
  assert.equal(latestPublishedVisualVersions(rows).get("skins")?.title,"Actual");
  assert.equal(latestPublishedVisualVersions([...rows].reverse()).get("skins")?.version,3);
});
test("competition edits preserve deterministic contracts and existing rule IDs",()=>{const base={id:"event",engineContract:{version:1},rules:[{id:"rule",category:"SCORING",title:"Medal",body:"Regla existente"}]};const result=buildCompetitionPayload(base,{name:"Evento",type:"TOURNAMENT",visibility:"PRIVATE",ruleBody:"Información",engineContract:{version:99},courseId:"course-a"});assert.deepEqual(result.engineContract,base.engineContract);assert.equal((result.rules as Record<string,unknown>[])[0].id,"rule");assert.equal(result.id,"event");});
test("catalog pagination applies state and search before slicing without dropping inactive history",()=>{const items=Array.from({length:85},(_,i)=>({id:String(i),title:"Campo",subtitle:String(i),active:i%2===0,kind:"COURSE" as const,values:{}}));const first=adminCatalogPage(items,"campo","active","0");assert.equal(first.total,43);assert.equal(first.items.length,40);assert.equal(first.nextOffset,40);const last=adminCatalogPage(items,"campo","active","40");assert.equal(last.items.length,3);assert.equal(last.nextOffset,null);assert.equal(adminCatalogPage(items,"campo","inactive","0").total,42);assert.throws(()=>adminCatalogPage(items,"","all","-1"));assert.throws(()=>adminCatalogPage(items,"","invalid",null));});
test("visual scorecard preserves hole identities and safely adds verified yardage without accepting forged references",()=>{const complete={...base,course:{...base.course,holes:9},holes:Array.from({length:9},(_,i)=>({id:`hole-${i+1}`,holeNumber:i+1,par:4,strokeIndex:i+1})),teeHoleYardages:[{teeId:"tee-a",holeId:"hole-1",yards:400}]};const input={...values,holeCount:"9",holes:complete.holes.map(h=>({...h,par:"4",strokeIndex:String(h.strokeIndex)})),yardages:[{teeIndex:0,holeIndex:0,yards:"410"}]};const payload=buildCoursePayload(complete,input);assert.equal(payload.holes[0].id,"hole-1");assert.equal(payload.teeHoleYardages[0].yards,410);assert.deepEqual(coursePayloadIssues(payload,"course-a"),[]);assert.throws(()=>buildCoursePayload(complete,{...input,holes:[]}),/históricos/);assert.throws(()=>buildCoursePayload(complete,{...input,holes:[{id:"foreign",par:4,strokeIndex:1}]}),/no pertenece/);assert.throws(()=>buildCoursePayload(complete,{...input,yardages:[{teeIndex:99,holeIndex:0,yards:400}]}),/yardas/);assert.throws(()=>buildCoursePayload(complete,{...input,holes:input.holes.map(h=>({...h,par:""}))}),/Completa/);});
