import assert from 'node:assert/strict';
import test from 'node:test';
import {canRequestAttest,attestCompanionLabel,type AttestCompanion} from '../lib/attest-requests';
import {socialUI,uiFind,uiNodes,uiText,settleUI} from './helpers/social-ui';
import {normalizeNotifications,notificationDestination} from '../features/notifications/presentation';
const peer:AttestCompanion={playerKey:'peer',userId:'22222222-2222-4222-8222-222222222222',name:'Compañero real',eligible:true,participation:'CONFIRMED',state:'UNSENT'};
for(const [label,overrides,eligible]of [['guest',{userId:null},false],['private',{eligible:false},false],['pending',{state:'PENDING'},false],['attested',{state:'ATTESTED'},false],['stale',{state:'STALE'},true],['participation required',{participation:'PENDING_CONFIRMATION'},true]] as const)test(`request selection: ${label}`,()=>{assert.equal(canRequestAttest({...peer,...overrides}),eligible);assert.ok(attestCompanionLabel({...peer,...overrides}));});
function dialog(request:(path:string,token:string,options?:any)=>Promise<any>){const h=socialUI('app/components/attest-request-dialog.tsx',{'use-modal-dialog':{useModalDialog:()=>({current:null})},'social-activity-client':{socialRequest:request,socialErrorMessage:(e:Error)=>e.message},'attest-requests':{canRequestAttest,attestCompanionLabel},'client':{notificationsChanged(){}}});const props={card:{id:'activity',author:{displayName:'Propietario'},round:{courseName:'Campo',date:'2026-10-08',ownerScore:80,localRoundId:'round'}},accessToken:'isolated',onClose(){},onSent(){}};return{h,render:()=>h.render('AttestRequestDialog',props)};}
test('real request dialog uses returned roster/hash, locks duplicate taps, confirms only after successful persistence',async()=>{
 const calls:any[]=[];let release:(r:any)=>void=()=>{};const roster={data:[peer,{...peer,playerKey:'guest',userId:null,name:'Invitado'}],expectedHash:'a'.repeat(64),sourceVersion:4};
 const d=dialog(async(path,token,options)=>{calls.push({path,token,options});return options?.method==='POST'?new Promise(resolve=>{release=resolve;}):roster;});d.render();await settleUI();let tree=d.render();const check=uiNodes(tree).filter(n=>n.type==='input');assert.equal(check.length,2);assert.equal(check[1].props.disabled,true);check[0].props.onChange({target:{checked:true}});tree=d.render();const send=uiFind(tree,n=>n.type==='button'&&uiText(n)==='Enviar solicitud');const one=send.props.onClick();send.props.onClick();await settleUI();assert.equal(calls.filter(c=>c.options?.method==='POST').length,1);assert.deepEqual(JSON.parse(JSON.stringify(calls[1].options.body)),{expectedHash:roster.expectedHash,recipients:[peer.userId]});assert.doesNotMatch(uiText(d.render()),/Solicitud enviada a/);release({data:[{id:'persistent'}],roster:{...roster,data:[{...peer,state:'PENDING'}]}});await one;await settleUI();tree=d.render();assert.match(uiText(tree),/Solicitud enviada a Compañero real/);assert.equal(uiFind(tree,n=>n.type==='input').props.disabled,true);
});
test('request dialog reports failure without showing sent or attested',async()=>{const d=dialog(async(_path,_token,options)=>{if(options?.method==='POST')throw Error('No se confirmó la solicitud.');return{data:[peer],expectedHash:'a'.repeat(64),sourceVersion:1};});d.render();await settleUI();uiFind(d.render(),n=>n.type==='input').props.onChange({target:{checked:true}});uiFind(d.render(),n=>n.type==='button'&&uiText(n)==='Enviar solicitud').props.onClick();await settleUI();assert.match(uiText(d.render()),/No se confirmó/);assert.doesNotMatch(uiText(d.render()),/Solicitud enviada a|✓ Atestada/);});
test('reading an attestation request leaves it pending and opens authorized activity, not an arbitrary round',()=>{const events=[{id:'request',type:'attest_request' as const,activityId:'activity',createdAt:'2026-10-08T10:00:00Z',readAt:'2026-10-08T11:00:00Z',attestRequest:{expectedHash:'a'.repeat(64),state:'PENDING' as const}}];const [item]=normalizeNotifications(events,[]);assert.equal(item.pending,true);assert.equal(item.unread,false);assert.equal(notificationDestination(item),'activity');const [stale]=normalizeNotifications([{...events[0],attestRequest:{...events[0].attestRequest,state:'STALE'}}],[]);assert.match(stale.message,/desactualizada/);assert.equal(stale.pending,false);});

