import assert from "node:assert/strict";
import test from "node:test";
import { readFileSync } from "node:fs";
import { runInNewContext } from "node:vm";
import ts from "typescript";
import { careerAttestSummary,backyardIndexTimeline,type CareerAttestCard,type AttestEvidence } from "../lib/career-index-presentation";
import * as presentation from "../lib/career-index-presentation";
import * as roundCards from "../lib/social-round-card";
import * as achievements from "../lib/round-achievements";
import { snapshotBackyardIndexRound,calculateBackyardIndex } from "../lib/backyard-index";
import { careerRound } from "./helpers/career-round";
import { buildGolfInsights } from "../lib/golf-insights";
import { socialUI,uiText,uiNodes,uiFind,settleUI } from "./helpers/social-ui";
const cards=(count=20):Omit<CareerAttestCard,"attested">[]=>Array.from({length:count},(_,i)=>({roundId:`r-${String(i).padStart(2,"0")}`,date:`2026-09-${String(30-i).padStart(2,"0")}`,courseName:"Campo QA sintético",score:72+i,currentHash:`hash-${i}`,version:2}));
const evidence=(items=cards(),count=17):AttestEvidence[]=>items.slice(0,count).map(c=>({round_id:c.roundId,target_user_id:"owner",attester_id:"peer",expected_hash:c.currentHash,expected_version:2}));
for(const [available,attested,percent]of [[20,17,85],[8,8,40],[0,0,0],[20,20,100],[20,0,0]] as const)test(`Atest ${attested} of ${available} available cards is ${percent}% with exactly 20 slots`,()=>{const list=cards(available),result=careerAttestSummary(list,evidence(list,attested),"owner");assert.equal(result.count,attested);assert.equal(result.percent,percent);assert.equal(result.slots.length,20);assert.equal(result.slots.filter(Boolean).length,attested);});
test("Atest keeps most recent 20, not 20 successfully attested cards",()=>{const list=cards(25),result=careerAttestSummary(list.reverse(),evidence(list,25),"owner");assert.equal(result.cards.length,20);assert.equal(result.cards[0].date,"2026-09-30");assert.equal(result.cards.at(-1)!.date,"2026-09-11");assert.equal(result.percent,100);});
test("material change invalidates one old attest: 85% becomes 80%",()=>{const list=cards(),attests=evidence(list);assert.equal(careerAttestSummary(list,attests,"owner").percent,85);list[0].currentHash="new-material-hash";assert.equal(careerAttestSummary(list,attests,"owner").percent,80);});
test("nonmaterial cloud version change retains matching current material attest",()=>{const list=cards(1),attests=evidence(list,1);list[0].version=3;assert.equal(careerAttestSummary(list,attests,"owner").percent,5);});
test("participant confirmation is not an attest and cannot increase the metric",()=>{assert.equal(careerAttestSummary(cards(1),[],"owner").percent,0);});
for(const mutation of ["self","other-target","other-round","future-version"] as const)test(`Atest excludes ${mutation}`,()=>{const list=cards(1),attests=evidence(list,1);if(mutation==="self")attests[0].attester_id="owner";if(mutation==="other-target")attests[0].target_user_id="other";if(mutation==="other-round")attests[0].round_id="other";if(mutation==="future-version")attests[0].expected_version=3;assert.equal(careerAttestSummary(list,attests,"owner").percent,0);});
test("multiple peers and duplicate history do not count a card twice",()=>{const list=cards(1),attests=evidence(list,1);attests.push({...attests[0],attester_id:"another-peer"});assert.equal(careerAttestSummary([...list,...list],attests,"owner").percent,5);});
test("history cannot invent an index from unaccredited scores or another account",()=>{assert.equal(backyardIndexTimeline([careerRound("uncertified",1)],"owner").points.length,0);assert.equal(backyardIndexTimeline([],"owner").low,null);});
function ratedRound(day:number,differential:number){const round=careerRound(`rated-${day}`,day);round.completedAt=`${round.date}T18:00:00Z`;const player=round.players![0];player.handicap=36;player.handicapIndex=8;player.handicapIndexSource="BACKYARD_MANUAL";player.courseHandicapSnapshot={index:8,indexSource:"BACKYARD_MANUAL",teeId:"qa-course",teeName:"Blancas",slope:113,courseRating:72,par:72,courseHandicap:8,appliedHandicap:8,formulaVersion:"WHS-2024-COURSE-HANDICAP-V1",effectiveAt:"2026-08-20T10:00:00Z",calculatedAt:"2026-08-20T10:00:00Z"};Object.assign(round.courseSnapshot!,{catalogCourseId:"qa-course",catalogTeeId:"qa-course",rating:72,slope:113});round.playerTeeAssignments=[{playerId:player.id,courseId:"qa-course",teeId:"qa-course",teeName:"Blancas",source:"catalog",rating:72,slope:113,capturedAt:"2026-08-20T10:00:00Z"}];round.order!.forEach((hole,i)=>{round.scores![hole][player.id]=4+Math.floor(differential/18)+(i<differential%18?1:0);});return snapshotBackyardIndexRound(round,"owner",{ratedTeeEvidence:{kind:"OFFICIAL_RATED_TEE",authority:"Synthetic test fixture",sourceUrl:"https://ratings.example.test/qa-course",verifiedAt:"2026-08-20T10:00:00Z",courseId:"qa-course",teeId:"qa-course",courseRating:72,slopeRating:113},pccEvidence:{kind:"DECLARED_LOCAL_ZERO",value:0,declaredAt:round.completedAt,declaredByAccountUserId:"owner"}});}
test("index history uses canonical frozen evidence; low/average/high are mathematical",()=>{const rounds=[18,16,14,12,10,8].map((d,i)=>ratedRound(i+1,d));const history=backyardIndexTimeline(rounds,"owner");assert.ok(history.points.length>=2);assert.equal(history.points.at(-1)!.value,calculateBackyardIndex(rounds,"owner").value);const values=history.points.map(p=>p.value);assert.equal(history.low,Math.min(...values));assert.equal(history.high,Math.max(...values));assert.equal(history.average,values.reduce((a,b)=>a+b,0)/values.length);assert.equal(backyardIndexTimeline(rounds,"other").points.length,0);});
function server(admin:any,viewer:any=admin){const exports:any={};runInNewContext(ts.transpileModule(readFileSync("lib/career-attest.server.ts","utf8"),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports,require(id:string){if(id==="server-only")return{};if(id.endsWith("social-round-card"))return roundCards;if(id.endsWith("round-achievements"))return achievements;if(id.endsWith("career-index-presentation"))return presentation;throw Error(id);}});return(account:string)=>exports.readCareerAttest(admin,account,viewer);}
test("private attest read scopes ownership and links to authenticated account",async()=>{const round=careerRound("local",1);round.completedAt=`${round.date}T18:00:00Z`;const source={id:"canonical",owner_id:"owner",local_round_id:round.id,version:2,snapshot:round};const queries:any[]=[];const admin={from(table:string){const filters:any[]=[];const q:any={select(){return q;},eq(k:string,v:any){filters.push([k,v]);return q;},in(k:string,v:any){filters.push([k,v]);return q;},order(){return q;},limit(){return q;},then(resolve:any){queries.push({table,filters});return Promise.resolve({data:table==="rounds_cloud"?[source]:[],error:null}).then(resolve);}};return q;}};const result=await server(admin)("owner");assert.equal(result.cards.length,1);assert.equal(result.cards[0].roundId,"local");assert.equal(result.percent,0);assert.ok(queries.some(q=>q.table==="rounds_cloud"&&q.filters.some(([k,v]:any)=>k==="owner_id"&&v==="owner")));assert.ok(queries.some(q=>q.table==="social_round_account_links_v3"&&q.filters.some(([k,v]:any)=>k==="user_id"&&v==="owner")));const unrelated=await server(admin)("unrelated");assert.equal(unrelated.cards.length,0);});
test("attest API rejects unauthenticated clients and never trusts client profile filters",()=>{const source=readFileSync("app/api/career/attest/route.ts","utf8");assert.match(source,/authenticatedRequest\(request\)/);assert.match(source,/if\(!account.ok\)return/);assert.match(source,/readCareerAttest\(admin,account.userId,account.client\)/);assert.match(source,/private, no-store/);assert.doesNotMatch(source,/searchParams|request.json|request.body/);});
test("Atest reads received evidence through authenticated RLS without additional service grants",async()=>{
  const round=careerRound("own-local",1);round.completedAt=`${round.date}T18:00:00Z`;
  const hash=await achievements.roundMaterialFingerprint(round,"owner");
  const row={id:"canonical",owner_id:"owner",local_round_id:round.id,version:2,snapshot:round};
  const query=(data:unknown[])=>{const q:any={select(){return q;},eq(){return q;},in(){return q;},order(){return q;},limit(){return q;},then(resolve:any){return Promise.resolve({data,error:null}).then(resolve);}};return q;};
  const admin={from(table:string){assert.notEqual(table,"social_round_attestations_v3","service role has no attest SELECT");return query(table==="rounds_cloud"?[row]:[]);}};
  const viewer={from(table:string){assert.equal(table,"social_round_attestations_v3");return query([{round_id:row.id,target_user_id:"owner",attester_id:"peer",expected_hash:hash,expected_version:2}]);}};
  const result=await server(admin,viewer)("owner");assert.equal(result.percent,5);assert.equal(result.cards[0].attested,true);
});
const props={displayName:"QA Owner",userId:"owner",accessToken:"qa-token",index:{source:"BACKYARD",value:8,reason:"test"},rounds:[],history:[],insights:buildGolfInsights([]),ready:true,view:"summary",onOpenRound(){}};
function panel(summary=careerAttestSummary(cards(),evidence(),"owner")){const opened:string[]=[];const h=socialUI("app/components/career-index-panel.tsx",{"career-index-presentation":presentation,"backyard-index":{calculateBackyardIndex},"career-attest-client":{readCareerAttestSummary:async()=>summary},"career-statistics":{careerDate:(s:string)=>s,careerNumber:(n:number|null)=>n??"—"}});return{h,opened,render:(detail:string|null=null)=>h.render("CareerIndexPanel",{props:{...props,onOpenRound:(id:string)=>opened.push(id)},detail,onDetail(){}})};}
test("last-20 detail renders persisted scores, statuses and 20 dots, and opens canonical history",async()=>{const p=panel();p.render("attest");await settleUI();const tree=p.render("attest");assert.match(uiText(tree),/Tus últimas 20 tarjetas[\s\S]*85%[\s\S]*17\/20/);assert.equal(uiNodes(tree).filter(n=>n.type==="i").length,20);assert.equal(uiNodes(tree).filter(n=>n.type==="button"&&n.props.className==="row").length,20);uiFind(tree,n=>n.type==="button"&&n.props.className==="row").props.onClick();assert.equal(p.opened[0],"r-00");});
test("index detail has correct source and honest insufficient history without official branding or percentile",()=>{const p=panel(),tree=p.render("index");assert.match(uiText(tree),/BACKYARD INDEX[\s\S]*Índice local calculado/);assert.match(uiText(tree),/Aún no tenemos suficiente historial/);assert.doesNotMatch(uiText(tree),/USGA|DATA AFFILIATE|Mejor que|78%/);});
test("Career preserves all five sections, statistics, history and trophy actions",()=>{const source=readFileSync("app/components/career-hub.tsx","utf8");for(const name of ["CareerOverview","CareerAchievements","CareerRivalries","CareerRounds","CareerTournaments","CareerTabs"])assert.match(source,new RegExp(name));assert.match(source,/CareerIndexPanel/);assert.doesNotMatch(source,/Feed|FriendsHub|Agregar amigos/);});
