import assert from "node:assert/strict";
import test from "node:test";
import { readFileSync } from "node:fs";
import * as navigation from "../lib/home-social-navigation";
import * as feed from "../lib/social-feed-presentation";
import { socialUI,uiFind,uiNodes,uiText,settleUI } from "./helpers/social-ui";
import type { SocialActivityCard } from "../lib/social-activity-contract";
export function socialCard(id="card-1"):SocialActivityCard{return{id,type:"ROUND_COMPLETED",audience:"FRIENDS",author:{userId:"peer",displayName:"QA Peer",username:"qa_peer",avatarUrl:null},createdAt:"2026-10-05T12:00:00Z",sourceVersion:1,currentHash:"hash-1",roundId:`round-${id}`,round:{roundId:`round-${id}`,localRoundId:id,date:"2026-10-05",courseName:"Campo QA",teeName:null,holesPlayed:18,ownerScore:72,coursePar:72},achievements:[],likesCount:0,likedByMe:false,commentsCount:0,attestCount:0,isAttestedByMe:false,canAttest:false,requiresParticipantConfirmation:false,participantPlayerKey:null,targetUserId:"peer"};}
const homeProps={displayName:"QA Owner",identityUserId:"owner",username:"qa_owner",accessToken:"qa-token",onOpenAchievements(){},onOpenRounds(){},onOpenFriends(){},onPrivacy(){}};
test("Inicio resumes only a real live round through the account-owned navigation callback",()=>{
  const h=socialUI("app/components/home-dashboard.tsx",{"home-social-navigation":navigation});let resumed=0;
  const activeRound={status:"live",courseName:"Campo de la ronda",totalHoles:18,currentHole:2,playerCount:3,roundDate:"2026-10-05"};
  let tree=h.render("HomeDashboard",{...homeProps,activeRound,onContinueRound:()=>{resumed++;}});
  const button=uiFind(tree,n=>n.type==="button"&&uiText(n).startsWith("Continuar ronda"));
  assert.match(uiText(button),/Campo de la ronda · Hoyo 2 de 18/);button.props.onClick();assert.equal(resumed,1);
  for(const unavailable of [null,{...activeRound,status:"setup"},{...activeRound,status:"review"}]) {
    tree=h.render("HomeDashboard",{...homeProps,activeRound:unavailable,onContinueRound:()=>{resumed++;}});
    assert.doesNotMatch(uiText(tree),/Continuar ronda/);
  }
  tree=h.render("HomeDashboard",{...homeProps,activeRound});assert.doesNotMatch(uiText(tree),/Continuar ronda/);
  const page=readFileSync("app/page.tsx","utf8");assert.match(page,/activeRound=\{globalRoundAvailable \? activeRoundSummary : null\}/);assert.match(page,/onContinueRound=\{globalRoundAvailable \? resumeActiveRound : undefined\}/);
});
for(const view of navigation.HOME_SOCIAL_VIEWS)test(`Inicio keeps social ${view} within Inicio and preserves history`,()=>{
  const h=socialUI("app/components/home-dashboard.tsx",{"home-social-navigation":navigation,"cloud-social-activity":{CloudSocialActivity:"Feed"},"social-connections-panel":{FriendsHub:"FriendsHub"}});
  let tree=h.render("HomeDashboard",homeProps);assert.equal(uiFind(tree,n=>n.props["aria-current"]==="page").props.children,"Feed");
  const labels={feed:"Feed",friends:"Amigos","add-friends":"Agregar amigos"};uiFind(tree,n=>n.type==="button"&&uiText(n)===labels[view]).props.onClick();tree=h.render("HomeDashboard",homeProps);
  assert.equal(uiFind(tree,n=>n.props["aria-current"]==="page").props.children,labels[view]);assert.equal(h.window.history.state.backyardTab,"welcome");assert.equal(navigation.homeSocialViewFromSearch(h.location.search),view);
  assert.doesNotMatch(uiText(tree),/Qué estás compartiendo|Actualizar feed|Qué comparto|Encuesta/);
});
test("Inicio direct reload and browser Back restore social subview",()=>{const h=socialUI("app/components/home-dashboard.tsx",{"home-social-navigation":navigation});h.location.search="?home=add-friends";h.render("HomeDashboard",homeProps);let tree=h.render("HomeDashboard",homeProps);assert.equal(uiFind(tree,n=>n.props["aria-current"]==="page").props.children,"Agregar amigos");h.location.search="?home=friends";h.emit("popstate");tree=h.render("HomeDashboard",homeProps);assert.equal(uiFind(tree,n=>n.props["aria-current"]==="page").props.children,"Amigos");});
test("normal Inicio return clears the completed friend-profile entry and defaults to Feed",()=>{const h=socialUI("app/components/home-dashboard.tsx",{"home-social-navigation":navigation});h.render("HomeDashboard",{...homeProps,friendsEntry:1,targetId:"peer"});let tree=h.render("HomeDashboard",{...homeProps,friendsEntry:1,targetId:"peer"});assert.equal(uiFind(tree,n=>n.props["aria-current"]==="page").props.children,"Amigos");h.location.search="";h.render("HomeDashboard",{...homeProps,friendsEntry:0,targetId:null});tree=h.render("HomeDashboard",{...homeProps,friendsEntry:0,targetId:null});assert.equal(uiFind(tree,n=>n.props["aria-current"]==="page").props.children,"Feed");assert.match(readFileSync("app/page.tsx","utf8"),/targetId=\{tab === "friends" \? socialTarget : null\}/);});
function feedSetup(){const calls:string[]=[];let release:(data:any)=>void=()=>{};let deferred=false;const request=async(path:string)=>{calls.push(path);if(deferred)return new Promise(resolve=>{release=resolve;});return{data:[socialCard(path.includes("cursor")?"card-2":"card-1")],nextCursor:path.includes("cursor")?null:"cursor-1"};};const h=socialUI("app/components/cloud-social-activity.tsx",{"social-feed-presentation":feed,"social-activity-client":{socialRequest:request,socialErrorMessage:String}});const props={viewerId:"owner",accessToken:"qa-token",friendsOnly:true};return{h,calls,render:()=>h.render("CloudSocialActivity",props),defer(){deferred=true;},release(){release({data:[socialCard()],nextCursor:null});}};}
test("infinite feed requests one next page and retains previous cards without duplicates",async()=>{const s=feedSetup();s.render();await settleUI();s.render();s.h.intersect();s.h.intersect();await settleUI();const tree=s.render();assert.equal(s.calls.length,2);assert.match(s.calls[1],/friendsOnly=true&cursor=cursor-1/);assert.equal(uiNodes(tree).filter(n=>typeof n.type==="function"&&n.type.name==="SocialRoundActivityCard").length,2);assert.doesNotMatch(uiText(tree),/Ver más actividad|Actualizar feed/);});
test("pull refresh crosses threshold once; pending refresh blocks duplicate pulls",async()=>{const s=feedSetup();s.render();await settleUI();s.render();s.defer();const touch=(y:number)=>({touches:[{clientY:y,clientX:10}],cancelable:true,preventDefault(){}});s.h.emit("touchstart",touch(0));s.h.emit("touchmove",touch(140));s.h.emit("touchend");s.h.emit("touchend");s.h.emit("touchstart",touch(0));s.h.emit("touchmove",touch(140));s.h.emit("touchend");assert.equal(s.calls.length,2);s.release();await settleUI();s.render();});
test("pull below threshold and below scroll top never refreshes",async()=>{const s=feedSetup();s.render();await settleUI();s.render();const touch=(y:number)=>({touches:[{clientY:y,clientX:0}],preventDefault(){}});s.h.emit("touchstart",touch(0));s.h.emit("touchmove",touch(30));s.h.emit("touchend");s.h.window.scrollY=30;s.h.emit("touchstart",touch(0));s.h.emit("touchmove",touch(200));s.h.emit("touchend");assert.equal(s.calls.length,1);});
test("foreground refresh shares the request guard",async()=>{const s=feedSetup();s.render();await settleUI();s.render();s.defer();s.h.emit("visibilitychange");s.h.emit("pageshow");assert.equal(s.calls.length,2);s.release();await settleUI();s.h.unmount();});
function cardUI(card= socialCard()){const calls:any[]=[];let refreshed=0;const comments=[{id:"own-comment",author:{userId:"owner",displayName:"QA Owner"},text:"Comentario propio"},{id:"other-comment",author:{userId:"peer",displayName:"QA Peer"},text:"Comentario ajeno"}];const h=socialUI("app/components/cloud-social-activity.tsx",{"social-feed-presentation":feed,"social-activity-client":{socialRequest:async(path:string,_token:string,init:any)=>{calls.push({path,init});return{data:path.endsWith("/comments")&&!init?comments:card};},socialErrorMessage:String}});return{h,calls,render:()=>h.render("SocialRoundActivityCard",{card,viewerId:"owner",accessToken:"qa-token",onRefresh:async()=>{refreshed++;}}),refreshed:()=>refreshed};}
test("normal round stays sober even with low score; unknown stats are absent",()=>{const c=socialCard();c.round!.ownerScore=65;const s=cardUI(c);const tree=s.render();assert.doesNotMatch(tree.props.className,/highlight/);assert.doesNotMatch(uiText(tree),/Putts|GIR|FIR|Récord/);assert.match(uiText(tree),/Score 65/);});
test("only persisted achievement evidence highlights a round, capped at four",()=>{const c=socialCard();c.achievements=["Mejor score","Birdie Club","Best Back 9","Par Master","Otro logro"];const tree=cardUI(c).render();assert.match(tree.props.className,/highlight/);assert.doesNotMatch(uiText(tree),/Otro logro/);assert.match(uiText(tree),/Mejor score/);});
test("actual captured stats and authorized leaderboard render without financial data",()=>{const c=socialCard();Object.assign(c.round!,{putts:32,girPct:50,firPct:70,toPar:0,leaderboard:[{userId:"peer",name:"QA Peer",avatarUrl:null,score:72,holes:18},{userId:"owner",name:"QA Owner",avatarUrl:null,score:76,holes:18}]});const tree=cardUI(c).render();assert.match(uiText(tree),/Putts 32 GIR 50\s*% FIR 70\s*%/);assert.match(uiText(tree),/2 jugadores · Score bruto/);assert.match(uiText(tree),/Ver resultados/);assert.doesNotMatch(uiText(tree),/dinero|balance|apuesta|\$/i);});
test("equipment card uses actual summary and avoids invented product photographs",()=>{const c=socialCard();c.type="EQUIPMENT_UPDATED";c.round=null;c.roundId=null;c.equipment={items:[{id:"driver",category:"Driver",brand:"QA Catalog",model:"QA Model"}],total:1};const tree=cardUI(c).render();assert.match(uiText(tree),/Mi bolsa de golf[\s\S]*QA Catalog QA Model/);assert.doesNotMatch(uiText(tree),/TaylorMade|Titleist|P790/);});
test("likes use canonical hash and refresh only this card",async()=>{const s=cardUI();let tree=s.render();uiFind(tree,n=>n.type==="button"&&uiText(n).includes("Me gusta")).props.onClick();await settleUI();tree=s.render();assert.equal(s.calls[0].init.method,"POST");assert.equal(s.calls[0].init.body.expectedHash,"hash-1");assert.equal(s.refreshed(),1);assert.doesNotMatch(uiText(tree),/Compartir/);});
test("comments are lazy and inline; only author has edit/delete actions",async()=>{const s=cardUI();let tree=s.render();assert.equal(s.calls.length,0);uiFind(tree,n=>n.type==="button"&&uiText(n).startsWith("Comentar")).props.onClick();await settleUI();tree=s.render();assert.equal(s.calls.length,1);assert.match(s.calls[0].path,/\/comments$/);assert.match(uiText(tree),/Comentario propio[\s\S]*Comentario ajeno/);assert.equal(uiNodes(tree).filter(n=>n.type==="button"&&uiText(n)==="Editar").length,1);assert.equal(uiNodes(tree).filter(n=>n.type==="button"&&uiText(n)==="Eliminar").length,1);assert.ok(uiNodes(tree).some(n=>n.type==="textarea"&&n.props.placeholder==="Escribe un comentario…"));});
test("comment submit uses existing API and does not reload the whole feed",async()=>{const s=cardUI();let tree=s.render();uiFind(tree,n=>n.type==="button"&&uiText(n).startsWith("Comentar")).props.onClick();await settleUI();tree=s.render();uiFind(tree,n=>n.type==="textarea").props.onChange({target:{value:"  Buena ronda QA  "}});tree=s.render();uiFind(tree,n=>n.type==="form").props.onSubmit({preventDefault(){}});await settleUI();assert.ok(s.calls.some(c=>c.init?.method==="POST"&&c.init.body.text==="Buena ronda QA"&&c.path.endsWith("/comments")));assert.equal(s.refreshed(),1);});
test("scorecard opens the actual resource and displays only captured holes",async()=>{const c=socialCard();c.round!.scorecard=[{hole:1,par:4,score:4}];const s=cardUI(c);let tree=s.render();uiFind(tree,n=>n.type==="button"&&uiText(n)==="Ver scorecard").props.onClick();await settleUI();tree=s.render();assert.equal(s.calls[0].path,"/api/social/activity/card-1");assert.match(uiText(tree),/Tarjeta guardada[\s\S]*Hoyo Par Score 1 4 4/);});
test("bottom navigation and protected modules remain the existing shell",()=>{const page=readFileSync("app/page.tsx","utf8");assert.match(page,/tab === "welcome" \|\| tab === "friends"/);assert.match(page,/onOpenRound=\{openHistoricalRound\}/);const nav=readFileSync("app/components/app-bottom-nav.tsx","utf8");assert.match(nav,/Inicio/);assert.match(nav,/Carrera/);assert.match(nav,/My Coach/);assert.match(readFileSync("lib/app-navigation.ts","utf8"),/Reglas/);assert.doesNotMatch(nav,/Agregar amigos/);});
