import assert from "node:assert/strict";
import test from "node:test";
import { readFileSync } from "node:fs";
import * as scorecard from "../lib/golf-scorecard-presentation";
import { safeSocialRoundCard } from "../lib/social-round-card";
import {participantCard} from "../lib/shared-round-participants";
import { careerRound } from "./helpers/career-round";
import { socialUI, uiFind, uiNodes } from "./helpers/social-ui";
for(const [score,result]of [[1,"eagle"],[2,"eagle"],[3,"birdie"],[4,"par"],[5,"bogey"],[6,"double"],[10,"double"],[null,"missing"]] as const)test(`score ${score} against par 4 communicates ${result} with a label and shape`,()=>{
  assert.equal(scorecard.scoreResult(score,4),result);const h=socialUI("app/components/premium-scorecard.tsx",{"golf-scorecard-presentation":scorecard});const symbol=h.render("ScoreSymbol",{score,par:4});assert.equal(symbol.props["data-score-result"],result);assert.match(symbol.props["aria-label"],new RegExp(scorecard.scoreResultLabel[result]));assert.match(symbol.props.className,new RegExp(result));
});
test("scorecard totals preserve front/back/total and refuse absent scores or putts",()=>{const holes=Array.from({length:18},(_,i)=>({hole:i+1,par:4,score:i<9?4:5,putts:2}));assert.deepEqual(scorecard.scorecardTotals(holes.slice(0,9)),{par:36,score:36,toPar:0,putts:18});assert.deepEqual(scorecard.scorecardTotals(holes.slice(9)),{par:36,score:45,toPar:9,putts:18});assert.deepEqual(scorecard.scorecardTotals(holes),{par:72,score:81,toPar:9,putts:36});assert.equal(scorecard.scorecardTotals([{hole:1,par:4,score:null}]).score,null);assert.equal(scorecard.scorecardTotals([{hole:1,par:4,score:4}]).putts,null);assert.equal(scorecard.scorecardTotals([]).score,null);});
test("each captured hole has a semantic dedicated-destination button",()=>{let selected=0;const h=socialUI("app/components/premium-scorecard.tsx",{"golf-scorecard-presentation":scorecard});const tree=h.render("PremiumScorecard",{holes:[{hole:7,par:4,score:3}],onHole:(n:number)=>selected=n});uiFind(tree,n=>n.type==="button"&&n.props["aria-label"]==="Abrir hoyo 7 · Birdie").props.onClick();assert.equal(selected,7);assert.equal(uiNodes(tree).filter(n=>n.type==="li").length,1);const css=readFileSync("app/components/golf-object.module.css","utf8");assert.match(css,/\.eagle:after/);assert.match(css,/\.double:after/);assert.match(css,/\.birdie\{border-radius:50%/);assert.match(css,/\.bogey\{border-radius:2px/);});
test("social hole projection retains authorized captured facts and excludes private coordinates and peers",()=>{const r=careerRound("qa",1);r.putts={1:{"owner-player":2,"rival-player":9}};r.advancedStats={1:{"owner-player":{greenInRegulation:true,fairwayHit:false,penaltyStrokes:1}}};r.courseSnapshot!.holes[0].yards=333;r.resultDetails={privateNotes:"secret"};const card=safeSocialRoundCard({id:"canonical",local_round_id:r.id,snapshot:r},"owner",true,false)!;assert.equal(card.scorecard![0].putts,2);assert.equal(card.scorecard![0].greenInRegulation,true);assert.equal(card.scorecard![0].fairwayHit,false);assert.equal(card.scorecard![0].penaltyStrokes,1);assert.equal(card.scorecard![0].yards,undefined);assert.equal(card.putts,undefined);assert.equal(card.girPct,undefined);assert.doesNotMatch(JSON.stringify(card),/secret|rival-player|latitude|longitude|GHIN|attestCount/);});
test("private participant symbols use their actual par and never guess a missing definition",()=>{const r=careerRound("qa",1);const owner="11111111-1111-4111-8111-111111111111",peer="22222222-2222-4222-8222-222222222222";r.players![0].accountUserId=owner;r.players![1].accountUserId=peer;r.completedAt="2026-09-01T12:00:00Z";const card=participantCard("round",owner,1,"hash",r,peer,new Set());assert.equal(card.myScorecard![0].score,5);assert.equal(card.myScorecard![0].par,4);assert.equal(scorecard.scoreResult(card.myScorecard![0].score,card.myScorecard![0].par),"bogey");delete r.courseSnapshot;assert.equal(participantCard("round",owner,1,"hash",r,peer,new Set()).myScorecard,undefined);});
