export const PRIVACY_LEGAL_VERSION = "2026-09-08-v6";
export const TERMS_LEGAL_VERSION = "2026-09-08-v2";
export const LEGAL_EFFECTIVE_DATE = "8 de septiembre de 2026";

export const LEGAL_SOURCE_HASHES = {
  privacyDocx: "0276488379564c88ff21cfee4419e56a4e47b096525d12b52e90378e55dd2b03",
  privacyTxt: "4c8e197b62d945278573f6b476847452772839ef5245ecf51b9a3017079814c4",
  privacyPublished: "c441091d44899e8b84e6dff1edd68e99cf377c60ddf9c824ff046a9a8aa78780",
  termsDocx: "bf90778176418bd02e7911a1484578a52c7a48a8625489c2299377d40d4e8d4c",
  termsTxt: "ddd3140b246d84beeb3ef312d4ce89d4a3e248f7d4eb473e4c61eed008d6aa9d",
  termsPublished: "cf401c0d71d0cbb79e859538dda41f433e8959d8cfbab6ddf3d22d7a20fb461f",
  privacySimplified: "3bc90c113d94b41886901ff4f06a102dc1003e1d48fb2d3797739e32ac370eee",
} as const;

export const PRIVACY_INTEGRAL_TEXT = [
  "Aviso de Privacidad Integral",
  "",
  "2026-09-08-v6  |  8 de septiembre de 2026",
  "",
  "Responsable actual: Said Abaid Taja",
  "",
  "Texto consolidado. Aplicable a partir de su publicación y presentación en el flujo correspondiente. La actualización documental no acredita por sí sola autorización regulatoria ni implementación técnica.",
  "",
  "1. Responsable y contacto",
  "",
  "Said Abaid Taja, persona física que opera el servicio identificado comercialmente como The Backyard, es responsable del tratamiento de los datos personales descritos en este Aviso durante la etapa actual de pruebas y desarrollo.",
  "",
  "Domicilio: Calle 1 Retorno Osa Menor, Número Exterior 2, Interior 1003, Colonia Reserva Territorial Atlixcáyotl, Localidad San Bernardino Tlaxcalancingo, Municipio San Andrés Cholula, Puebla, C.P. 72820, México. Referencia: Periférico Ecológico.",
  "",
  "Privacidad y derechos ARCO: privacidad@thebackyard.com.mx. Soporte: soporte@thebackyard.com.mx. Sitio: https://thebackyard.com.mx. Aplicación web: https://app.thebackyard.com.mx.",
  "",
  "La etapa de pruebas y la ausencia de cobro no eliminan las obligaciones de protección de datos. Si la operación pasa a una sociedad, se informará la identidad del nuevo responsable y se atenderán las obligaciones aplicables al cambio y a la comunicación de los datos; no se presume una sustitución retroactiva de responsabilidades.",
  "",
  "2. Alcance y funciones disponibles",
  "",
  "Este Aviso comprende el sitio informativo, la aplicación web y su acceso desde la pantalla de inicio del dispositivo, el soporte y los servicios conectados de The Backyard. Las finalidades opcionales únicamente se aplican a las funciones efectivamente disponibles que la persona decida utilizar.",
  "",
  "La prueba actual no supone una contratación de pago. Las referencias a suscripciones, facturación, Apple, GHIN, GPS u otras integraciones futuras no significan que estén activas ni autorizan a recolectar anticipadamente esos datos. Antes de incorporarlas se informarán sus condiciones, proveedores y tratamientos y se recabarán los consentimientos y permisos que correspondan.",
  "",
  "3. Categorías de datos personales",
  "",
  "Identificación y contacto: nombre o alias, correo electrónico, imagen de perfil cuando se aporte, idioma y preferencias; teléfono únicamente si se proporciona para soporte o una función informada. La declaración de mayoría de edad, cuando se recabe, no incluye por sí misma una comprobación documental.",
  "",
  "Cuenta y acceso: identificador de usuario, método de autenticación, identificadores que entregue el proveedor elegido, datos de sesión y registros de acceso. El acceso mediante Google no requiere que entregues a The Backyard tu contraseña de Google.",
  "",
  "Actividad deportiva: handicap/HCP, scores, tees, par, ventajas por hoyo, campos, fechas, rondas, jugadores, grupos, torneos, clasificaciones, estadísticas e históricos. Los valores de course rating y slope pueden asociarse a tus rondas.",
  "",
  "Registros financieros o patrimoniales: participantes de un juego, reglas elegidas, importes, presiones, resultados económicos calculados, saldos y gastos capturados. Son anotaciones y cálculos; no representan fondos depositados en The Backyard.",
  "",
  "Contenido y asistencia: fotografías de tarjetas, imágenes de situaciones de reglas cuando se habilite su análisis, archivos seleccionados, consultas a IA, reportes, mensajes a soporte y comentarios que envíes.",
  "",
  "Datos técnicos: IP, navegador, sistema operativo, identificadores de sesión o dispositivo cuando estén disponibles, fecha y hora, versión de la aplicación, registros de errores y seguridad, rendimiento y eventos de uso necesarios para operación y diagnóstico. Las métricas adicionales identificables no indispensables y la analítica comercial se sujetan a la sección de finalidades opcionales.",
  "",
  "Evidencia de elecciones: versión del texto presentado, fecha, hora, cuenta o identificador de sesión y manifestaciones de aceptación, rechazo o revocación, en la medida en que se recaben para acreditar esas decisiones.",
  "",
  "4. Datos sensibles, ubicación e integraciones futuras",
  "",
  "No solicitamos deliberadamente datos sensibles sobre salud, religión, origen étnico, opiniones políticas, vida sexual o biometría de identificación. Los resultados deportivos no son por sí solos datos sensibles, pero fotografías o textos pueden revelar información sensible: evita incorporarla, en especial sobre terceros.",
  "",
  "El sitio informativo no solicita GPS. Una función de ubicación precisa en la app deberá explicar su finalidad y solicitar el permiso correspondiente antes de acceder a ella; la IP puede permitir una ubicación aproximada. Este Aviso no autoriza seguimiento permanente o en segundo plano.",
  "",
  "La vinculación futura con GHIN, federaciones o clubes requerirá una integración autorizada y la información previa pertinente. Los identificadores y datos obtenidos no se recabarán por extracción no autorizada de cuentas de terceros.",
  "",
  "Si se habilitan suscripciones, se informarán los datos de plan, compra, renovación, cancelación y facturación necesarios. Los pagos deberán gestionarse mediante el procesador identificado en la compra; no solicitamos datos completos de tarjeta ni códigos de seguridad por correo, chat o campos libres de la app.",
  "",
  "5. Fuentes de obtención y datos de otros jugadores",
  "",
  "Los datos pueden provenir de ti, de tu navegador o dispositivo, del proveedor de acceso que elijas, de integraciones que autorices y de jugadores o administradores que capturen información de una ronda en la que participas.",
  "",
  "Quien capture datos ajenos debe limitarse a información necesaria y contar con autorización o base jurídica aplicable. Un administrador no puede otorgar por otros jugadores el consentimiento financiero, publicitario o de publicación que deba recabarse de cada titular. No se autoriza cargar agendas, documentos de identidad o históricos privados completos de otras personas.",
  "",
  "Cuando recibamos datos de una persona por un tercero, pondremos a su disposición el aviso y atenderemos los requisitos de información y consentimiento aplicables. El registro por un compañero no elimina los derechos del titular.",
  "",
  "6. Finalidades primarias",
  "",
  "Tratamos los datos necesarios para autenticar y administrar cuentas; mantener perfiles; registrar rondas y scores; configurar jugadores y grupos; calcular resultados deportivos y estadísticas; conservar el histórico elegido; y prestar las funciones compartidas de torneo, captura y clasificación disponibles.",
  "",
  "También se utilizan para responder consultas de reglas o procesar contenido solicitado mediante IA; sincronizar y almacenar información cuando se utilice la nube; prestar soporte y corregir errores; proteger cuentas y prevenir abuso; atender solicitudes de privacidad y requerimientos legales; y acreditar consentimientos y operaciones.",
  "",
  "El registro y cálculo de importes de juegos entre participantes es una finalidad opcional vinculada a ese módulo y exige el consentimiento indicado en la sección siguiente. Las finalidades primarias no constituyen una excepción general a los requisitos legales de consentimiento.",
  "",
  "7. Consentimiento financiero o patrimonial",
  "",
  "Los registros de apuestas, resultados económicos, saldos y gastos se tratarán como información financiera o patrimonial para recabar consentimiento expreso, salvo que una excepción legal concreta resulte aplicable. La autorización debe obtenerse antes del tratamiento correspondiente mediante una elección afirmativa separada, no premarcada, o un medio equivalente válido.",
  "",
  "La autorización comprende calcular, mostrar y conservar los datos pertinentes y comunicarlos a los participantes de esa misma dinámica, conforme a su alcance y a la sección de visibilidad. No autoriza publicar el historial económico de la persona ni compartirlo con todos los miembros de un club o torneo.",
  "",
  "Rechazar o revocar esa autorización impide el tratamiento opcional que dependa de ella, no el uso de funciones deportivas que puedan prestarse sin esos datos. No basta aceptar en bloque los Términos, instalar la app o que otro jugador marque una casilla por ti.",
  "",
  "The Backyard no recibe, custodia ni transfiere dinero apostado entre usuarios ni garantiza su pago. Este Aviso regula datos personales: no certifica la licitud ni la exigibilidad de los acuerdos registrados.",
  "",
  "8. Finalidades secundarias y elección de marketing",
  "",
  "Las promociones, ofertas comerciales, encuestas de marketing y comunicaciones publicitarias requieren una elección separada y opcional. La negativa no condiciona el acceso a funciones principales. No incluimos la autorización publicitaria dentro del consentimiento financiero.",
  "",
  "Puedes negar o retirar estas finalidades desde su presentación, mediante la baja incluida en los mensajes cuando corresponda o escribiendo a privacidad@thebackyard.com.mx, con el asunto “Limitar uso / marketing”. Usaremos la cuenta y el alcance de tu solicitud para tramitarla. No es necesario esperar a recibir publicidad para oponerte.",
  "",
  "No vendemos bases de datos de usuarios. La incorporación de publicidad personalizada, seguimiento entre servicios o analítica no indispensable requerirá información específica y las elecciones legalmente exigibles antes de su activación.",
  "",
  "9. Visibilidad en rondas, grupos y Polla Live",
  "",
  "Rondas y grupos compartidos. Los participantes, capturistas o administradores autorizados pueden conocer nombre o alias, HCP, scores, datos de la ronda y resultados necesarios para coordinar el juego y revisar la clasificación. La pertenencia a un grupo no concede acceso automático a todo tu histórico personal.",
  "",
  "Importes y gastos. La visibilidad de resultados económicos se limita a quienes intervengan en esa apuesta o acuerdo y a los administradores expresamente autorizados cuando sea necesario. Los gastos personales no se comparten por el solo hecho de participar en un torneo.",
  "",
  "Clasificación pública de Polla Live. Si el organizador habilita y comparte un leaderboard público, personas ajenas al grupo que tengan su enlace o código pueden consultar datos deportivos como nombre o alias, HCP, scores, posición, campo y resultados de Oyes. Un enlace o código público no equivale a una sesión privada. La publicación debe informarse previamente a los participantes y contar con la base jurídica correspondiente; cuando se requiera consentimiento, deberá recabarse de cada titular.",
  "",
  "La clasificación deportiva pública no autoriza divulgar saldos, apuestas privadas, gastos personales, correos ni credenciales. La captura y administración del evento no deben confundirse con el permiso de visualización pública.",
  "",
  "Quien exporta o comparte una tarjeta o captura debe verificar su contenido y destinatarios. Los receptores pueden conservar copias fuera del control técnico del servicio; esto no elimina las obligaciones de The Backyard respecto de las copias que controla. Puedes solicitar limitación, corrección o eliminación en privacidad@thebackyard.com.mx.",
  "",
  "10. IA: tratamiento, entrenamiento y límites",
  "",
  "Cuando utilizas una función de IA, el texto, las imágenes elegidas y el contexto pertinente pueden enviarse al proveedor de esa función. Se limitará el envío a lo necesario: no procede remitir tu histórico económico completo, credenciales o datos de otros jugadores si no son necesarios para la consulta. Revisa lo que escribes y los datos visibles en una fotografía.",
  "",
  "En el servicio API de OpenAI, las entradas y salidas no se utilizan por defecto para entrenar modelos del proveedor; su documentación contempla opciones voluntarias de participación. The Backyard no autoriza mediante este Aviso el entrenamiento de modelos generales con datos personales de sus usuarios. Cualquier cambio en esa finalidad requeriría información previa y una base jurídica válida y, cuando corresponda, consentimiento adicional.",
  "",
  "No usar datos para entrenamiento no significa ausencia de almacenamiento: el proveedor puede conservar contenidos o registros para prestar la función, seguridad o cumplimiento, según el servicio, contrato y controles aplicables. No prometemos retención cero ni borrado instantáneo por parte de todos los proveedores.",
  "",
  "Las respuestas y extracciones mediante IA pueden ser inexactas. Revisa scores, nombres e importes detectados antes de confirmarlos. Los Términos explican el alcance informativo del asistente y de los cálculos.",
  "",
  "11. Proveedores y comunicaciones de datos",
  "",
  "Podemos utilizar Netlify para el sitio informativo, Vercel para la aplicación, Supabase para autenticación, base de datos o archivos y OpenAI para IA. Cada proveedor recibe únicamente los datos necesarios para la función utilizada, dentro de la arquitectura efectivamente contratada.",
  "",
  "Los servicios que procesan datos por nuestra cuenta se sujetan a instrucciones, obligaciones de confidencialidad y condiciones de seguridad aplicables. No se confunde esa relación con una transferencia a un responsable independiente.",
  "",
  "Google, al utilizar su acceso, y otros servicios independientes que vincules pueden realizar tratamientos propios bajo sus avisos. Antes de una nueva integración que implique comunicación de datos se identificará su finalidad y se obtendrá la autorización exigible. Apple, proveedores de pagos, GHIN y federaciones no se presentan como integraciones ya activas por su sola mención en este documento.",
  "",
  "Las imágenes o recursos externos del sitio, cuando se carguen desde GitHub o Unsplash, pueden comunicar al servidor que los entrega la IP y datos técnicos de la solicitud. Los enlaces a redes sociales dirigen a servicios independientes. No equivalen a una autorización para entregarles tu historial de rondas o económico.",
  "",
  "12. Procesamiento internacional y transferencias",
  "",
  "El tratamiento tecnológico puede realizarse fuera de México, incluyendo Estados Unidos y otras jurisdicciones donde operen los proveedores o sus subencargados. La región de la base de datos no determina por sí sola la ubicación de todos los registros, respaldos o servicios de soporte.",
  "",
  "Las comunicaciones a participantes o administradores, la publicación deportiva autorizada y las integraciones independientes tendrán el alcance descrito en este Aviso. Las transferencias que requieran consentimiento se someterán a una elección previa y específica; el consentimiento financiero cubrirá sólo los destinatarios y datos expresamente informados. No existe autorización general para cualquier tercero o país.",
  "",
  "Podremos comunicar los datos estrictamente exigidos por un requerimiento válido de autoridad o una excepción legal aplicable. No se pide renunciar a tus derechos ni aceptar una transferencia que legalmente puedas rechazar. La información transferida quedará sujeta a las obligaciones que resulten aplicables al receptor.",
  "",
  "13. Permisos, cookies y almacenamiento local",
  "",
  "La aplicación puede usar cookies técnicas, localStorage, IndexedDB u otras tecnologías para sesión, autosave, rondas, preferencias, imágenes y datos guardados en el dispositivo. Puedes administrarlas desde el navegador; bloquearlas o borrarlas puede cerrar tu sesión o eliminar información local.",
  "",
  "El sitio informativo incluido en esta versión no incorpora formularios de registro, píxeles publicitarios ni cookies publicitarias propias. El alojamiento y las solicitudes de recursos pueden generar registros técnicos. La aplicación y las páginas de terceros tienen sus propios flujos descritos cuando corresponda.",
  "",
  "Los permisos de cámara, selección de fotos, archivos, ubicación o notificaciones se solicitan por función. Conceder acceso a una imagen seleccionada no autoriza importar tu fototeca completa. Puedes revocarlos en los ajustes del dispositivo. Las notificaciones promocionales requieren una elección distinta del permiso técnico para recibir notificaciones.",
  "",
  "14. Conservación, bloqueo y borrado",
  "",
  "Conservamos los datos mientras sean necesarios para la cuenta, la función solicitada, el histórico que decidas mantener, soporte, seguridad u obligaciones legales. La mera posibilidad de una controversia no justifica conservación ilimitada. Al terminar la finalidad se eliminarán o anonimizarán, salvo bloqueo o conservación legalmente justificada.",
  "",
  "Los datos locales dependen del almacenamiento del navegador o de la app web. Quitar el icono de la pantalla de inicio no necesariamente borra los datos del navegador ni elimina la cuenta en la nube. Para quitar copias locales utiliza los ajustes de almacenamiento; para la cuenta utiliza el canal de eliminación indicado.",
  "",
  "Cuando una solicitud proceda, la supresión se aplicará a los sistemas bajo control del responsable y se instruirá a los encargados según corresponda. Los respaldos se depurarán conforme a su ciclo y a las obligaciones aplicables; las copias bloqueadas no se usarán para finalidades ordinarias. Se te informarán las restricciones y razones legales de conservación pertinentes.",
  "",
  "Los registros compartidos que incluyan datos de otras personas se evaluarán individualmente. La participación de terceros no autoriza conservar indefinidamente tu identidad o historial económico ni negar de forma automática tu cancelación.",
  "",
  "15. Seguridad y vulneraciones",
  "",
  "El responsable debe mantener medidas administrativas, técnicas y físicas adecuadas al riesgo, incluidos controles de acceso y confidencialidad, protección de credenciales y atención a incidentes. Este Aviso no constituye una certificación de seguridad absoluta ni una renuncia a reclamar incumplimientos del prestador.",
  "",
  "Cuando una vulneración afecte de forma significativa tus derechos patrimoniales o morales, se informará de forma inmediata conforme a la legislación aplicable, con la información pertinente del incidente, datos comprometidos, medidas adoptadas y recomendaciones disponibles para protegerte.",
  "",
  "Reporta accesos o divulgaciones no autorizadas a soporte@thebackyard.com.mx o privacidad@thebackyard.com.mx. No envíes contraseñas, claves bancarias ni documentos completos por canales no solicitados.",
  "",
  "16. Derechos ARCO y procedimiento",
  "",
  "Puedes ejercer Acceso, Rectificación, Cancelación u Oposición por correo a privacidad@thebackyard.com.mx o mediante solicitud en el domicilio del responsable. Incluye tu nombre, cuenta o dato que permita localizarte, medio de respuesta, derecho solicitado y descripción clara de los datos involucrados. Para rectificación, indica los datos correctos y, cuando corresponda, su respaldo.",
  "",
  "Podrá solicitarse información proporcional para acreditar identidad o representación. La comprobación de una solicitud ARCO no es una verificación sistemática de edad de todos los usuarios. Se evitará pedir documentos excesivos o datos ajenos al trámite.",
  "",
  "La determinación se comunicará en un máximo de veinte días y, de resultar procedente, se hará efectiva dentro de los quince días siguientes a esa comunicación. El cómputo, las ampliaciones por una sola vez y las demás incidencias se sujetan a la legislación aplicable. No se impondrán plazos menores de ejercicio ni renuncias a derechos.",
  "",
  "El ejercicio es gratuito, salvo costos legalmente permitidos de reproducción o envío. Si no procede total o parcialmente, se explicarán los motivos y la vía correspondiente. Puedes acudir a la autoridad competente en protección de datos sin agotar un mecanismo privado de solución de controversias.",
  "",
  "17. Revocación y limitación de uso o divulgación",
  "",
  "Puedes revocar un consentimiento o solicitar limitación de uso o divulgación escribiendo a privacidad@thebackyard.com.mx, con tu cuenta, consentimiento o tratamiento afectado, alcance y medio de respuesta. Se aplicará la comprobación proporcional de identidad y se comunicarán la procedencia y efectos dentro de los plazos aplicables al trámite.",
  "",
  "La revocación no tiene efectos retroactivos. Si existe una obligación legal de conservar ciertos datos, se informará su alcance. Retirar marketing no cancela tu cuenta; retirar el consentimiento financiero limita las funciones que lo requieren. La instalación o permanencia de la app no sustituye una autorización expresa.",
  "",
  "18. Eliminación de cuenta",
  "",
  "Puedes iniciar una solicitud de eliminación de cuenta y datos en privacidad@thebackyard.com.mx, indicando la cuenta y un medio para confirmar identidad. Los controles de eliminación que estén disponibles en la aplicación complementan este canal; no es necesario esperar a una nueva pantalla para presentar la solicitud.",
  "",
  "Cerrar sesión, desinstalar el acceso web y eliminar la cuenta son acciones diferentes. El borrado se realizará con las salvedades de conservación y derechos de terceros legalmente justificadas en este Aviso. El derecho de acceso permite solicitar información de tus datos aunque no exista una herramienta específica de exportación.",
  "",
  "19. Personas menores de edad",
  "",
  "Esta etapa del servicio está dirigida a personas de 18 años o más. No solicitamos de manera general fecha de nacimiento, identificación oficial ni biometría para verificar edad. La mayoría de edad se apoya en la declaración del usuario, cuando se recaba; no existe una comprobación documental o técnica de edad por el solo uso del servicio.",
  "",
  "Si advertimos razonablemente que una cuenta pertenece a una persona menor de edad, podremos restringirla y atender la eliminación o tratamiento que corresponda. Padres o tutores pueden comunicarlo a privacidad@thebackyard.com.mx. Un modo junior futuro requeriría reglas, aviso y controles separados, excluyendo las funciones de apuestas.",
  "",
  "20. Cambios y disponibilidad del Aviso",
  "",
  "El texto se publica con identificador de versión. Los cambios se comunicarán mediante el sitio y, cuando sean relevantes para cuentas existentes, por la app o los medios de contacto disponibles. Se solicitará nueva elección cuando cambie una finalidad o lo exija la ley; no se dará por obtenido un consentimiento expreso únicamente por seguir navegando.",
  "",
  "El Aviso Integral está disponible en https://thebackyard.com.mx/privacidad.html y el Simplificado en https://thebackyard.com.mx/privacidad-simplificada.html. Las versiones son aplicables a partir de su publicación y presentación en el flujo correspondiente; no convalidan tratamientos anteriores.",
  "",
  "Anexo. Aviso de Privacidad Simplificado",
  "",
  "Responsable",
  "",
  "Said Abaid Taja, con domicilio en Calle 1 Retorno Osa Menor, Número Exterior 2, Interior 1003, Colonia Reserva Territorial Atlixcáyotl, Localidad San Bernardino Tlaxcalancingo, Municipio San Andrés Cholula, Puebla, C.P. 72820, México. Referencia: Periférico Ecológico. Es responsable del tratamiento de los datos personales de The Backyard.",
  "",
  "Datos y finalidades",
  "",
  "Tratamos identificación y contacto, cuenta, datos deportivos y scores, rondas, grupos, torneos, archivos o imágenes seleccionados, consultas a IA, soporte y datos técnicos de operación y seguridad. Los registros de juegos, saldos y gastos pueden ser financieros o patrimoniales. No solicitamos deliberadamente datos sensibles.",
  "",
  "Los usamos para prestar la cuenta, registro, cálculo deportivo, históricos, funciones compartidas, IA, sincronización, soporte, seguridad y obligaciones legales. Los datos económicos requieren consentimiento expreso separado, salvo excepción legal. Las funciones futuras de pago, ubicación o integraciones no quedan activadas por este aviso.",
  "",
  "Visibilidad y proveedores",
  "",
  "Los participantes y administradores autorizados ven los datos necesarios del contexto compartido. Si se habilita un leaderboard público de Polla Live, nombre o alias, HCP, scores y clasificación deportiva pueden verse mediante enlace o código, previa información y base jurídica aplicable. No se autoriza publicar por ello apuestas privadas ni gastos personales. Los proveedores tecnológicos pueden procesar datos en México, Estados Unidos u otras jurisdicciones.",
  "",
  "Elecciones y derechos",
  "",
  "Marketing es opcional y separado. Puedes negarlo desde su presentación o limitar uso y divulgación, ejercer ARCO, revocar consentimiento y solicitar eliminación en privacidad@thebackyard.com.mx o en el domicilio del responsable. La negativa a marketing no impide las funciones principales. Consulta procedimientos, finalidades y condiciones en https://thebackyard.com.mx/privacidad.html.",
].join("\n");

export const PRIVACY_SIMPLIFIED_TEXT = [
  "Anexo. Aviso de Privacidad Simplificado",
  "",
  "Responsable",
  "",
  "Said Abaid Taja, con domicilio en Calle 1 Retorno Osa Menor, Número Exterior 2, Interior 1003, Colonia Reserva Territorial Atlixcáyotl, Localidad San Bernardino Tlaxcalancingo, Municipio San Andrés Cholula, Puebla, C.P. 72820, México. Referencia: Periférico Ecológico. Es responsable del tratamiento de los datos personales de The Backyard.",
  "",
  "Datos y finalidades",
  "",
  "Tratamos identificación y contacto, cuenta, datos deportivos y scores, rondas, grupos, torneos, archivos o imágenes seleccionados, consultas a IA, soporte y datos técnicos de operación y seguridad. Los registros de juegos, saldos y gastos pueden ser financieros o patrimoniales. No solicitamos deliberadamente datos sensibles.",
  "",
  "Los usamos para prestar la cuenta, registro, cálculo deportivo, históricos, funciones compartidas, IA, sincronización, soporte, seguridad y obligaciones legales. Los datos económicos requieren consentimiento expreso separado, salvo excepción legal. Las funciones futuras de pago, ubicación o integraciones no quedan activadas por este aviso.",
  "",
  "Visibilidad y proveedores",
  "",
  "Los participantes y administradores autorizados ven los datos necesarios del contexto compartido. Si se habilita un leaderboard público de Polla Live, nombre o alias, HCP, scores y clasificación deportiva pueden verse mediante enlace o código, previa información y base jurídica aplicable. No se autoriza publicar por ello apuestas privadas ni gastos personales. Los proveedores tecnológicos pueden procesar datos en México, Estados Unidos u otras jurisdicciones.",
  "",
  "Elecciones y derechos",
  "",
  "Marketing es opcional y separado. Puedes negarlo desde su presentación o limitar uso y divulgación, ejercer ARCO, revocar consentimiento y solicitar eliminación en privacidad@thebackyard.com.mx o en el domicilio del responsable. La negativa a marketing no impide las funciones principales. Consulta procedimientos, finalidades y condiciones en https://thebackyard.com.mx/privacidad.html.",
].join("\n");

export const TERMS_TEXT = [
  "Términos y Condiciones de Uso",
  "",
  "2026-09-08-v2  |  8 de septiembre de 2026",
  "",
  "Prestador actual: Said Abaid Taja",
  "",
  "Texto consolidado. Aplicable a partir de su publicación y presentación en el flujo correspondiente. La actualización documental no acredita por sí sola autorización regulatoria ni implementación técnica.",
  "",
  "1. Prestador, alcance y etapa actual",
  "",
  "The Backyard es el nombre comercial del servicio operado actualmente por Said Abaid Taja, persona física, con domicilio en Calle 1 Retorno Osa Menor, Número Exterior 2, Interior 1003, Colonia Reserva Territorial Atlixcáyotl, Localidad San Bernardino Tlaxcalancingo, Municipio San Andrés Cholula, Puebla, C.P. 72820, México. Referencia: Periférico Ecológico.",
  "",
  "Contacto de servicio y reclamaciones: soporte@thebackyard.com.mx. Datos personales: privacidad@thebackyard.com.mx. Sitio: https://thebackyard.com.mx. App web: https://app.thebackyard.com.mx.",
  "",
  "Estos Términos regulan el sitio, la app web, sus herramientas de golf, funciones compartidas y asistencia. La etapa actual es de pruebas sin cobro por uso. No promete disponibilidad de todas las funciones proyectadas, acceso indefinido gratuito ni una fecha automática de lanzamiento comercial.",
  "",
  "La gratuidad y la fase de pruebas no eliminan obligaciones legales. Si cambia el prestador, se informará su identidad, domicilio y condiciones aplicables antes del cambio, sin suprimir responsabilidades anteriores ni derechos del usuario.",
  "",
  "2. Aceptación y elecciones separadas",
  "",
  "Los Términos se pondrán a tu disposición antes de contratar o habilitar las funciones que requieran aceptación. La manifestación se recabará mediante casilla no premarcada u otra acción inequívoca presentada a tal efecto. La mera visita al sitio no equivale a aceptar obligaciones económicas ni a otorgar consentimiento financiero o de marketing.",
  "",
  "La aceptación contractual no sustituye el Aviso de Privacidad, el consentimiento expreso para datos financieros o patrimoniales, la declaración de mayoría de edad ni las elecciones opcionales que deban recabarse por separado. No podrás aceptar por otros usuarios sin representación válida.",
  "",
  "3. Mayores de edad y cuenta",
  "",
  "El servicio en esta etapa se dirige a mayores de 18 años. No se verifica de forma general la edad mediante fecha de nacimiento, documentos o biometría; una declaración no es una comprobación de edad. Se podrá restringir una cuenta cuando haya indicios razonables de uso por una persona menor.",
  "",
  "Debes utilizar datos razonablemente exactos, proteger tu correo y sesiones, no suplantar identidades y avisar de accesos no autorizados. Esto no traslada al usuario fallas de seguridad atribuibles al prestador.",
  "",
  "4. Qué hace The Backyard",
  "",
  "The Backyard proporciona herramientas para configurar rondas, jugadores, grupos y modalidades; registrar scores e información deportiva; efectuar cálculos; conservar históricos; consultar IA; y, según las funciones disponibles, cursar invitaciones, coordinar captura y mostrar clasificaciones mediante Polla Live.",
  "",
  "Algunos módulos permiten registrar reglas, participantes, importes y resultados de juegos o apuestas que los usuarios acuerdan. La plataforma estructura y facilita información y coordinación además de calcular. No se describe como una calculadora pasiva sin intervención funcional.",
  "",
  "El papel jurídico del servicio depende de las funciones y de la operación efectiva. Su denominación comercial o estas cláusulas no sustituyen la ley, una resolución de autoridad ni un permiso que pudiera resultar exigible.",
  "",
  "5. Fondos, cuotas y pagos entre participantes",
  "",
  "En el modelo actual The Backyard no recibe, concentra, custodia, transfiere ni paga dinero apostado entre usuarios; no mantiene monedero de apuestas, depósito en garantía o fondo común; no financia participantes ni cobra deudas de juego.",
  "",
  "Tampoco fija cuotas de casa u odds para captar apuestas, toma la posición económica contraria al jugador, paga premios de apuestas o cobra comisión, rake o porcentaje sobre las cantidades apostadas, ganadas o perdidas. Los importes visibles son anotaciones calculadas, no dinero disponible para retirar.",
  "",
  "La ausencia de manejo de fondos no constituye por sí sola una exención regulatoria. Los acuerdos o pagos que existan entre usuarios deben ser lícitos y se celebran entre ellos; The Backyard no garantiza su cumplimiento ni determina si una deuda de juego es jurídicamente exigible.",
  "",
  "6. Legalidad del uso y lugar del juego",
  "",
  "Sólo puedes usar las funciones para actividades lícitas en el lugar y bajo las circunstancias en que se desarrollen. Ser amigos, usar un grupo cerrado o jugar en un club de propiedad privada no demuestra por sí mismo que una apuesta esté exceptuada de regulación.",
  "",
  "Estos Términos no equiparan un campo de golf, un club privado o una sala virtual a un domicilio particular ni invocan de forma automática la excepción de los artículos 15 de la Ley Federal de Juegos y Sorteos y 13 de su Reglamento. Tampoco declaran que toda apuesta privada esté permitida.",
  "",
  "La disponibilidad de un botón, modalidad, invitación o cálculo no es autorización para organizar, promover o realizar una actividad que requiera permiso. Las obligaciones de los usuarios no excluyen las que correspondan a The Backyard por sus propios actos.",
  "",
  "7. Usos prohibidos del módulo económico",
  "",
  "No se permite utilizar el servicio para captar apuestas del público o de desconocidos, crear mercados o intermediación de apuestas, operar una casa o negocio de apuestas, cobrar comisión sobre ellas, organizar actividades de juego sujetas a autorización sin contar con ella, o presentar a The Backyard como patrocinador, permisionario, garante o cobrador sin una base válida.",
  "",
  "Tampoco se permite promover apuestas a menores, financiar juego ilícito, defraudar, extorsionar, lavar dinero, manipular resultados para causar daño o eludir restricciones mediante cuentas, grupos o eventos fragmentados.",
  "",
  "Invitaciones deportivas o un marcador público no habilitan captación de apuestas. Incluso si un usuario cuenta con una autorización propia, ello no amplía por sí solo los usos admitidos ni autoriza operaciones de fondos a través de The Backyard.",
  "",
  "8. Escala, frecuencia y restricciones operativas",
  "",
  "No se ofrece un número de usuarios, rondas semanales ni un monto que convierta automáticamente una actividad en legal u ocasional. Los límites técnicos, comerciales o preventivos que pueda fijar The Backyard no son umbrales legales ni permisos.",
  "",
  "Podremos revisar y restringir modalidades ante indicios de captación pública, organización comercial, uso habitual sujeto a autorización, fraude o riesgo de incumplimiento. Se considerarán las circunstancias y los datos estrictamente necesarios bajo el Aviso de Privacidad, sin prometer vigilancia total ni verificación en tiempo real de cada actividad.",
  "",
  "Podremos mantener disponibles las funciones deportivas y restringir las económicas o la creación de determinados eventos de forma diferenciada. Las restricciones se aplicarán proporcionalmente, sin discriminación, y se informarán cuando la ley, la seguridad y las circunstancias lo permitan.",
  "",
  "9. Scores, handicap y cálculos",
  "",
  "Los resultados dependen de los scores, HCP, tees, participantes, ventajas, reglas, importes y correcciones capturados. Revisa la configuración antes de iniciar y los resultados antes de utilizarlos para decisiones deportivas o económicas.",
  "",
  "Un cálculo automático, una foto leída por IA o un dato importado pueden contener errores. No certificamos por el solo uso de la app un handicap oficial, la exactitud de una tarjeta o el resultado de un torneo. Las integraciones oficiales se identificarán cuando estén autorizadas y disponibles.",
  "",
  "Los usuarios no deben alterar datos sin autorización ni manipular capturas. La obligación de verificar sus entradas no excusa errores del software o incumplimientos que sean atribuibles al prestador.",
  "",
  "10. Controversias, correcciones y evidencia",
  "",
  "Las controversias entre participantes sobre acuerdos, cambios de reglas, validez de una apuesta o pagos les corresponden a ellos y, cuando proceda, a las autoridades competentes. The Backyard no asume funciones de juez, árbitro de deudas, fiador o cobrador.",
  "",
  "Esto no excluye las reclamaciones contra The Backyard por errores técnicos, fallas de seguridad, tratamiento de datos u otros actos propios. Podremos investigar reportes, corregir cálculos y brindar información pertinente dentro de la ley, sin decidir por ello la exigibilidad de acuerdos privados.",
  "",
  "Las pantallas, registros y exportaciones no crean por sí solos un título de crédito, sentencia o garantía de pago de The Backyard. Su posible valor probatorio se determina conforme a la ley; no se afirma que los registros digitales carezcan de evidencia ni se permite su destrucción o alteración para eludir obligaciones.",
  "",
  "11. Polla Live: organización deportiva y componente económico",
  "",
  "Polla Live proporciona herramientas diferenciadas de creación y configuración de torneos, invitación de participantes, asignación de grupos, captura compartida, scores y leaderboard. Esa facilitación tecnológica se reconoce expresamente; no equivale a afirmar que The Backyard carece de cualquier participación funcional.",
  "",
  "El usuario que organiza el evento debe contar con las facultades y autorizaciones que legalmente le correspondan, informar reglas deportivas, condiciones de participación y visibilidad, y respetar los derechos de los participantes. Su función no elimina responsabilidades propias de The Backyard o del establecimiento.",
  "",
  "El uso como marcador o torneo deportivo sin registro económico es distinto del uso con importes, premios, aportaciones o apuestas. No se presupone que ambos tengan el mismo tratamiento regulatorio. La plataforma no otorga permisos de juegos o sorteos ni representa contar con uno por la sola existencia de Polla Live.",
  "",
  "La habilitación de un leaderboard público permite difusión deportiva, no convocatoria pública para apostar. En el modelo actual no se recaudan inscripciones destinadas a una bolsa de apuestas, no se custodian premios ni se procesan pagos entre jugadores a través de The Backyard.",
  "",
  "Podremos separar, limitar o deshabilitar componentes económicos, eventos o formas de acceso cuando existan razones jurídicas, de privacidad o seguridad. Cualquier operación distinta requeriría evaluación previa y cumplimiento de las autorizaciones efectivamente aplicables; estos Términos no la autorizan anticipadamente.",
  "",
  "12. IA y reglas de golf",
  "",
  "La IA es apoyo informativo. Puede interpretar mal una consulta o imagen y producir respuestas incorrectas. No sustituye al Comité, al árbitro, a las reglas oficiales y locales aplicables ni a asesoría jurídica.",
  "",
  "Verifica una respuesta antes de aplicarla a una penalidad, descalificación o decisión económica. No uses recomendaciones de la app cuando distraigan durante un golpe o creen un riesgo en el campo. La advertencia sobre IA no elimina obligaciones propias del prestador.",
  "",
  "13. Privacidad, jugadores y publicación de resultados",
  "",
  "El tratamiento de datos se rige por el Aviso en https://thebackyard.com.mx/privacidad.html. No se incorpora una autorización universal de tratamiento al aceptar estos Términos.",
  "",
  "Los administradores deben informar si habilitan una clasificación pública y obtener la base jurídica necesaria para los datos de participantes. Un enlace público puede ser consultado por terceros; no debe contener historiales de apuestas privadas, gastos personales, credenciales ni datos no necesarios. No se permite aceptar consentimientos individuales por otras personas sin facultad válida.",
  "",
  "No puedes exportar ni divulgar datos privados para acosar, presionar pagos o afectar a otro jugador. Compartir una tarjeta con un tercero requiere revisar el contenido y contar con los derechos o autorizaciones correspondientes.",
  "",
  "14. Contenido que subes",
  "",
  "Conservas los derechos que te correspondan sobre el contenido. Nos concedes una licencia no exclusiva y limitada a alojarlo, reproducirlo, procesarlo y mostrarlo a los destinatarios autorizados para prestar la función solicitada, soporte, seguridad y cumplimiento legal.",
  "",
  "La licencia no autoriza venta del contenido, publicidad con tu imagen ni entrenamiento general de IA. Termina al eliminarse el contenido, salvo conservación limitada y legalmente justificada, respaldos sujetos a depuración o copias compartidas por otros usuarios conforme a sus propios derechos.",
  "",
  "Debes contar con derechos sobre los archivos y no cargar malware, contenido ilegal, datos excesivos de terceros ni material que infrinja derechos. El canal de soporte recibe reportes de infracciones.",
  "",
  "15. Propiedad intelectual y datos de terceros",
  "",
  "El software, diseño, nombre, logotipos, documentación y elementos protegibles de The Backyard pertenecen a sus titulares o licenciantes. Se permite el acceso personal y uso conforme a estos Términos; no se autoriza revender el servicio, extraer bases de datos restringidas, copiar código protegido o eludir medidas técnicas, salvo derechos que la ley reconozca.",
  "",
  "Los datos de campos, mapas, handicap y otros servicios externos dependen de sus fuentes y condiciones autorizadas. Mencionar una marca o integración no implica asociación oficial. No se permite usar la app para acceder a cuentas o bases ajenas sin autorización.",
  "",
  "16. Disponibilidad, modo local y pruebas",
  "",
  "La etapa de pruebas puede incluir cambios, errores y mantenimiento. Se atenderán reportes razonables de funcionamiento; no se garantiza operación ininterrumpida ni conservación infalible de cada dato.",
  "",
  "Las funciones locales que estén disponibles dependen del navegador y dispositivo. La sincronización, IA y Polla Live requieren conexión. Instalar un icono no convierte todas las funciones en offline, no garantiza un respaldo y no equivale a instalar una aplicación publicada en App Store o Google Play.",
  "",
  "Borrar datos del navegador, cambiar de dispositivo o eliminar el icono puede afectar información local. Se recomienda conservar copias de resultados importantes. Esto no excluye las obligaciones de almacenamiento y seguridad que correspondan al prestador.",
  "",
  "17. Suscripciones y cobros futuros",
  "",
  "La prueba actual no genera cobros de suscripción ni se transforma automáticamente en una membresía pagada. Antes de ofrecer planes se informarán el prestador, precio total e impuestos, moneda, funciones, duración, periodicidad, fecha y medio de cobro y reglas de cancelación.",
  "",
  "Un cobro recurrente requerirá consentimiento expreso e informado. Cuando proceda renovación automática, se notificará con al menos cinco días naturales de anticipación y se permitirá cancelar sin penalización, con el mecanismo de cancelación inmediata exigido por la legislación aplicable.",
  "",
  "Una futura suscripción pagaría acceso al software; no se calculará como participación sobre apuestas. Esto no determina por sí solo su tratamiento regulatorio. Reembolsos, bonificaciones y otros remedios se sujetarán a derechos legales y condiciones informadas; no se impone una política absoluta de “sin devoluciones”.",
  "",
  "18. Suspensión, baja y revisión",
  "",
  "Podremos suspender una cuenta o función por incumplimiento material, fraude, uso ilícito, riesgo de seguridad, indicios razonables de minoría de edad o requerimiento legal. Siempre que sea procedente, se comunicará la causa y se permitirá aclararla por soporte; no se condiciona una reclamación legítima al pago de una apuesta.",
  "",
  "Puedes dejar de utilizar el servicio y pedir eliminación de cuenta por el canal de privacidad. La baja no implica renuncia de derechos ni obliga a conservar datos por tiempo indefinido. Si en el futuro existe una suscripción pagada, se atenderán además las obligaciones de cancelación o reembolso correspondientes.",
  "",
  "19. Responsabilidad del prestador y límites válidos",
  "",
  "The Backyard responde por los actos u omisiones que legalmente le sean imputables. No se excluyen responsabilidad por dolo, incumplimientos de protección de datos, daños propios cuando sea inválido excluirlos, obligaciones frente al consumidor ni derechos irrenunciables.",
  "",
  "No asumimos una obligación de pagar apuestas de terceros, financiar premios o responder como fiador de acuerdos en los que no somos parte. Las fallas del servicio y los daños que puedan ser atribuibles a The Backyard se analizan por separado; la existencia de una apuesta entre usuarios no los excluye automáticamente.",
  "",
  "No se establece una renuncia general a reclamar ni un límite de responsabilidad de cero por ser una prueba gratuita. La imputación, causalidad y reparación se determinarán conforme a la ley y a las obligaciones válidamente asumidas.",
  "",
  "20. Responsabilidad de usuarios y cumplimiento regulatorio",
  "",
  "Cada persona responderá por sus propios actos ilícitos, fraude, suplantación, infracciones de derechos u organización de actividades no autorizadas, en la medida que establezca la ley. Esta cláusula no traslada al usuario responsabilidades administrativas, penales o civiles que correspondan al prestador.",
  "",
  "La condición de responsable del tratamiento de datos personales no determina por sí sola quién es organizador, facilitador o participante a efectos de juegos y sorteos. Esas calificaciones dependen de los hechos y de la ley. Constituir una sociedad o firmar estos Términos no garantiza inmunidad de las personas involucradas.",
  "",
  "21. Atención de reclamaciones",
  "",
  "Escribe a soporte@thebackyard.com.mx con la cuenta, descripción del problema, fecha y referencia de ronda o torneo; adjunta sólo las capturas necesarias, sin contraseñas ni datos excesivos. Los asuntos de privacidad pueden dirigirse directamente a privacidad@thebackyard.com.mx o al domicilio informado.",
  "",
  "La atención interna no es requisito para acudir a PROFECO, a la autoridad de protección de datos o a los órganos competentes. No reduce plazos legales ni impone arbitraje privado obligatorio.",
  "",
  "22. Cambios a los Términos",
  "",
  "Las nuevas versiones estarán disponibles en el sitio. Los cambios materiales se comunicarán por medios adecuados antes de aplicarlos y requerirán nueva aceptación cuando corresponda. No se modificarán retroactivamente acuerdos ni se impondrán cobros, finalidades o renuncias mediante silencio.",
  "",
  "Si una modificación afecta un servicio pagado, se respetarán las obligaciones de información, cancelación y remedios legales aplicables.",
  "",
  "23. Ley, autoridades y separabilidad",
  "",
  "Se aplica la legislación correspondiente de los Estados Unidos Mexicanos, sin excluir normas obligatorias que resulten aplicables por el lugar de la prestación o del usuario. Conocerán las autoridades y tribunales competentes conforme a la ley; no se obliga al consumidor a renunciar a su jurisdicción protegida.",
  "",
  "Si una cláusula resulta inválida, se aplicará la disposición legal pertinente y el resto subsistirá en lo que sea separable y válido. Nada en estos Términos limita facultades de autoridades ni sustituye autorizaciones de juegos y sorteos.",
].join("\n");

export type LegalDocumentKey = "privacy_integral" | "privacy_simplified" | "terms";

export const LEGAL_DOCUMENTS = {
  privacy_integral: {
    key: "privacy_integral",
    title: "Aviso de Privacidad Integral",
    version: PRIVACY_LEGAL_VERSION,
    effectiveDate: LEGAL_EFFECTIVE_DATE,
    sourceFileHash: LEGAL_SOURCE_HASHES.privacyTxt,
    contentHash: LEGAL_SOURCE_HASHES.privacyPublished,
    path: "/legal/privacy",
    text: PRIVACY_INTEGRAL_TEXT,
  },
  privacy_simplified: {
    key: "privacy_simplified",
    title: "Aviso de Privacidad Simplificado",
    version: PRIVACY_LEGAL_VERSION,
    effectiveDate: LEGAL_EFFECTIVE_DATE,
    sourceFileHash: LEGAL_SOURCE_HASHES.privacyTxt,
    contentHash: LEGAL_SOURCE_HASHES.privacySimplified,
    path: "/legal/privacy-simplified",
    text: PRIVACY_SIMPLIFIED_TEXT,
  },
  terms: {
    key: "terms",
    title: "Términos y Condiciones de Uso",
    version: TERMS_LEGAL_VERSION,
    effectiveDate: LEGAL_EFFECTIVE_DATE,
    sourceFileHash: LEGAL_SOURCE_HASHES.termsTxt,
    contentHash: LEGAL_SOURCE_HASHES.termsPublished,
    path: "/legal/terms",
    text: TERMS_TEXT,
  },
} as const satisfies Record<LegalDocumentKey, {
  key: LegalDocumentKey;
  title: string;
  version: string;
  effectiveDate: string;
  sourceFileHash: string;
  contentHash: string;
  path: string;
  text: string;
}>;

export type LegalEvidenceSubject =
  | "privacy_notice"
  | "terms"
  | "age_declaration"
  | "financial_data"
  | "marketing";

export type LegalEvidenceAction = "presented" | "accepted" | "rejected" | "revoked";

export const LEGAL_EVIDENCE_DEFINITIONS = {
  privacy_notice: {
    documentKey: "privacy_simplified",
    version: PRIVACY_LEGAL_VERSION,
    documentHash: LEGAL_SOURCE_HASHES.privacySimplified,
    allowedActions: ["presented"],
    statements: {
      presented: "Se me presentó el Aviso de Privacidad Simplificado y tuve acceso al Aviso de Privacidad Integral, versión 2026-09-08-v6.",
    },
    statementHashes: {
      presented: "6ed32114df4a74b4dea1da41dd2b38fb7c0dd08bb0cd393bb3015c0851839ca5",
    },
  },
  terms: {
    documentKey: "terms",
    version: TERMS_LEGAL_VERSION,
    documentHash: LEGAL_SOURCE_HASHES.termsPublished,
    allowedActions: ["accepted", "rejected", "revoked"],
    statements: {
      accepted: "He leído y acepto los Términos y Condiciones de Uso, versión 2026-09-08-v2.",
      rejected: "No acepto los Términos y Condiciones de Uso, versión 2026-09-08-v2.",
      revoked: "Revoco mi aceptación de los Términos y Condiciones de Uso, versión 2026-09-08-v2, sin efectos retroactivos.",
    },
    statementHashes: {
      accepted: "7cc5eaf33c2d2e774233c3ed3affbd7d98a52c876d85428191fadfb2ea87cb00",
      rejected: "828be73e0ed7690ba7ca9458fe6e395ab59729f67e6d7fb9f115e184266ce0ba",
      revoked: "c603283665c6475ac58d88a93cadb75e242942167681884d1bfd6ffb30d8791b",
    },
  },
  age_declaration: {
    documentKey: "terms",
    version: TERMS_LEGAL_VERSION,
    documentHash: LEGAL_SOURCE_HASHES.termsPublished,
    allowedActions: ["accepted", "rejected", "revoked"],
    statements: {
      accepted: "Declaro expresamente que tengo 18 años o más. Entiendo que esta declaración no constituye verificación documental de edad.",
      rejected: "No declaro tener 18 años o más.",
      revoked: "Retiro mi declaración de mayoría de edad, sin efectos retroactivos.",
    },
    statementHashes: {
      accepted: "27aadb7dee198eed11aa3ca04d4abfab1e7294761becff07b486c4f4032e173f",
      rejected: "4042964b932f449771317a533dcf4f01e072dd608f7d07d5d6b9d8fca362fcd5",
      revoked: "3f40a845590f1f7f4fe183ab3cf0b73ee6bb1ded8e416ddb22143cfd22e43136",
    },
  },
  financial_data: {
    documentKey: "privacy_integral",
    version: PRIVACY_LEGAL_VERSION,
    documentHash: LEGAL_SOURCE_HASHES.privacyPublished,
    allowedActions: ["accepted", "rejected", "revoked"],
    statements: {
      accepted: "Consiento expresamente el tratamiento de datos financieros o patrimoniales necesario para registrar apuestas privadas, saldos, gastos y resultados económicos.",
      rejected: "No consiento el tratamiento de datos financieros o patrimoniales para apuestas privadas, saldos, gastos y resultados económicos.",
      revoked: "Revoco mi consentimiento para el tratamiento de datos financieros o patrimoniales, sin efectos retroactivos.",
    },
    statementHashes: {
      accepted: "41ddb7fa9e2c2332eb320f32dcede6158493a18ad0f61a6d8fb0ed787a25a620",
      rejected: "02c6e0ce2b40157048f3cf57502eaaca8cd04a2b288cafc6b87da30709e2329d",
      revoked: "a3fe0588b5cc0b5ba7fb1ba5b809844787e770b1f7bf6866292fb5079a33f1ce",
    },
  },
  marketing: {
    documentKey: "privacy_integral",
    version: PRIVACY_LEGAL_VERSION,
    documentHash: LEGAL_SOURCE_HASHES.privacyPublished,
    allowedActions: ["accepted", "rejected", "revoked"],
    statements: {
      accepted: "Consiento recibir comunicaciones promocionales de The Backyard. Esta elección es opcional.",
      rejected: "No consiento recibir comunicaciones promocionales de The Backyard.",
      revoked: "Revoco mi consentimiento para recibir comunicaciones promocionales, sin efectos retroactivos.",
    },
    statementHashes: {
      accepted: "3270203a4cd4b19b720d6876c637115d1eb7fd5f0febef64a19988a7c9b2cce0",
      rejected: "b69273f6e3ae17383a0beba18b8dbdedc0078e8a572456dac7a244b19a89f22c",
      revoked: "d2976d844ed1a7c75b8dd126e2da0be28654c95e9d27d5809f392e02e3a09823",
    },
  },
} as const;

export function legalEvidenceDefinition(subject: LegalEvidenceSubject, action: LegalEvidenceAction) {
  const definition = LEGAL_EVIDENCE_DEFINITIONS[subject];
  if (!(definition.allowedActions as readonly string[]).includes(action)) return null;
  const statement = (definition.statements as Partial<Record<LegalEvidenceAction, string>>)[action];
  const statementHash = (definition.statementHashes as Partial<Record<LegalEvidenceAction, string>>)[action];
  if (!statement || !statementHash) return null;
  return { ...definition, statement, statementHash };
}

const UNNUMBERED_HEADINGS = new Set([
  "Responsable",
  "Datos y finalidades",
  "Elecciones y derechos",
  "Aviso Integral",
]);

export type LegalTextBlock = {
  kind: "title" | "version" | "attribution" | "heading" | "paragraph";
  text: string;
};

export function legalTextBlocks(text: string): LegalTextBlock[] {
  return text.split(/\n\s*\n/).map((block, index) => {
    const value = block.trim();
    if (index === 0) return { kind: "title" as const, text: value };
    if (/^2026-09-08-v\d+\s+\|/.test(value)) return { kind: "version" as const, text: value };
    if (/^(Responsable|Prestador) actual:/.test(value)) return { kind: "attribution" as const, text: value };
    if (/^\d+\.\s+/.test(value) || value === "Anexo. Aviso de Privacidad Simplificado" || UNNUMBERED_HEADINGS.has(value)) {
      return { kind: "heading" as const, text: value };
    }
    return { kind: "paragraph" as const, text: value };
  });
}
