// ISO 3166-2 codes for MX/US/CA cross-checked against Unicode CLDR's
// supplemental/subdivisions.xml. Localized labels are maintained in this file.
// Unicode data: Copyright © 1991-2026 Unicode, Inc. SPDX-License-Identifier: Unicode-3.0
export const PROFILE_SUBDIVISION_ROWS = {
  MX: [
  ["MX-AGU", "Aguascalientes"],
  ["MX-BCN", "Baja California"],
  ["MX-BCS", "Baja California Sur"],
  ["MX-CAM", "Campeche"],
  ["MX-CHH", "Chihuahua"],
  ["MX-CHP", "Chiapas"],
  ["MX-CMX", "Ciudad de México"],
  ["MX-COA", "Coahuila"],
  ["MX-COL", "Colima"],
  ["MX-DUR", "Durango"],
  ["MX-GRO", "Guerrero"],
  ["MX-GUA", "Guanajuato"],
  ["MX-HID", "Hidalgo"],
  ["MX-JAL", "Jalisco"],
  ["MX-MEX", "Estado de México"],
  ["MX-MIC", "Michoacán"],
  ["MX-MOR", "Morelos"],
  ["MX-NAY", "Nayarit"],
  ["MX-NLE", "Nuevo León"],
  ["MX-OAX", "Oaxaca"],
  ["MX-PUE", "Puebla"],
  ["MX-QUE", "Querétaro"],
  ["MX-ROO", "Quintana Roo"],
  ["MX-SIN", "Sinaloa"],
  ["MX-SLP", "San Luis Potosí"],
  ["MX-SON", "Sonora"],
  ["MX-TAB", "Tabasco"],
  ["MX-TAM", "Tamaulipas"],
  ["MX-TLA", "Tlaxcala"],
  ["MX-VER", "Veracruz"],
  ["MX-YUC", "Yucatán"],
  ["MX-ZAC", "Zacatecas"],
  ],
  US: [
  ["US-AK", "Alaska"],
  ["US-AL", "Alabama"],
  ["US-AR", "Arkansas"],
  ["US-AS", "Samoa Americana"],
  ["US-AZ", "Arizona"],
  ["US-CA", "California"],
  ["US-CO", "Colorado"],
  ["US-CT", "Connecticut"],
  ["US-DC", "Distrito de Columbia"],
  ["US-DE", "Delaware"],
  ["US-FL", "Florida"],
  ["US-GA", "Georgia"],
  ["US-GU", "Guam"],
  ["US-HI", "Hawái"],
  ["US-IA", "Iowa"],
  ["US-ID", "Idaho"],
  ["US-IL", "Illinois"],
  ["US-IN", "Indiana"],
  ["US-KS", "Kansas"],
  ["US-KY", "Kentucky"],
  ["US-LA", "Luisiana"],
  ["US-MA", "Massachusetts"],
  ["US-MD", "Maryland"],
  ["US-ME", "Maine"],
  ["US-MI", "Míchigan"],
  ["US-MN", "Minnesota"],
  ["US-MO", "Misuri"],
  ["US-MP", "Islas Marianas del Norte"],
  ["US-MS", "Misisipi"],
  ["US-MT", "Montana"],
  ["US-NC", "Carolina del Norte"],
  ["US-ND", "Dakota del Norte"],
  ["US-NE", "Nebraska"],
  ["US-NH", "Nuevo Hampshire"],
  ["US-NJ", "Nueva Jersey"],
  ["US-NM", "Nuevo México"],
  ["US-NV", "Nevada"],
  ["US-NY", "Nueva York"],
  ["US-OH", "Ohio"],
  ["US-OK", "Oklahoma"],
  ["US-OR", "Oregón"],
  ["US-PA", "Pensilvania"],
  ["US-PR", "Puerto Rico"],
  ["US-RI", "Rhode Island"],
  ["US-SC", "Carolina del Sur"],
  ["US-SD", "Dakota del Sur"],
  ["US-TN", "Tennessee"],
  ["US-TX", "Texas"],
  ["US-UM", "Islas menores alejadas de EE. UU."],
  ["US-UT", "Utah"],
  ["US-VA", "Virginia"],
  ["US-VI", "Islas Vírgenes de EE. UU."],
  ["US-VT", "Vermont"],
  ["US-WA", "Washington"],
  ["US-WI", "Wisconsin"],
  ["US-WV", "Virginia Occidental"],
  ["US-WY", "Wyoming"],
  ],
  CA: [
  ["CA-AB", "Alberta"],
  ["CA-BC", "Columbia Británica"],
  ["CA-MB", "Manitoba"],
  ["CA-NB", "Nuevo Brunswick"],
  ["CA-NL", "Terranova y Labrador"],
  ["CA-NS", "Nueva Escocia"],
  ["CA-NT", "Territorios del Noroeste"],
  ["CA-NU", "Nunavut"],
  ["CA-ON", "Ontario"],
  ["CA-PE", "Isla del Príncipe Eduardo"],
  ["CA-QC", "Quebec"],
  ["CA-SK", "Saskatchewan"],
  ["CA-YT", "Yukón"],
  ],
} as const;
