import type { Course, HoleScore, PersonalBet, Player } from "../../lib/types";

// Exact scores/SI/expectations supplied by the user, NOT generated by the engine.
export const realSI = [4,16,8,18,6,14,12,2,10,11,7,17,13,1,3,9,15,5];
export const realGross = {
  said: [5,4,6,2,5,4,4,4,6,5,5,5,5,4,6,4,3,5],
  carlos: [4,3,4,4,4,4,3,4,5,5,5,2,4,3,5,3,2,4],
  juan: [5,3,7,3,7,2,4,5,7,6,4,4,5,6,5,6,3,5],
  flavio: [4,5,4,3,5,3,4,6,8,5,5,3,7,7,5,6,6,5],
  javier: [4,5,5,3,5,4,4,5,7,6,4,3,6,5,5,4,3,6],
};
export const realPlayers: Player[] = Object.keys(realGross).map((id) => ({ id, name: id === "juan" ? "José Juan" : id, handicap: 36 }));
// Par is irrelevant to Personal arithmetic; exact course pars are loaded from the app's course fixture in browser QA.
export const realCourse: Course = { id: "real-temporary", name: "Temporary | La Vista Country Club", teeName: "Regresión SI", holes: realSI.map((strokeIndex,i) => ({number:i+1, strokeIndex, par:4})) };
export const realOrder = realSI.map((_,i) => i+1);
export const realScores: Record<number,HoleScore> = Object.fromEntries(realOrder.map((h) => [h,Object.fromEntries(Object.entries(realGross).map(([id,scores]) => [id,scores[h-1]]))]));
export const realCases = [
  { id:"carlos", strokes:12, receives:"owner", match:[0,-1,-1], medal:[1,-3,-2], money:[0,100,-300,-200,-100,-100], gross:[100,700], net:-600 },
  { id:"juan", strokes:5, receives:"rival", match:[1,-1,0], medal:[1,-1,0], money:[100,100,-200,-200,0,0], gross:[200,400], net:-200 },
  { id:"flavio", strokes:5, receives:"rival", match:[1,1,2], medal:[0,4,4], money:[100,0,200,300,100,100], gross:[800,0], net:800 },
  { id:"javier", strokes:7, receives:"rival", match:[0,-1,-1], medal:[-1,-4,-5], money:[0,-100,-300,-200,-100,-100], gross:[0,800], net:-800 },
] as const;
export function realPersonal(c: typeof realCases[number]): PersonalBet & { carryEnabled:boolean; nassauVersion:2 } {
  return { id:c.id, rivalMode:"group", rivalPlayerId:c.id, rivalName:c.id, externalScores:{}, baseValue:100,
    advantageReceiver:c.receives, advantageStrokes:c.strokes, back9Multiplier:1, pressureMultiplier:2,
    carryEnabled:true, nassauVersion:2,
    components:{match1:true,medal1:true,match2:true,medal2:true,match18:true,medal18:true} };
}
